const DATA = [
  {
    "id": "CHIH-2024-001",
    "fecha": "2024-09-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "6. Dip. Roberto Arturo Medina Aguirre (PRI).- Proposición con carácter de punto de acuerdo, que pretende exhortar a la Comisión Federal de Electricidad, a través de su Superintendente en Chihuahua, para que brinde atención a la ciudadanía que presente quejas sobre los altos cobros que se están dando en diversas regiones del Estado, no se realicen cortes en el servicio, y se otorgue facilida",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6725.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1940&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Subtema corregido: ENE_REG→ENE_TAR (exhorto a CFE por altos cobros eléctricos) | Scraping automático — sesID:1940"
  },
  {
    "id": "CHIH-2024-002",
    "fecha": "2024-09-17",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "1. Dip. Ismael Pérez Pavía (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar al Poder Ejecutivo Federal, a través de las Secretarías de Infraestructura, Comunicaciones y Transportes, y de Hacienda y Crédito Público, a la próxima titular de la Presidencia de la República, realicen las gestiones para liberar recursos y estos sean utilizados para la conservación de",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6760.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1942&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Subtema corregido: MOV_TP→MOV_INF (carreteras federales Chihuahua, término 'carretera' fuera de extracto 400 chars) | Scraping automático — sesID:1942 | [Duplicado-carreteras-fed/grupo-A]"
  },
  {
    "id": "CHIH-2024-003",
    "fecha": "2024-09-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "2. Dip. Ismael Pérez Pavía (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar al Poder Ejecutivo Federal, a través de las Secretarías de Infraestructura, Comunicaciones y Transportes, y de Hacienda y Crédito Público, a la próxima titular de la Presidencia de la República, realicen las gestiones para liberar recursos y estos sean utilizados para la conservación de",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6774.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1943&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Subtema corregido: MOV_TP→MOV_INF (carreteras federales Chihuahua, extracto truncado) | Scraping automático — sesID:1943 | [Duplicado-carreteras-fed/grupo-A]"
  },
  {
    "id": "CHIH-2024-004",
    "fecha": "2024-09-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "4. Dip. Pedro Torres Estrada (MORENA).- Proposición con carácter de punto de acuerdo, con el propósito de exhortar al H. Congreso de la Unión, así como al titular de la Secretaría de Infraestructura, Comunicaciones y Transportes, para que continúen con el proyecto de reforma que regularía el transporte a través de plataformas digitales de movilidad en los aeropuertos; así mismo, a la tit",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6777.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1943&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1943 | [Duplicado-plataformas-dig/grupo-B]"
  },
  {
    "id": "CHIH-2024-005",
    "fecha": "2024-09-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "8. Dip. Pedro Torres Estrada (MORENA).- Proposición con carácter de punto de acuerdo, con la intención de exhortar al H. Congreso de la Unión, así como al titular de la Secretaría de Infraestructura, Comunicaciones y Transportes, para que continúen con el proyecto de reforma que regularía el transporte a través de plataformas digitales de movilidad en los aeropuertos; así mismo, a la tit",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6803.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1944&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1944 | [Duplicado-plataformas-dig/grupo-B]"
  },
  {
    "id": "CHIH-2024-006",
    "fecha": "2024-10-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "1. Dip. Ismael Pérez Pavía (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar al Ejecutivo Federal, a través de las Secretarías de Infraestructura, Comunicaciones y Transportes, y de Hacienda y Crédito Público, para que realicen las gestiones para liberar recursos y sean utilizados para la conservación de las carreteras federales en el Estado; así como al H. Congr",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6871.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1947&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1947 | [Duplicado-carreteras-fed/grupo-A]"
  },
  {
    "id": "CHIH-2024-007",
    "fecha": "2024-10-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "4. Dip. Pedro Torres Estrada (MORENA).- Proposición con carácter de punto de acuerdo, por la que pretende exhortar a la Secretaría General de Gobierno, para que a través de la Subsecretaría de Transporte, reestablezca la ruta de transporte público denominada El Porvenir.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6865.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1947&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1947"
  },
  {
    "id": "CHIH-2024-008",
    "fecha": "2024-10-08",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "3. Dip. Carlos Alfredo Olson San Vicente (PAN).- Iniciativa con carácter de decreto, con el propósito de adicionar la fracción VI, al artículo 44 de la Ley de Vialidad y Tránsito para el Estado de Chihuahua, a fin de expedir placas de circulación de autos clásicos.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6877.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1948&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_SEG — placas de circulación dentro de Ley de Vialidad y Tránsito | Scraping automático — sesID:1948"
  },
  {
    "id": "CHIH-2024-009",
    "fecha": "2024-10-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "3. Dip. María Antonieta Pérez Reyes (MORENA).- Proposición con carácter de punto de acuerdo, por la que pretende exhortar al Cabildo de Juárez, para que se lleven a cabo modificaciones al Reglamento de Vialidad y Tránsito, relativo a las líneas de cruce de los puentes internacionales.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6911.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1950&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_INF→MOV_SEG — modificación reglamentaria sobre líneas de cruce, materia de tránsito | Scraping automático — sesID:1950"
  },
  {
    "id": "CHIH-2024-010",
    "fecha": "2024-10-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "5. Dip. Yesenia Guadalupe Reyes Calzadías (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar a la titular del Poder Ejecutivo Federal, para que a través de la Secretaría de Infraestructura, Comunicaciones y Transporte, se incluyan las carreteras federales de la zona noroeste del Estado, en el programa Bachetón.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6914.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1950&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1950"
  },
  {
    "id": "CHIH-2024-011",
    "fecha": "2024-10-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "2. Dip. Saúl Mireles Corral (PAN).- Iniciativa con carácter de decreto, a efecto de adicionar el artículo 212 Ter al Código Penal del Estado de Chihuahua, en materia de robo de vehículos en carreteras o vías de comunicación dentro del territorio estatal.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6921.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1951&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_INF→MOV_SEG — tipo penal por robo en carreteras, seguridad vial/delictiva | ⚠ Posible falso positivo: adicionar tipo penal (robo en carreteras) — no es infraestructura vial. Verificar PDF. | Scraping automático — sesID:1951"
  },
  {
    "id": "CHIH-2024-012",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "1. Dip. Elizabeth Guzmán Argueta (MORENA).- Iniciativa con carácter de decreto, a efecto de reformar diversas disposiciones de la Ley de Vialidad y Tránsito para el Estado de Chihuahua, en materia de licencias de conducir permanentes de automovilista particular.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6959.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1952&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1952"
  },
  {
    "id": "CHIH-2024-013",
    "fecha": "2024-10-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "3. Dip. Oscar Daniel Avitia Arellanes (MORENA).- Proposición con carácter de punto de acuerdo, a fin de exhortar a lase titulares de los Poderes Ejecutivo Federal y Estatal, así como a los 67 Ayuntamientos, se realicen los oficios para realizar la coordinación y cooperación debida con miras a garantizar una disminución en el costo de la energía eléctrica.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6962.pdf",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1952&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Subtema corregido: ENE_REG→ENE_TAR (disminución costo energía eléctrica) | Scraping automático — sesID:1952"
  },
  {
    "id": "CHIH-2024-014",
    "fecha": "2024-10-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "4. Dip. Ismael Pérez Pavía (PAN).- Proposición con carácter de punto de acuerdo, por la que se pretende exhortar a las legislaturas de las 32 entidades federativas, a analizar exhaustivamente la reforma energética recientemente aprobada y, en su caso, adoptar medidas legislativas que salvaguarden los intereses de sus ciudadanos y promuevan un desarrollo energético sostenible.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6949.doc",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1952&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1952"
  },
  {
    "id": "CHIH-2024-015",
    "fecha": "2024-10-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "0. Dip. Roberto Arturo Medina Aguirre (PRI).- Proposición con carácter de punto de acuerdo, con la intención de exhortar al Gobierno Federal, por conducto de la Secretaría de Relaciones Exteriores, así como al Gobierno del Estado, a que se pronuncien en contra del cierre del cruce de vehículos de carga en el Puente Internacional Córdova-Américas, a efecto de mantener las relacionas comerci",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6957.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1952&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1952"
  },
  {
    "id": "CHIH-2024-016",
    "fecha": "2024-10-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "4. Dip. Magdalena Rentería Pérez (MORENA).- Proposición con carácter de punto de acuerdo, con el propósito de exhortar a Gobierno del Estado, por medio de la Secretaría General de Gobierno, a proporcionar un informe financiero y presupuestal del uso del Fondo de Movilidad, previsto en la Ley de Transporte del Estado de Chihuahua.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6975.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1954&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1954"
  },
  {
    "id": "CHIH-2024-017",
    "fecha": "2024-10-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "6. Dip. Alma Yesenia Portillo Lerma (MC).- Proposición con carácter de punto de acuerdo, con la finalidad de exhortar a los municipios del Estado, a retirar los parquímetros instalados y abstenerse de colocar nuevos dispositivos en las zonas hospitalarias, así como buscar estacionamientos gratuitos o convenios de tarifas reducidas para usuarios de servicios hospitalarios.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6979.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1954&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_ACT — parquímetros en zonas hospitalarias, accesibilidad de usuarios | Scraping automático — sesID:1954 | [Duplicado-parquimetros/grupo-C]"
  },
  {
    "id": "CHIH-2024-018",
    "fecha": "2024-10-29",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "6. Dip. Ã“scar Daniel Avitia Arellanes (MORENA).- ProposiciÃ³n con carÃ¡cter de punto de acuerdo, a efecto de exhortar a la SecretarÃ­a General de Gobierno, para que, de manera coordinada con la SubsecretarÃ­a de Transporte del Estado, inspeccionen y vigilen las condiciones mecÃ¡nicas, asÃ­ como la calidad y seguridad de los autobuses dedicados al transporte forÃ¡neo de carÃ¡cter privado de nuestr",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/6999.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1955&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_SEG — inspección de condiciones mecánicas de autobuses, seguridad del servicio | Scraping automático — sesID:1955"
  },
  {
    "id": "CHIH-2024-019",
    "fecha": "2024-10-31",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "1. Dip. Alma Yesenia Portillo Lerma (MC).- Proposición con carácter de punto de acuerdo, con la finalidad de exhortar a los municipios del Estado, a retirar los parquímetros instalados y abstenerse de colocar nuevos dispositivos en las zonas hospitalarias, así como buscar estacionamientos gratuitos o convenios de tarifas reducidas para usuarios de servicios hospitalarios.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7011.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1957&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_ACT — retiro de parquímetros zonas hospitalarias, accesibilidad | Scraping automático — sesID:1957 | [Duplicado-parquimetros/grupo-C]"
  },
  {
    "id": "CHIH-2024-020",
    "fecha": "2024-11-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "9. Dip. José Luis Villalobos García (PRI).- Iniciativa con carácter de decreto, a efecto de reformar y adicionar el artículo 13, fracción XI de la Ley para Prevenir y Erradicar la Discriminación del Estado de Chihuahua, en materia de implementación de ajustes con diseño universal, para garantizar el acceso y libre desplazamiento de personas con discapacidad. * Asunto incorporado en Mesa Di",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7059.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1960&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1960"
  },
  {
    "id": "CHIH-2024-021",
    "fecha": "2024-11-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "3. Dip. Edna Xóchitl Contreras Herrera (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar al Presidente Municipal de Juárez, así como a la empresa Ferrocarril mexicano S.A. de C.V., y a la Secretaría de Infraestructura, Comunicaciones y Transporte, división Chihuahua, para que se instale una mesa de diálogo con la sociedad civil, en relación a la construcción del",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7052.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1960&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_INF — ferrocarril y mesa de diálogo, infraestructura | Scraping automático — sesID:1960"
  },
  {
    "id": "CHIH-2024-022",
    "fecha": "2024-11-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "1. Dip. Alma Yesenia Portillo Lerma (MC).- Proposición con carácter de punto de acuerdo, a fin de exhortar a la Secretaría de Hacienda y Crédito Público y a la Comisión Reguladora de Energía (CRE), con respecto al precio del gas LP en la entidad.",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7082.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1963&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Subtema corregido: ENE_REG→ENE_HC (precio gas LP = gas licuado de petróleo) | Scraping automático — sesID:1963"
  },
  {
    "id": "CHIH-2024-023",
    "fecha": "2024-12-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "2. Dip. Ã“scar Daniel Avitia Arellanes (MORENA).- ProposiciÃ³n con carÃ¡cter de punto de acuerdo, a fin de exhortar a la ComisiÃ³n de ProgramaciÃ³n, Presupuesto y Hacienda PÃºblica, con la finalidad de aprobar la creaciÃ³n de un fondo de atenciÃ³n prioritaria para infraestructura y movilidad urbana, financiado con la creaciÃ³n del impuesto del 1.5% a las plataformas digitales que pretende adiciona",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7146.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1967&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: MOV_TP→MOV_INF — fondo para infraestructura y movilidad urbana | Scraping automático — sesID:1967"
  },
  {
    "id": "CHIH-2025-001",
    "fecha": "2025-01-31",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "2. Dip. Magdalena Rentería Pérez (MORENA).- Proposición con carácter de punto de acuerdo, a fin de exhortar al Poder Ejecutivo Estatal, por medio de la Secretaría General de Gobierno, para que realice un diagnóstico del transporte público en sur oriente en Juárez, con la finalidad de determinar la necesidad de más camiones y rutas en dicho sector urbano. * Asunto retirado",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/7256.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=1983&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "Scraping automático — sesID:1983"
  },
  {
    "id": "CHIH-2026-001",
    "fecha": "2026-03-31",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "1. Dip. Arturo Zubía Fernández (PAN).- Proposición con carácter de punto de acuerdo, a efecto de exhortar a la Secretaría de Energía, a la Comisión Reguladora de Energía",
    "resumen": "",
    "link_documento": "https://www.congresochihuahua2.gob.mx/archivosDocumentosSesiones/8576.docx",
    "link_portal": "https://www.congresochihuahua.gob.mx/detalleSesion.php?idsesion=2107&tipo=documento&id=&idtipodocumento=",
    "fuente_verificada": "No",
    "notas": "GPT-audit: ENE_REG→ENE_HC provisional — SENER+CRE sin texto completo; requiere verificación | Scraping automático — sesID:2107"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};