const SUBTEMAS = {
  ENE_GEN: "Generación y transición energética",
  ENE_TAR: "Tarifas, subsidios y suministro eléctrico",
  ENE_HC: "Hidrocarburos, carbón, gas",
  ENE_EF: "Eficiencia energética",
  ENE_REG: "Marco regulatorio energético",
  MOV_ELEC: "Electromovilidad",
  MOV_ACT: "Movilidad activa y accesibilidad",
  MOV_TP: "Transporte público y carga",
  MOV_INF: "Infraestructura vial",
  MOV_SEG: "Seguridad vial"
};

const DATA = [
  {
    "id": "COAH-2024-002",
    "fecha": "2024-03-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se adiciona un segundo párrafo al artículo 52 de la Ley de Transporte y Movilidad Sustentable para el Estado de Coahuila de Zaragoza: en municipios de hasta 250 mil habitantes podrán operar unidades con capacidad mínima de 8 pasajeros sentados.",
    "resumen": "Adiciona segundo párrafo al artículo 52 de la Ley de Transporte y Movilidad Sustentable: en municipios de hasta 250 mil habitantes, previo estudio técnico y con aprobación de la Secretaría, se podrán usar unidades de transporte público con capacidad no inferior a ocho pasajeros sentados.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/1945/4001_20240320.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-003",
    "fecha": "2024-04-30",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SICT para subsanar las licitaciones canceladas del Programa Nacional de Conservación de Carreteras 2024 en Coahuila, tras los recortes presupuestales de la SHCP.",
    "resumen": "Conservación de carreteras federales en Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10787/20240430_F_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-004",
    "fecha": "2024-06-04",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 38 ayuntamientos de Coahuila para mejorar la accesibilidad universal en vialidades y espacios públicos para personas con discapacidad y movilidad reducida.",
    "resumen": "Accesibilidad urbana para personas con discapacidad en municipios de Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10806/20240604_F_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-005",
    "fecha": "2024-06-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Se adiciona el inciso d) a la fracción I del artículo 5 y se reforman el inciso f) de la fracción II y el inciso c) de la fracción V del artículo 18, así como la fracción II del artículo 22 de la Ley para el Impulso Emprendedor del Estado de Coahuila de Zaragoza. En relación a apoyos y programas que incentiven el espíritu empresarial en el sector de las energías renovables y la implementación de tecnologías y procesos limpios.",
    "resumen": "Adiciona incentivos para el sector de las energías renovables y la implementación de tecnologías y procesos limpios en la Ley para el Impulso Empresarial del Estado de Coahuila de Zaragoza.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/1966/20240625_018_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-006",
    "fecha": "2024-06-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Decreto 082-24 — ARTÍCULO ÚNICO.- Se Deroga la \"Tabla de Valores para Explotación de Energía Eólica\", del Decreto número 646 publicado en el Periódico Oficial del Gobierno del Estado de fecha 22 de diciembre de 2023.",
    "resumen": "Deroga la 'Tabla de Valores para Explotación de Energía Eólica' (Decreto 444) y la Tabla de Valores de Suelo y Construcción del municipio de General Cepeda, para el ejercicio fiscal 2024.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dec/1779/Decreto082-24.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-007",
    "fecha": "2024-07-02",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorto a autoridades estatales y municipales para que fortalezcan campañas de educación y respeto vial dirigidas a peatones y ciclistas.",
    "resumen": "Campañas de educación vial para protección de peatones y ciclistas.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10826/20240702_H_PA Fortalezcan campañas de educación y respeto vial a peatones y ciclistas.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-008",
    "fecha": "2024-09-10",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorto en materia de movilidad y accesibilidad de las personas con discapacidad en el sistema de transporte estatal.",
    "resumen": "Accesibilidad en transporte para personas con discapacidad.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10857/20240910_C_PA Movilidad y accesibilidad de las personas con discapacidad.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-009",
    "fecha": "2024-09-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se adiciona la fracción V al artículo 104 de la Ley de Transporte y Movilidad Sustentable para el Estado de Coahuila de Zaragoza: la localización y demanda voluntaria de escuelas y universidades como punto para definir rutas de transporte público, garantizando disponibilidad y acceso del servicio a estudiantes.",
    "resumen": "Reforma la Ley de Transporte para que las rutas de transporte público consideren la localización de escuelas y universidades como criterio de demanda.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/1987/20240924_034_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-010",
    "fecha": "2024-10-08",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se reforma la fracción XXI del artículo 105 de la Ley de Transporte y Movilidad Sustentable para el Estado de Coahuila de Zaragoza: los concesionarios y permisionarios del transporte deben proporcionar capacitación continua y permanente a sus operadores, con especial énfasis en el trato digno a personas adultas mayores.",
    "resumen": "Obliga a concesionarios de transporte público a capacitar a sus operadores de forma continua, con énfasis en trato digno a personas adultas mayores.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/1994/20241008_041_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-011",
    "fecha": "2024-10-15",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Exhorto para implementar políticas públicas de movilidad sustentable en el Estado de Coahuila.",
    "resumen": "Políticas públicas de movilidad sustentable.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10882/20241015_C_PA Políticas públicas de movilidad sustentable.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-012",
    "fecha": "2024-10-15",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto para gestionar recursos destinados a la construcción del puente a desnivel que conecta los municipios de Allende y Morelos.",
    "resumen": "Puente a desnivel entre Allende y Morelos.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10883/20241015_D_PA Puente a desnivel que conecta a los municipios de Allende y Morelos.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-013",
    "fecha": "2024-10-29",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SCT para que realice mantenimiento al tramo carretero Sabinas–Monclova.",
    "resumen": "Mantenimiento carretera Sabinas–Monclova (SCT).",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10903/20241029_E_PA SCT Mantenimiento al tramo carretero Sabinas-Monclova.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-014",
    "fecha": "2024-10-29",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto para gestionar recursos federales destinados a proyectos carreteros en el Estado de Coahuila.",
    "resumen": "Recursos para proyectos carreteros en Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10904/20241029_F_PA Recursos para Proyectos Carreteros.pdf",
    "link_portal": "",
    "fuente_verificada": "URL inaccesible — nombre de archivo con espacios",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2024-015",
    "fecha": "2024-12-12",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SICT y CAPUFE para rectificar el tramo denominado \"Los Chorros\" de la carretera 57 y retirar topes reductores de velocidad que causan accidentes.",
    "resumen": "Corrección de trazo vial y retiro de topes peligrosos en carretera federal 57.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10945/20241212_F_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-001",
    "fecha": "2025-01-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Exhorto a la CFE para actualizar las líneas de transmisión eléctrica y sistemas subterráneos en el municipio de Torreón.",
    "resumen": "Modernización de infraestructura de transmisión eléctrica en Torreón.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10966/20250109_B_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-002",
    "fecha": "2025-01-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto a la CFE para instalar cajeros automáticos o terminales de cobro en Monclova y Frontera, facilitando el pago del servicio eléctrico a los usuarios.",
    "resumen": "Acceso a puntos de pago del servicio eléctrico en municipios de Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10967/20250109_C_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-003",
    "fecha": "2025-01-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto a la CFE para resolver las fallas recurrentes en el suministro de energía eléctrica en Boquillas del Carmen, municipio de Ocampo.",
    "resumen": "Servicio eléctrico en zonas rurales y remotas de Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10968/20250109_D_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-004",
    "fecha": "2025-01-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Exhorto al Ejecutivo Federal para cumplir los compromisos internacionales de México en materia de energías renovables y eficiencia energética, establecidos en el Acuerdo de París y agenda climática.",
    "resumen": "Cumplimiento de compromisos de transición energética y renovables ante organismos internacionales.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10969/20250109_E_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-005",
    "fecha": "2025-01-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto a la CFE para fortalecer la protección de la infraestructura eléctrica en Coahuila ante la temporada de frentes fríos y garantizar la continuidad del servicio.",
    "resumen": "Resiliencia del servicio eléctrico ante condiciones climáticas adversas en Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10970/20250109_F_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-006",
    "fecha": "2025-01-14",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SE, SEMARNAT y CRE para diseñar políticas de reconversión responsable de la minería de carbón ante el auge de las nuevas energías y la transición energética global.",
    "resumen": "Política de minería responsable y reconversión del sector carbonífero frente a la transición energética.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10971/20250114_A_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-007",
    "fecha": "2025-02-25",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SICT y a la CANACAR para fortalecer la vigilancia del autotransporte federal de carga y la capacitación obligatoria de conductores en Coahuila.",
    "resumen": "Regulación y capacitación del autotransporte federal de carga.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10986/20250225_A_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-008",
    "fecha": "2025-02-25",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SADER para difundir el Programa Especial de Energía para Uso Agropecuario (PEUA) entre los productores del campo coahuilense.",
    "resumen": "Acceso a tarifas preferenciales de energía para productores agrícolas en Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/10991/20250225_F_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-009",
    "fecha": "2025-04-01",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto a la SEGOB, SICT y Secretarías de Estado para gestionar la construcción del puente internacional en la zona de la Tribu Kikapú en Coahuila.",
    "resumen": "Construcción de puente internacional para la comunidad indígena Kikapú.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11018/20250401_B_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-010",
    "fecha": "2025-04-01",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 38 ayuntamientos de Coahuila para impulsar la movilidad ecológica y el ciclismo urbano como alternativas de transporte sostenible.",
    "resumen": "Fomento del ciclismo urbano y movilidad ecológica en municipios coahuilenses.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11019/20250401_C_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-011",
    "fecha": "2025-04-08",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Transporte y Movilidad Sustentable del Estado de Coahuila: adición de la fracción V al artículo 164.",
    "resumen": "Reforma legislativa a la Ley de Transporte y Movilidad Sustentable de Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11030/20250408_B_REFORMA_LEY.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-012",
    "fecha": "2025-04-08",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Decreto 248-25 — ARTÍCULO ÚNICO.- Se adiciona la fracción V al artículo 104 de la Ley de Transporte y Movilidad Sustentable: la localización y demanda de escuelas, centros educativos, universidades y tecnológicos, promoviendo la disponibilidad, eficiencia y seguridad en la prestación del servicio a estudiantes.",
    "resumen": "Decreto aprobado: rutas de transporte público deben considerar la proximidad a escuelas, universidades y tecnológicos. (Complementa COAH-2024-009).",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dec/1945/Decreto248-25.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-013",
    "fecha": "2025-07-08",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Exhorto a la Secretaría de Turismo Federal y a la SICT para impulsar y ampliar la presencia de los aeropuertos de Coahuila en la industria turística nacional e internacional.",
    "resumen": "Promoción de aeropuertos de Coahuila como motor del turismo y conectividad aérea.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11107/20250708_O_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-014",
    "fecha": "2025-08-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa popular (136 pp.) que reforma y adiciona diversos artículos de la Ley de Transporte y Movilidad Sustentable del Estado de Coahuila de Zaragoza, y adiciona un nuevo capítulo y artículos al Código Penal de Coahuila de Zaragoza en materia de delitos de tránsito y seguridad vial.",
    "resumen": "Iniciativa ciudadana de Héctor Manuel Garza Martínez: introduce delitos de tránsito y sanciones penales para conductores en el Código Penal, y refuerza obligaciones de seguridad vial en la Ley de Transporte.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2097/15_20250820.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-015",
    "fecha": "2025-09-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "Se adiciona un nuevo contenido a la fracción XXXIV, recorriendo el actual a la siguiente, haciendo lo propio con las demás fracciones del artículo 3 de la Ley del Equilibrio Ecológico y la Protección al Ambiente del Estado de Coahuila de Zaragoza. En materia de electromovilidad en México.",
    "resumen": "Adición de la definición de 'electromovilidad' a la fracción XXXIV del artículo 3 de la Ley del Equilibrio Ecológico y la Protección al Ambiente del Estado de Coahuila de Zaragoza. MOV_ELEC confirmado: la ley ambiental incorpora electromovilidad como concepto.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2099/20250917_117_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-016",
    "fecha": "2025-10-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se reforma la fracción XIV del artículo 281, se adicionan el artículo 278 Bis, un segundo párrafo al artículo 284, y la fracción XV al artículo 281, de la Ley de Transporte y Movilidad Sustentable para el Estado de Coahuila de Zaragoza. En relación a garantizar la prestación del servicio de estacionamiento en los establecimientos comerciales.",
    "resumen": "Reforma la Ley de Transporte y Movilidad Sustentable para establecer la obligación de contar con espacios de estacionamiento en establecimientos comerciales, con criterios de capacidad y seguridad vial.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2134/20251028_141_UDC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-017",
    "fecha": "2025-12-09",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Se adiciona la fracción IX al artículo 142 del Código Municipal para el Estado de Coahuila de Zaragoza: como parte de los objetivos de la planeación del desarrollo municipal, se establece la obligación de garantizar el cumplimiento de las normas de accesibilidad para personas con discapacidad, adultas mayores y con movilidad reducida.",
    "resumen": "Código Municipal: la planeación del desarrollo municipal debe garantizar la accesibilidad universal para personas con discapacidad, adultas mayores y movilidad reducida.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2176/20251209_174_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-018",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Se adiciona la fracción XI (recorriendo subsecuentes) del artículo 3° y se reforma el artículo 245 de la Ley de Asentamientos Humanos, Ordenamiento Territorial y Desarrollo Urbano del Estado de Coahuila: incorpora el concepto de 'personas con movilidad reducida' y obliga a contemplar zonas y lugares especiales de estacionamiento para personas con discapacidad en construcciones y equipamientos públicos y privados.",
    "resumen": "Ley de Asentamientos Humanos: define 'personas con movilidad reducida' y exige espacios de estacionamiento especiales para discapacitados en edificaciones públicas y privadas.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2183/20251215_178_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2025-019",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Se adiciona un segundo párrafo a la fracción I del artículo 170 del Código Municipal para el Estado de Coahuila de Zaragoza: garantizar la accesibilidad de personas con discapacidad, adultas mayores y con movilidad reducida.",
    "resumen": "Código Municipal: garantiza expresamente la accesibilidad universal para personas con discapacidad, adultas mayores y movilidad reducida en la gestión municipal.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/ini/2186/20251215_181_GAC.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2026-001",
    "fecha": "2026-01-13",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 38 ayuntamientos del Estado de Coahuila para que consideren el otorgamiento de estímulos fiscales a las empresas que implementen energías limpias en sus procesos productivos.",
    "resumen": "Incentivos municipales para la adopción de energías limpias por empresas coahuilenses.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11293/20260113_K_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2026-002",
    "fecha": "2026-01-13",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Por los cuales se envía un atento exhorto a los 38 Ayuntamientos del Estado de Coahuila de Zaragoza para que implementen acciones de tránsito y vialidad: retiro de vehículos abandonados, cumplimiento de restricciones de estacionamiento y señalización vial.",
    "resumen": "Exhorto a 38 municipios sobre tránsito y vialidad urbana: retiro de vehículos abandonados y cumplimiento de señalización y restricciones de estacionamiento.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11296/20260113_N_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  },
  {
    "id": "COAH-2026-003",
    "fecha": "2026-01-27",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada en comisión",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "Exhorto a la STPS para realizar inspecciones exhaustivas en las minas de carbón de Coahuila y transparentar un listado público de aquellas que cumplen con normas de seguridad y autorización para operar.",
    "resumen": "Seguridad laboral e inspección en minas de carbón de la región Carbonífera de Coahuila.",
    "link_documento": "https://www.congresocoahuila.gob.mx/archivos/estadistica/dic/11311/20260127_C_PA.pdf",
    "link_portal": "",
    "fuente_verificada": "Sí (PDF leído)",
    "notas": "",
    "estado": "Coahuila"
  }
];
