const DATA = [
  {
    "id": "MEX-2026-003",
    "fecha": "2026-03-18",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "Adiciona numerales 4-5 al art. 93 y fracs. X-XII al art. 97 de la Ley de Movilidad y Seguridad Vial del Estado de México y Municipios; y fracs. VI-VII al art. 7.57 Bis del Código Administrativo.",
    "resumen": "Amplía el catálogo de infracciones y sanciones de tránsito en la Ley de Movilidad y Seguridad Vial del Estado de México, adicionando nuevas fracciones a los artículos 93 (infracciones) y 97 (sanciones). Complementa con disposiciones en el Código Administrativo. Representa un endurecimiento del marco sancionatorio vial del estado.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/469-INIC-MOVILIDAD-PMC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Seguridad Pública y Tránsito | Iniciativa No. 1214 (LXII Legislatura)"
  },
  {
    "id": "MEX-2026-002",
    "fecha": "2026-03-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Adiciona fracs. VIII y VIII Bis al art. 27 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios; adiciona fracs. XVII Bis, XVII Ter, XVII Quarter al art. 2.8 del Código para la Biodiversidad.",
    "resumen": "Incorpora obligaciones de protección a fauna silvestre en la Ley de Movilidad y Seguridad Vial, añadiendo disposiciones sobre paso de animales y velocidad reducida en zonas de fauna. Vincula el código de biodiversidad con la normativa vial. Busca reducir atropellamiento de fauna en carreteras estatales.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/442-INIC-MOVILIDAD-ARLETH-PM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Protección Ambiental y Cambio Climático | Iniciativa No. 1183 (LXII Legislatura)"
  },
  {
    "id": "MEX-2026-001",
    "fecha": "2026-02-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Adiciona fracción III Bis al art. 28 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios; adiciona fracción VIII Bis al art. 31 de la Ley Orgánica Municipal.",
    "resumen": "Refuerza los derechos de ciclistas y usuarios vulnerables en el artículo 28 de la Ley de Movilidad, que regula los derechos de todos los usuarios de la vía. Obliga adicionalmente a los municipios (art. 31 de la Ley Orgánica Municipal) a garantizar infraestructura accesible. Fortalece la movilidad activa desde el marco municipal.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/428-INIC-MOVILIDAD-ARLETH-PM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Legislación y Administración Municipal | Iniciativa No. 1152 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-012",
    "fecha": "2025-12-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Autoriza al H. Ayuntamiento de Chimalhuacán a suscribir convenio de regularización de adeudos con CFE Suministrador de Servicios Básicos por adeudos históricos al mes de agosto de 2020 del ODAPAS Chimalhuacán.",
    "resumen": "Autoriza al Ayuntamiento de Chimalhuacán a reestructurar deudas históricas con CFE por el suministro eléctrico del organismo de agua municipal (ODAPAS). La iniciativa del Ejecutivo formaliza un convenio de pago a largo plazo para evitar cortes de energía al servicio de agua. Fue aprobada, lo que indica urgencia en la regularización de adeudos municipales con la empresa eléctrica estatal.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/7-INIC-CONVENIO-CHIMALHUACAN-EJEC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Comisión: Sin comisión registrada | Iniciativa No. 1105 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-011",
    "fecha": "2025-12-03",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Adiciona arts. 8 Bis y 8 Ter, reforma frac. XXXV y adiciona fracs. XXXVII-XXXVIII al art. 20 de la Ley de Movilidad y Seguridad Vial del Estado de México; adiciona art. 5.6 Quater al Código Administrativo.",
    "resumen": "Introduce nuevas disposiciones de planeación de movilidad (arts. 8 Bis y 8 Ter) y amplía el catálogo de derechos y obligaciones del artículo 20 de la Ley de Movilidad. Agrega disposiciones reglamentarias al Código Administrativo. Busca fortalecer la gobernanza del sistema de transporte estatal.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/409-INIC-MOVILIDAD-PMC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Seguridad Pública y Tránsito | Iniciativa No. 1102 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-010",
    "fecha": "2025-11-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Reforma, adiciona y deroga diversas disposiciones de la Ley de Educación del Estado de México, de la Ley para la Implementación de Energías Limpias y Renovables en los Edificios Públicos del Estado de México y Municipios, y del Código Administrativo.",
    "resumen": "Modifica la Ley para la Implementación de Energías Limpias y Renovables en Edificios Públicos, que obliga a instalar paneles solares y sistemas de eficiencia en inmuebles gubernamentales. Vincula la educación ambiental con la transición energética. Es la ley más directamente enfocada en generación renovable y eficiencia energética en edificios públicos del estado.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/397-INIC-EDUCAC-IMM-PVEM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: energía | Comisión: Protección Ambiental y Cambio Climático / Educación, Cultura, Ciencia, Tecnología e Innovación | Iniciativa No. 1077 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-009",
    "fecha": "2025-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona párrafo al inciso c de la frac. I del art. 60 E del Código Financiero del Estado de México y Municipios; adiciona art. 20 Bis a la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Reforma el Código Financiero en materia de contribuciones de transporte (art. 60 E) y añade un artículo 20 Bis a la Ley de Movilidad para establecer nuevas obligaciones de los operadores de transporte. Vincula el régimen fiscal con la regulación operativa del transporte público. Podría incidir en tarifas o requisitos de operadores.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/470-INIC-COD-FINANC-SANTILLAN-PT.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Planeación y Gasto Público / Finanzas Públicas / Comunicaciones y Transportes | Iniciativa No. 965 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-007",
    "fecha": "2025-10-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma el art. 107 y adiciona art. 107 Bis de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios; adiciona art. 193 Bis y frac. X al art. 266 del Código Penal del Estado de México.",
    "resumen": "Refuerza el régimen de responsabilidad por accidentes viales (art. 107 Ley de Movilidad) y tipifica penalmente conductas relacionadas con accidentes de tránsito en el Código Penal. Introduce el delito de homicidio o lesiones culposas por conducción imprudente. Busca disuadir la conducción temeraria mediante sanciones penales más severas.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/446-INIC-MOVILIDAD-PELAEZ-PVEM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Procuración y Administración de Justicia | Iniciativa No. 938 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-008",
    "fecha": "2025-10-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma y adiciona diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de México y Municipios, y el Código Administrativo del Estado de México.",
    "resumen": "Reforma integral a diversas disposiciones de la Ley de Movilidad y Seguridad Vial con ajustes complementarios al Código Administrativo. El título sugiere cambios en regulación de operadores y condiciones de prestación del servicio. La doble comisión (transporte y tránsito) indica alcance tanto en movilidad urbana como en seguridad vial.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/445-INIC-MOVILIDAD-YESICA-PM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Seguridad Pública y Tránsito | Iniciativa No. 937 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-006",
    "fecha": "2025-08-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma diversas disposiciones del Código para la Biodiversidad del Estado de México y de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Vincula la política de biodiversidad con la regulación vial para reducir atropellamiento de fauna silvestre en carreteras estatales. Reforma tanto el Código de Biodiversidad como la Ley de Movilidad para crear zonas de paso de fauna y límites de velocidad especiales. Se enmarca en la agenda ambiental del PVEM asociada a la movilidad.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/411-INIC-BIODIV-PMC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Protección Ambiental y Cambio Climático / Comunicaciones y Transportes | Iniciativa No. 707 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-003",
    "fecha": "2025-05-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona frac. XXX (recorriendo subsecuentes) al art. 2, reforma frac. XVII y adiciona frac. XVIII al art. 20, adiciona fracs. XXX y XXX Bis al art. 28 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Amplía las definiciones de la Ley de Movilidad (art. 2), los derechos de los usuarios (art. 20) y los derechos de los ciclistas/peatones (art. 28). La iniciativa del PRD busca robustecer el marco conceptual y de derechos en la normativa de movilidad. Nota: la comisión quedó 'precluida', lo que indica que la iniciativa caducó en comisión.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/407-INIC-MOVILIDAD-PRD.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes (Precluida) | Iniciativa No. 682 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-004",
    "fecha": "2025-05-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_INF",
    "extracto": "Adiciona y reforma diversas disposiciones al art. 7.27 del Código Administrativo del Estado de México, y de los artículos 20 y 22 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Modifica el art. 7.27 del Código Administrativo (referente a infraestructura de transporte) y los arts. 20-22 de la Ley de Movilidad (derechos, obligaciones y modalidades). El doble frente normativo sugiere ajustes tanto en la infraestructura física de transporte como en la operación del servicio.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/403-INIC-COD-ADM-KRISHNA-PAN.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes | Iniciativa No. 678 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-005",
    "fecha": "2025-05-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma el artículo 57 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios, adicionando la fracción XII Bis.",
    "resumen": "Incorpora una nueva fracción al art. 57 de la Ley de Movilidad, que regula los requisitos del servicio de transporte. La comisión de 'Grupos Vulnerables' indica que la frac. XII Bis establece obligaciones específicas de accesibilidad o trato preferente para personas con discapacidad, adultos mayores u otros grupos vulnerables en el transporte público.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/401-INIC-MOVILIDAD-SOFIA-PT.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Para la Atención de Grupos Vulnerables | Iniciativa No. 676 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-002",
    "fecha": "2025-03-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Adiciona tercer y cuarto párrafo al artículo 8.17 y reforma la fracción IV del artículo 8.18 del Código Administrativo del Estado de México.",
    "resumen": "Modifica los arts. 8.17 y 8.18 del Código Administrativo, correspondientes al Libro 8 de Transporte. Estos artículos regulan el control de tránsito y las obligaciones de las autoridades de vialidad. La comisión de Seguridad Pública y Tránsito confirma el enfoque en regulación de tráfico. Podría incluir nuevas facultades de control de velocidad o alcoholimetría.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/322-INIC-COD-ADM-PELAEZ-PVEM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: tránsito | Comisión: Seguridad Pública y Tránsito | Iniciativa No. 579 (LXII Legislatura)"
  },
  {
    "id": "MEX-2025-001",
    "fecha": "2025-02-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona seis párrafos al artículo 78 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Amplia el artículo 78 de la Ley de Movilidad, que regula el régimen de concesiones del transporte público estatal, añadiendo seis nuevos párrafos. El nombre del archivo ('CONCES') confirma que trata sobre concesiones. Busca fortalecer las condiciones y requisitos para la operación concesionada del transporte público en el Estado de México.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/288-INIC-CONCES-PMC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes | Iniciativa No. 542 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-010",
    "fecha": "2024-12-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona y reforma diversas disposiciones del Código Financiero del Estado de México y Municipios y de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Reforma paralela al Código Financiero y la Ley de Movilidad para ajustar el esquema fiscal del transporte público estatal. Puede incluir cambios en derechos de tránsito, tenencia vehicular o financiamiento del transporte. La doble comisión (finanzas y transportes) indica un enfoque en sostenibilidad financiera del sistema de movilidad.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/285-INIC-COD-FINANC-KRISHNA-PAN.docx",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Planeación y Gasto Público / Finanzas Públicas / Comunicaciones y Transportes | Iniciativa No. 464 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-009",
    "fecha": "2024-12-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona, reforma y deroga diversas disposiciones del Código Financiero del Estado de México y Municipios, del Código Administrativo del Estado de México, así como de la Ley de Movilidad y Seguridad Vial del Estado de México.",
    "resumen": "Reforma integral de tres cuerpos normativos (Código Financiero, Código Administrativo y Ley de Movilidad) para ajustar el marco fiscal y operativo del transporte público. El PRI propone modificar y derogar disposiciones en la Ley de Movilidad, lo que podría implicar simplificación regulatoria o cambios en el modelo de concesiones.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/273-COD-FINANC-PRI.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Planeación y Gasto Público / Finanzas Públicas / Comunicaciones y Transportes | Iniciativa No. 451 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-008",
    "fecha": "2024-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_INF",
    "extracto": "Adiciona un Título Sexto a la Ley de Responsabilidad Patrimonial para el Estado de México y Municipios.",
    "resumen": "Incorpora un nuevo Título Sexto a la Ley de Responsabilidad Patrimonial, que regularía la responsabilidad del Estado por daños causados en infraestructura vial (accidentes por deficiencias en carreteras, señalización deficiente, etc.). La comisión de Comunicaciones y Transportes confirma el enfoque vial. Busca proteger a ciudadanos frente a daños por omisión gubernamental en vías públicas.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/268-INIC-RESPONSABIL-PRI.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: transporte | Comisión: Procuración y Administración de Justicia / Comunicaciones y Transportes | Iniciativa No. 439 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-007",
    "fecha": "2024-11-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Autoriza al H. Ayuntamiento de Nezahualcóyotl a suscribir convenios de regularización de adeudos con CFE Suministrador de Servicios Básicos por adeudos históricos existentes al 31 de diciembre de 2022 del municipio y del ODAPAS Nezahualcóyotl.",
    "resumen": "Autoriza al Ayuntamiento de Nezahualcóyotl a reestructurar deudas históricas con CFE por el suministro eléctrico municipal y del organismo de agua local (ODAPAS). El Congreso aprobó esta autorización del Ejecutivo para evitar cortes de energía al servicio de agua. Refleja la tensión fiscal entre municipios y CFE en el Estado de México, con dos adeudos acumulados hasta finales de 2022.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/227-INIC-ADEUDOS-NEZA-EJEC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Comisión: Finanzas Públicas / Planeación y Gasto Público / Recursos Hidráulicos | Iniciativa No. 361 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-006",
    "fecha": "2024-11-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Adiciona fracción LXXV Bis al artículo 2 y fracción XXXVII al artículo 20 de la Ley de Movilidad y Seguridad Vial del Estado de México y sus Municipios.",
    "resumen": "Añade una nueva definición (frac. LXXV Bis) y una obligación específica (frac. XXXVII al art. 20) en la Ley de Movilidad relacionada con la protección de fauna silvestre en vías. El nombre del archivo ('FAUNA') confirma el enfoque ambiental-vial. Busca reconocer el riesgo de fauna en carreteras como un tema de movilidad activa y seguridad vial.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/225-INIC-MOVILIDAD-FAUNA-PMC.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Protección Ambiental y Cambio Climático | Iniciativa No. 358 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-001",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma frac. XVIII del art. 2 y agrega frac. XII Bis al art. 26 de la Ley de Movilidad del Estado de México; crea Capítulo Cuarto 'De los Vehículos Compartidos' del Título Segundo, Libro Séptimo del Código Administrativo.",
    "resumen": "Crea el marco normativo para los vehículos compartidos (ride-hailing y plataformas digitales como Uber/DiDi) en el Estado de México, añadiendo un capítulo específico al Código Administrativo. Actualiza las definiciones de la Ley de Movilidad para incorporar estas modalidades. La iniciativa del PRD buscaba regular las plataformas de transporte digital, aunque expiró en comisión.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/288-INIC-MOVILIDAD-PRD.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes (Precluida) | Iniciativa No. 294 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-002",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Modifica el Título Cuarto 'Del Registro Estatal de Transporte Público' del Código Administrativo del Estado de México.",
    "resumen": "Reforma el título del Código Administrativo dedicado al Registro Estatal de Transporte Público, que contiene las reglas de padrón y control de unidades de transporte. Busca modernizar o simplificar el sistema de registro. Iniciativa del PRD que caducó en comisión sin dictaminarse.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/218-INIC-COD-ADM-PRD.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: transporte | Comisión: Comunicaciones y Transportes (Precluida) | Iniciativa No. 224 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-003",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona un párrafo segundo al artículo 52 de la Ley de Movilidad del Estado de México.",
    "resumen": "Añade un segundo párrafo al art. 52 de la Ley de Movilidad, que regula el otorgamiento y condiciones de las concesiones de transporte. La adición podría establecer nuevas condiciones o limitaciones a las concesiones. Iniciativa PRD que no fue dictaminada (precluida).",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/215-INIC-MOVILIDAD-PRD.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes (Precluida) | Iniciativa No. 221 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-004",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Reforma art. 1 párrafo tercero, frac. XXIII y adiciona frac. XXVII del art. 9, adiciona fracs. XVIII-XIX al art. 12, reforma art. 26 adicionando fracs. XV-XVII, y adiciona fracs. X-XI al art. 27 de la Ley de Movilidad del Estado de México.",
    "resumen": "Reforma amplia de la Ley de Movilidad del Estado de México que actualiza principios (art. 1), competencias (art. 9), modos de transporte (art. 12), prestación del servicio (art. 26) y derechos de ciclistas/peatones (art. 27). El PVEM presentó una reforma estructural para alinear la ley con tendencias de movilidad sostenible. Es una de las iniciativas más amplias presentadas al inicio de la legislatura.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/164-INIC-MOVILIDAD-PVEM.pdf",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes | Iniciativa No. 170 (LXII Legislatura)"
  },
  {
    "id": "MEX-2024-005",
    "fecha": "2024-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Reforma párrafo tercero del art. 1, frac. XXIII y adiciona frac. XXVII al art. 9, adiciona fracs. XVII-XVIII al art. 12, reforma art. 26 adicionando fracs. XV-XVII, y adiciona fracs. X-XI al art. 27 de la Ley de Movilidad del Estado de México.",
    "resumen": "Segunda versión del PVEM de la reforma a la Ley de Movilidad (ver No. 170), presentada en la misma fecha con variaciones menores y la adición de la Comisión de Desarrollo Urbano. Ambas fueron presentadas el mismo día como parte del paquete legislativo de apertura de la LXII Legislatura. Abarca los mismos artículos con diferencias puntuales en fracciones adicionadas.",
    "link_documento": "https://legislacion.congresoedomex.gob.mx/storage/documentos/asuntos/iniciativas/160-INIC-MOVILIDAD-PVEM.docx",
    "link_portal": "https://legislacion.congresoedomex.gob.mx/asuntosparlamentarios/iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En estudio | Término búsqueda: movilidad | Comisión: Comunicaciones y Transportes / Desarrollo Urbano | Iniciativa No. 166 (LXII Legislatura)"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};