const DATA = [
  {
    "id": "DUR-2026-001",
    "fecha": "2026-01-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo de la Comisión Permanente en el que el Dip. José Luis Rocha Medina emitió un exhorto a CAPUFE para que considere las tarifas de peaje de las autopistas federales que atraviesan el Estado de Durango.",
    "resumen": "En la Comisión Permanente del Congreso de Durango (período diciembre 2025 - febrero 2026), el Dip. José Luis Rocha Medina presentó un Punto de Acuerdo para exhortar a CAPUFE a revisar las tarifas de peaje en autopistas federales de Durango, en el contexto del aumento de tarifas aplicado en enero 2025 de entre 5 y 9 por ciento.",
    "link_documento": "",
    "link_portal": "https://congresodurango.gob.mx",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (Comisión Permanente) | Término búsqueda: vialidad | Presentó: Dip. José Luis Rocha Medina. Fecha exacta no determinada; la Comisión Permanente opera del 16 dic 2025 al 14 feb 2026. Se usó 2026-01-01 como fecha aproximada provisional."
  },
  {
    "id": "DUR-2025-006",
    "fecha": "2025-12-06",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma a la Ley de Transportes del Estado para regular el servicio especializado en la modalidad de ejecutivo privado operado a través de plataformas tecnológicas o aplicaciones móviles; establece obligación de registro ante la Subsecretaría de Transportes con refrendo anual, exceptuando a quienes ya cuentan con concesión del servicio público.",
    "resumen": "La LXX Legislatura aprobó el 6 de diciembre de 2025 reformas a la Ley de Transportes para regular los servicios de transporte privado vía plataformas digitales tipo Uber en Durango. Los operadores deberán inscribirse y renovar anualmente su registro ante la Subsecretaría de Transportes. Dictaminó la Comisión de Tránsito y Transportes.",
    "link_documento": "https://congresodurango.gob.mx/Archivos/legislacion/LEY%20DE%20TRANSPORTES.pdf",
    "link_portal": "https://congresodurango.gob.mx/2025/12/08/regula-congreso-transporte-privado-de-plataformas-digitales/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | Publicado en sitio del Congreso: 8 diciembre 2025. Dictaminó: Comisión de Tránsito y Transportes."
  },
  {
    "id": "DUR-2025-003",
    "fecha": "2025-10-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Nueva Ley de Tránsito para los Municipios del Estado de Durango que actualiza el marco normativo municipal en materia de tránsito, establece obligaciones de organizar y operar el servicio de tránsito, normas de circulación, señalética y sanciones.",
    "resumen": "La LXX Legislatura aprobó el 7 de octubre de 2025 una nueva Ley de Tránsito para los Municipios del Estado de Durango, reemplazando el marco normativo anterior. La nueva ley unifica criterios de tránsito, establece sanciones actualizadas y obliga a cada municipio a organizar y operar su propia área de tránsito. Publicada como Decreto 197 en el P.O. No. 85 el 23 de octubre de 2025.",
    "link_documento": "https://congresodurango.gob.mx/Archivos/legislacion/LEY%20DE%20TRANSITO.pdf",
    "link_portal": "https://congresodurango.gob.mx",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada (Decreto 197, P.O. No. 85, 23 octubre 2025) | Término búsqueda: tránsito | Ley vigente publicada en portal del Congreso."
  },
  {
    "id": "DUR-2025-002",
    "fecha": "2025-10-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma al artículo 32 de la Ley de Movilidad y Seguridad Vial para el Estado de Durango para garantizar el derecho a la movilidad en zonas rurales, reconociendo las condiciones específicas de acceso y desplazamiento de las comunidades rurales.",
    "resumen": "La LXX Legislatura aprobó reformar el artículo 32 de la Ley de Movilidad y Seguridad Vial para asegurar el derecho a la movilidad en comunidades rurales de Durango. Publicada como Decreto 198 en el Periódico Oficial No. 85 el 23 de octubre de 2025.",
    "link_documento": "",
    "link_portal": "https://congresodurango.gob.mx/Archivos/LXX/GACETAS/ORDINARIO/GACETA137.pdf",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada (Decreto 198, P.O. No. 85, 23 octubre 2025) | Término búsqueda: movilidad | Gaceta No. 137 (7 octubre 2025)."
  },
  {
    "id": "DUR-2025-004",
    "fecha": "2025-08-07",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta a la Comisión Federal de Electricidad (CFE) a corregir con urgencia las fallas técnicas que provocaron múltiples apagones en distintos municipios de Durango, y a informar sobre las causas de las interrupciones del servicio eléctrico que afectaron a miles de familias, comercios e industrias.",
    "resumen": "La LXX Legislatura aprobó por unanimidad el 7 de agosto de 2025 un exhorto a la CFE para atender la ola de apagones que afectó severamente a Durango durante el verano de 2025, incluyendo 16 apagones registrados sólo en la capital.",
    "link_documento": "",
    "link_portal": "https://congresodurango.gob.mx/2025/08/07/pide-congreso-a-cfe-solucionar-apagones-y-garantizar-suministro-de-la-luz/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada por unanimidad | Término búsqueda: energía | Presentó: Dip. Ernesto Alanís Herrera (PRI). Apoyó: Dip. Alejandro Mata Valadez (Morena)."
  },
  {
    "id": "DUR-2025-005",
    "fecha": "2025-07-02",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo de la Comisión Permanente que exhorta a la SICT a fortalecer las acciones de mantenimiento, rehabilitación y modernización de la red vial, y a continuar la segunda etapa del programa Bachetón 2025 con atención especial a los 2,099 km de red carretera federal libre de peaje en Durango.",
    "resumen": "La Comisión Permanente del Congreso de Durango exhortó por unanimidad a la SICT a priorizar el mantenimiento de la red vial federal en el estado, solicitando la segunda etapa del programa Bachetón 2025.",
    "link_documento": "",
    "link_portal": "https://congresodurango.gob.mx",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada por unanimidad (Comisión Permanente) | Término búsqueda: vialidad | Presentó: Dip. Sughey Torres Rodríguez. Fecha aproximada: 2 julio 2025."
  },
  {
    "id": "DUR-2025-001",
    "fecha": "2025-05-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma al artículo 32 de la Ley de Movilidad y Seguridad Vial para el Estado de Durango en materia de derechos y condiciones laborales de mujeres operadoras en el transporte público estatal.",
    "resumen": "La LXX Legislatura aprobó el 27 de mayo de 2025 una reforma al artículo 32 de la Ley de Movilidad y Seguridad Vial para garantizar condiciones igualitarias para mujeres operadoras en el transporte público. Publicada como Decreto 177 en el Periódico Oficial No. 54 el 6 de julio de 2025.",
    "link_documento": "",
    "link_portal": "https://congresodurango.gob.mx",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada (Decreto 177, P.O. No. 54, 6 julio 2025) | Término búsqueda: movilidad | Dictaminó Comisión de Tránsito y Transportes."
  },
  {
    "id": "DUR-2024-001",
    "fecha": "2024-04-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Reforma artículo 29 de la Ley de Cambio Climático del Estado de Durango para privilegiar la sustitución de combustibles fósiles y el desarrollo de sistemas de transporte urbano y suburbano sustentable de alta eficiencia, así como para promover la movilidad activa o no motorizada y la electromovilidad.",
    "resumen": "La LXX Legislatura aprobó una reforma a la Ley de Cambio Climático que impulsa el transporte público de alta eficiencia, la sustitución del parque vehicular por unidades eléctricas e híbridas y la movilidad activa. Aprobada como Decreto 207 de la LXX.",
    "link_documento": "https://congresodurango.gob.mx/Archivos/LXX/DECRETOS/DEC207.pdf",
    "link_portal": "https://congresodurango.gob.mx",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Decreto publicado (LXX) | Término búsqueda: energía / movilidad | Iniciativa presentada 24 abril 2024 en LXIX; aprobada como Decreto 207 de LXX."
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
