const DATA = [
  {
    "id": "NL-2026-001",
    "fecha": "2026-03-02",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA A LA LEY DE ASENTAMIENTOS HUMANOS, ORDENAMIENTO TERRITORIAL Y DESARROLLO URBANO PARA EL ESTADO DE NUEVO LEON, Y A LA LEY PARA LA PROTECCIÓN DE LOS DERECHOS DE LAS PERSONAS CON DISCAPACIDAD,EN MATERIA DE ACCESIBILIDAD UNIVERSAL.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21142.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PRI"
  },
  {
    "id": "NL-2025-001",
    "fecha": "2025-09-17",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 8 Y 68 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A ESTABLECER EL CONCEPTO DE ACCIDENTE MENOR. SE TURNA CON CARÁCTER URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20272.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PRI"
  },
  {
    "id": "NL-2025-002",
    "fecha": "2025-08-13",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN AL ARTÍCULO 14 DE LA LEY DE FOMENTO A LA MICRO, PEQUEÑA Y MEDIANA EMPRESA PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE APOYO ECONÓMICO A LAS PYMES PARA QUE DENTRO DE SUS PROCESOS PRODUCTIVOS INTRODUZCAN, ADAPTE, SUSTITUYAN O EMPLEEN ENERGÍAS LIMPIAS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20183.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PRI"
  },
  {
    "id": "NL-2025-003",
    "fecha": "2025-03-26",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LOS ARTÍCULOS 71 Y 75 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE SERVICIOS A PERSONAS CON DISCAPACIDAD EN EL TRANSPORTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/faaf5a800240a76376e794fc3ebc591ace2d6b9d.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PRI"
  },
  {
    "id": "NL-2025-004",
    "fecha": "2025-01-15",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA POR ADICIÓN DE UN CAPÍTULO SEGUNDO BIS DENOMINADO “SUBSIDIO AL USO DEL TRANSPORTE PÚBLICO” EL CUAL CONTIENE LOS ARTÍCULOS 86 BIS, 86 BIS 1, 86 BIS 2 Y 86 BIS 3 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN. SE TURNA CON CARÁCTER DE URGENTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19323.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PRI"
  },
  {
    "id": "NL-2026-002",
    "fecha": "2026-02-24",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA AL ARTICULO 191; SE ADICIONAN LOS ARTICULOS 191 BIS Y 191 BIS 1 A ALA LEY DE MOVILIDAD Y ACCESIBILIDAD DEL ESTADO DE NUEVO LEON, EN MATERIA DE INSPECCIONES AL TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21122.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2026-003",
    "fecha": "2026-01-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 15 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, CON EL FIN DE OTORGAR UNA FACULTAD EXPRESA A LOS MUNICIPIOS DEL ESTADO DE NUEVO LEÓN, PARA CONSTITUIR EMPRESAS PÚBLICAS MUNICIPALES O PARTICIPAR EN ESQUEMAS DE ASOCIACIÓN PÚBLICO-PRIVADA, DESTINADAS A LA OPERACIÓN DEL TRANSPORTE PÚBLICO D",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21032.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-005",
    "fecha": "2025-12-15",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA POR LA QUE SE REFORMAN DIVERSAS DISPOSICIONES DE LA LEY DE EDUCACIÓN DEL ESTADO; LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON Y A LA LEY DE FOMENTO A LA INVERSIÓN Y AL EMPLEO PARA EL ESTADO DE NUEVO LEÓN EN MATERIA DE TRANSPORTE ESCOLAR GRATUITO PARA ESCUELAS PÚBLICAS DE EDUCACIÓN BÁSICA",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20894.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-006",
    "fecha": "2025-12-10",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE TARIFAS PREFERENCIALES DEL SISTEMA DE TRANSPORTE PÚBLICO PARA VOLUNTARIOS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20872.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-007",
    "fecha": "2025-11-18",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE REFORMA A DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE CAPACITACIÓN CONTINUA DE OPERADORES DE TRANSPORTE PÚBLICO",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20712.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-008",
    "fecha": "2025-11-10",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA A DIVERSOS ARTICULOS A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON., EN MATERIADE VEHICULOS NO MOTORIZADOS Y MICROMOVILIDAD.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20537.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-009",
    "fecha": "2025-10-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 8 Y POR ADICIÓN DE UN ARTÍCULO 5 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN AL DERECHOS A LA MOVILIDAD DE LOS VEHÍCULOS FORÁNEOS, A TRAVÉS DE LA EXPEDICIÓN DEL PERMISO TURÍSTICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20376.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-010",
    "fecha": "2025-09-22",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 214 Y POR ADICIÓN DE LOS ARTÍCULOS 116 BIS Y 173 BIS A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE RESPONSABILIDAD LEGAL PARA LAS EMPRESAS QUE PRESTEN EL SERVICIO DE TRANSPORTE DE PERSONAL PRIVADO O TURÍSTICO Y SE VEAN INVOLUCRADOS EN ACCIDENTES AUTOMOVILÍSTICOS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20289.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-011",
    "fecha": "2025-09-09",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA A LAS FRACCIONES II Y XIV DEL ARTICULO 23, LAS FRACCIONES XVII Y XIX DEL ARTICULO 27 Y LA FRACCION XIII DEL ARTICULO 30; ADICION LA SECCION PRIMERA BIS DENOMINADA \"CONSEJO DE TRANSPORTE DE CARGA\" CON SUS ARTICULOS 98 BIS AL 98 BIS 16 AL CAPITULO SEGUNDO SERVICIO DE TRANSPORTE DEL TITULO QUINTO DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20265.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-012",
    "fecha": "2025-06-04",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA POR ADICIÓN DE UN ARTÍCULO 70 BIS AL CAPÍTULO SEGUNDO DEL TÍTULO CUARTO DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19981.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-013",
    "fecha": "2025-04-30",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN DE DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE COORDINACIÓN Y CONCURRENCIA.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19852.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-014",
    "fecha": "2025-04-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 33 DE LA LEY DE GOBIERNO MUNICIPAL DEL ESTADO DE NUEVO LEÓN, EN MATERIA DE ENERGÍAS RENOVABLES.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19805.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-015",
    "fecha": "2025-03-31",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA POR ADICIÓN DE UN ARTÍCULO 2 BIS A LA LEY DE SEÑALAMIENTOS VIALES PARA EL ESTADO DE NUEVO LEÓN, RELATIVO AL MANTENIMIENTO DE LOS SEÑALAMIENTOS DE TRÁNSITO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19738.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-016",
    "fecha": "2025-03-19",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA POR ADICIÓN AL ARTÍCULO 68 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19683_compressed.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-017",
    "fecha": "2025-03-10",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A DIVERSAS DISPOSICIONES DE LA LEY DE ACCESO DE LAS MUJERES A UNA VIDA LIBRE DE VIOLENCIA, A FIN DE ESTABLECER EL PROGRAMA ESTATAL DE MUJERES SEGURAS EN EL TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19573.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2025-018",
    "fecha": "2025-02-17",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LOS ARTÍCULOS 8 Y 70 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A ESTABLECER UNA TARIFA ÚNICA EN EL TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19417.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2024-001",
    "fecha": "2024-12-03",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 12 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19200.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2024-002",
    "fecha": "2024-11-25",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 133 Y 133 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A LA INSTALACIÓN OBLIGATORIA DE CASETAS TECHADAS Y CLIMATIZADAS EN LAS PARADAS DE AUTOBUSES, PARA SEGURIDAD Y PROTECCIÓN DE LOS USUARIOS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19129.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2024-003",
    "fecha": "2024-11-25",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 12 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19127.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2024-004",
    "fecha": "2024-11-13",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA POR ADICIÓN DE UN CAPÍTULO PRIMERO BIS DENOMINADO “TARIFAS SOCIALES AL USO DEL TRANSPORTE PÚBLICO”, EL CUAL CONTIENE LOS ARTÍCULOS 183 BIS, 183 BIS 1 Y 183 BIS 2 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN. SE TURNA CON CARÁCTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP18959.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2024-005",
    "fecha": "2024-11-11",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE REFORMA A LOS ARTÍCULOS 16 Y 109 DE LA LEY DE EDUCACIÓN DEL ESTADO Y AL ARTÍCULO 23 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP18937.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PAN"
  },
  {
    "id": "NL-2026-004",
    "fecha": "2026-03-24",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA CON PROYECTO DE REFORMA LA FRACCION V DEL ARTICULO 149 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21241.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2026-005",
    "fecha": "2026-03-17",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 74 Y POR ADICIÓN DE UN ARTÍCULO 53 BIS DE LA LEY DE CAMINOS, PUENTES Y AUTOTRANSPORTE FEDERAL, EN MATERIA DE LINEAMIENTOS PARA LA PROTECCIÓN DE MENORES DE EDAD EN EL SERVICIO DE TRANSPORTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21202.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2026-006",
    "fecha": "2026-02-03",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "PRESENTA \tINICIATIVA DE REFORMA A DISTINTAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE GESTIÓN Y PRIORIZACIÓN DE TRANSPORTE PÚBLICO E INFRAESTRUCTURA PEATONAL.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21041.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2026-007",
    "fecha": "2026-01-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 66 DEL CÓDIGO PENAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A PRECISAR LA DEFINICIÓN DE CULPA GRAVE EN EL CONTEXTO DE ACCIDENTES DE TRÁNSITO QUE CAUSAN LESIONES GRAVES O MUERTE, INCLUYENDO LAS CONDUCTAS DE ABANDONO, OMISIÓN DE AUXILIO Y FALTA DE SOLICITUD DE AYUDA.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21021.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2026-008",
    "fecha": "2026-01-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 112 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE INVASIÓN, OBSTRUCCIÓN O CIRCULACIÓN EN ZONAS DESTINADAS A LA CIRCULACIÓN DE MOTOCICLETAS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21020.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-019",
    "fecha": "2025-10-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA Y ADICIÓN DEL ARTÍCULO 12 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A QUE LA SECRETARÍA DE MOVILIDAD, CELEBRE CONVENIOS CON LOS MUNICIPIOS Y SECTORES PÚBLICOS Y PRIVADOS, A FIN DE QUE PROMUEVA E INSTALEN CENICEROS DE PIE CON CONTENEDORES DE BASURA CERCA DE LAS ÁREAS Y LUGARES DESTI",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20467.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-020",
    "fecha": "2025-10-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA Y ADICIÓN DEL ARTÍCULO 133 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A INSTALAR CENICEROS DE PIE PARA EL DESECHO DE LAS COLILLAS DE CIGARRO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20466.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-021",
    "fecha": "2025-10-21",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 4 BIS 4 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN EN MATERIA DE DERECHO DE LAS PERSONAS USUARIAS DEL TRANSPORTE PÚBLICO, A ESPERAR EN CONDICIONES DIGNAS, SEGURAS Y PROTEGIDAS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20435.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-022",
    "fecha": "2025-10-20",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 15 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE CIRCULACIÓN DE VEHÍCULOS DE CARGA PESADA",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20422.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-023",
    "fecha": "2025-10-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA CON PROYECTO DE DECRETO POR EL CUAL SE REFORMA LA FRACCIÓN IV DEL ARTÍCULO 112 BIS, DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL DEL ESTADO DE NUEVO LEÓN, EN MATERIA DE PROHIBICIÓN DE LA CIRCULACIÓN DE MOTOCICLETAS QUE NO CUENTEN CON UN SISTEMA DE ESCAPES QUE FUNCIONEN COMO SILENCIADORES.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/0961e2ece7205eb58c370c2256ea7609664ee9f8.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-024",
    "fecha": "2025-10-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA POR EL QUE SE ADICIONA UN SEGUNDO Y TERCER PÁRRAFO AL ARTÍCULO 18 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE CONTRAFLUJOS VEHICULARES. SE TURNA CON CARÁCTER URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/32da81940bb67f7a11cfd77fe485323a81c1f0e0.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-025",
    "fecha": "2025-09-02",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA CON PROYECTO DE DECRETO POR EL CUAL SE REFORMAN DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE TARIFAS PREFERENCIALES PARA GRUPOS VULNERABLES",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20242.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-026",
    "fecha": "2025-08-13",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 68 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE ESTABLECER POR UN PERIODO DE 12 MESES, UNA SEÑAL DISTINTIVA CON LA LETRA “A” DE APRENDIZ A AQUELLOS CONDUCTORES QUE OBTENGAN POR PRIMERA VEZ SU LICENCIA DE CONDUCIR.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20186.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-027",
    "fecha": "2025-06-25",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA PARA ADICIONAR LOS PARRAFOS SEGUNDO, TERCERO Y CUARTO AL ARTICULO 68 DE LA LEY DE MOVILIDADA SOSTEIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20058.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-028",
    "fecha": "2025-06-11",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE USO RACIONAL DE VIALIDADES PARA EL TRASLADO DEL ALUMNADO A PLANTELES EDUCATIVOS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20004.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-029",
    "fecha": "2025-06-11",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN A LOS ARTÍCULOS 8, 14, 30, 39, 49, 70 Y 144 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE PROHIBICIÓN DE INCREMENTOS MULTIANUALES Y DESLIZAMIENTOS MENSUALES A LAS TARIFAS DE TRANSPORTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20000.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-030",
    "fecha": "2025-06-04",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 68 BIS I DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19984.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-031",
    "fecha": "2025-05-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 65 Y POR ADICIÓN DE UN ARTÍCULO 60 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE SEGURIDAD CICLISTA Y HOMOLOGACIÓN DE REGLAMENTOS MUNICIPALES.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19802.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-032",
    "fecha": "2025-05-27",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 8, 12 Y POR ADICIÓN DE UN ARTÍCULO 186 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19898.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-033",
    "fecha": "2025-05-27",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 120 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19886.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-034",
    "fecha": "2025-04-28",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, A FIN DE QUE LAS PLATAFORMAS CON SERVICIO DE TRANSPORTE INDIVIDUAL DE ALQUILER PRIVADO (SETIAP) NO REGISTREN VEHÍCULOS QUE EXCEDAN LA ANTIGÜEDAD ESTABLECIDA EN LA LEY.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19797.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-035",
    "fecha": "2025-03-31",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 15 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN RELATIVO A LOS CAJONES PARA PERSONAS CON DISCAPACIDAD.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19722.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-036",
    "fecha": "2025-03-26",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 27 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DEL PLAZO DE LA DESIGNACIÓN DE LOS REPRESENTANTES DE COLECTIVOS, ONG’S Y COLEGIOS DE ARQUITECTOS E INGENIEROS ANTE LA JUNTA DE GOBIERNO DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19718.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-037",
    "fecha": "2025-03-26",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 27 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE REPRESENTACIÓN SOCIAL ANTE LA JUNTA DE GOBIERNO DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19717.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-038",
    "fecha": "2025-03-04",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19538.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-039",
    "fecha": "2025-02-24",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19450.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-040",
    "fecha": "2025-01-08",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE PROHIBIR NUEVOS FRACCIONAMIENTOS SIN FACTIBILIDAD EN SERVICIOS DE TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19298.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2024-006",
    "fecha": "2024-12-20",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A TRASMITIR EN VIVO DE LAS SESIONES Y REUNIONES DE TRABAJO DE LAS COMISIONES DEL CONSEJO CONSULTIVO DE MOVILIDAD. SE TURNO CON CARÁCTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19248.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2024-007",
    "fecha": "2024-12-09",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA POR LA QUE SE EXPIDE LA DENOMINADA LEY ALEJANDRA ROMÁN, LEY DE PROTECCIÓN AL CICLISTA Y FOMENTO AL USO DE LA BICICLETA EN EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19218.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2024-008",
    "fecha": "2024-10-14",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA Y ADICION DE DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON, EN MATERIA DE BENEFICIOS A LAS PERSONAS OPERADORAS DE LOS SERVICIOS DE TRANSPORTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP18826.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2024-009",
    "fecha": "2024-09-18",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A DIVERSOS ARTÍCULOS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP18742.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MC"
  },
  {
    "id": "NL-2025-041",
    "fecha": "2025-10-27",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 8, 70, 70 BIS 1 Y 71 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20446.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-042",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A DIVERSAS DISPOSICIONES DE LA LEY DE EDUCACIÓN DEL ESTADO DE NUEVO LEÓN Y A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE TRANSPORTE ESCOLAR. SE TURNA CON CARÁCTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20154.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-043",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA POR LA QUE SE REFORMAN DIVERSOS ARTÍCULOS DE LA LEY DE FOMENTO A LA INVERSIÓN Y AL EMPLEO DEL ESTADO DE NUEVO LEÓN EN MATERIA DE APOYO PARA QUE LAS EMPRESAS BRINDEN APOYO EN TRANSPORTE PÚBLICO A SUS EMPLEADOS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20102.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-044",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 12 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A QUE LAS PERSONAS USUARIAS DEL TRANSPORTE PÚBLICO, PUEDAN CANJEAR MATERIALES RECICLABLES POR DESCUENTOS O ACCESOS AL TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20076.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-045",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 70 BIS 2 DE LA LEY DE MOVILIDAD SOSTENIBLE, ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN Y AL ARTÍCULO 8° DE LA LEY QUE REGULA LA EXPEDICIÓN DE LICENCIAS PARA CONDUCIR DEL ESTADO, EN MATERIA DE CAPACITACIÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20072.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-046",
    "fecha": "2025-06-18",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 8 Y POR ADICIÓN DE LOS ARTÍCULOS 134 BIS Y 134 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE, ACCESIBILIDAD Y SEGURIDAD VIAL DEL ESTADO DE NUEVO LEÓN, EN MATERIA DE MODELO DE CALLES COMPLETAS. SE TURNA CON CARÁCTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20037.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-047",
    "fecha": "2025-06-18",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA POR ADICIÓN DE LOS ARTÍCULOS 122 BIS Y 122 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN; ASÍ COMO INICIATIVA DE REFORMA AL ARTÍCULO 51 DE LA LEY DE JUSTICIA CIVIL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A VEHÍCULOS DE MICROMOVILIDAD ELÉCTRICA. SE TURNA CON CARÁCTER URGENTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20032.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-048",
    "fecha": "2025-05-27",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN A DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19938.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-049",
    "fecha": "2025-04-08",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN DE DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN. SE TURNA CON CARÁCTER URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19786.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-050",
    "fecha": "2025-03-31",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 8, 133 Y 144 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL DEL ESTADO DE NUEVO LEÓN, RELATIVA A LA TARJETA ÚNICA DE MOVILIDAD.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19729_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-051",
    "fecha": "2025-02-24",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 10 Y 26 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN. SE TURNA CON CARÁCTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19462.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-052",
    "fecha": "2025-02-05",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA Y ADICION DE DIVERSAS DISPOSICIONES DE LA LEY DE MOVLIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON. SE TURNA CON CARÁCTER URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19374.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-053",
    "fecha": "2025-02-04",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 13 DE LA LEY DE JUVENTUD PARA EL ESTADO DE NUEVO LEÓN; AL CAPÍTULO CUARTO DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN Y AL ARTÍCULO 33 DE LA LEY DE GOBIERNO MUNICIPAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19356.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-054",
    "fecha": "2025-01-15",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 50 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19322.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: MORENA"
  },
  {
    "id": "NL-2025-055",
    "fecha": "2025-02-26",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19480.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: PVEM"
  },
  {
    "id": "NL-2025-056",
    "fecha": "2025-11-04",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 81 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN RELACIÓN A INCENTIVAR EL OFICIO DE OPERADOR DE TAXI",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20515.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Independientes"
  },
  {
    "id": "NL-2025-057",
    "fecha": "2025-10-13",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE SIMPLIFICACIÓN DE LAS CONDICIONES Y LAS GARANTÍAS PARA EL ACCESO A LAS TARIFAS PREFERENCIALES DEL TRANSPORTE PÚBLICO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20396.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Independientes"
  },
  {
    "id": "NL-2025-058",
    "fecha": "2025-09-22",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMAS Y ADICIONES DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20302.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Independientes"
  },
  {
    "id": "NL-2025-059",
    "fecha": "2025-09-08",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PRESENTA INICIATIVA DE REFORMA DEL ARTÍCULO 27 EN SUS FRACCIONES II, IV BIS, XI Y XVII, SU PRIMER PARRAFO Y SE LE ADICIONA UNA FRACCIÓN XIX; Y EL ARTICULO 50 EN SU FRACCIÓN IV SE ADICIONA UN INCISCO W) DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE MEJORAS EN LA REPRESENTACIÓN CIUDADANA EN LA JUNTA DE GOBIERNO DEL INSTITUTO DE MOVIL",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20262.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Independientes"
  },
  {
    "id": "NL-2026-009",
    "fecha": "2026-03-04",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LOS ARTÍCULOS 142 Y 144 DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE COBRO DEL SERVICIO DE TRANSPORTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2026-EXP21154_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2026-010",
    "fecha": "2026-01-14",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA POR ADICIÓN DE UN CAPÍTULO X DENOMINADO “DEL USO DE SISTEMAS AUTOMATIZADOS DE CONDUCCIÓN” DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20975_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-060",
    "fecha": "2025-11-10",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN MATERIA DE TARIFAS PREFERENCIALES DE POR LO MENOS CINCUENTA POR CIENTO DEL MONTO VIGENTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20530_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-061",
    "fecha": "2025-11-10",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LOS ARTÍCULOS 23 Y 30 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN EN MATERIA DE TARIFAS DEL SISTEMA COLECTIVO METRORREY",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20529_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-062",
    "fecha": "2025-11-03",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A DIVERSOS ARTÍCULOS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL DEL ESTADO DE NUEVO LEÓN, EN MATERIA DE ESTABLECER QUE TODO VEHÍCULO EN CIRCULACIÓN CUENTE CON SEGURO VIGENTE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20502_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-063",
    "fecha": "2025-04-08",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA Y ADICIÓN DE DIVERSAS DISPOSICIONES DEL ARTÍCULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19788_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-064",
    "fecha": "2025-03-25",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, PARA ADICIÓN LA LEY DE FOMENTO, APOYO Y PARTICIPACIÓN DE STARTUPS TECNOLÓGICAS EN LA MODALIDAD ESTATAL”.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19709_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-065",
    "fecha": "2025-03-10",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA CON PROYECTO DE DECRETO QUE ADICIONA UNA FRACCIÓN XI DEL ARTICULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19591_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-066",
    "fecha": "2025-03-10",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA PARA LA IMPLEMENTACIÓN DE LA “RUTA VERDE”, MOVILIDAD SOSTENIBLE EN NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19607_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-067",
    "fecha": "2025-02-19",
    "tipo_acto": "Iniciativa",
    "estatus": "Atendido/a",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA CON PROYECTO DE DECRETO POR EL QUE SE REFORMA LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN, EN EL SENTIDO DE QUE LOS MOTOCICLISTAS PORTEN EN EL CASCO UNA ESTAMPA CON EL NÚMERO DE PLACA CORRESPONDIENTE, ASÍ COMO UN CHALECO REFLEJANTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19442_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-068",
    "fecha": "2025-01-28",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 30 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19340_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2024-010",
    "fecha": "2024-11-25",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA DIVERSOS ARTÍCULOS A LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN, CON EL OBJETIVO DE SENTAR BASES PARA LA CREACIÓN, REGLAMENTACIÓN Y HOMOLOGACIÓN DEL CONVENIO DE COMÚN ACUERDO DE ACEPTACIÓN DE RESPONSABILIDAD VIAL PARA LOS MUNICIPIOS DEL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19147_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2024-011",
    "fecha": "2024-11-25",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTÍCULOS 142 Y 144 DE LA LEY DE MOVILIDAD SOSTENIBLE Y ACCESIBILIDAD PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19130_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2024-012",
    "fecha": "2024-09-18",
    "tipo_acto": "Iniciativa",
    "estatus": "Dado de baja conforme al Art. 46 del Reglamento",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO 70 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP18734_VP.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2024-013",
    "fecha": "2024-04-30",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A DIVERSOS ARTÍCULOS DE LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/65a6fefa339d07eb79a3167c9564efcf71c34195.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Ciudadanas"
  },
  {
    "id": "NL-2025-069",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 120 Y POR ADICIÓN DE LOS ARTÍCULOS 90 BIS 1 Y 90 BIS 2, 109 BIS Y 109 BIS 1 A LA LEY DE EDUCACIÓN DEL ESTADO, EN RELACIÓN A QUE SE REGULE EL PROGRAMA DE TRANSPORTE ESCOLAR EN INSTITUCIONES PÚBLICA Y PRIVADAS DE EDUCACIÓN PRIMARIA Y SECUNDARIA, COMO MEDIDA INTEGRAL QUE CONTRIBUYE A LA PREVENCIÓN DE LA CONTAMINACIÓN AMBIENTAL Y LA MEJORA D",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP20123.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Municipales"
  },
  {
    "id": "NL-2025-070",
    "fecha": "2025-08-06",
    "tipo_acto": "Iniciativa",
    "estatus": "En estudio",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA A LOS ARTÍCULOS 4 BIS 8, 70 Y 144 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/99ea8d1811f5640661d02f6fc873e3b7d435e4ff.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Municipales"
  },
  {
    "id": "NL-2025-071",
    "fecha": "2025-02-11",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTAN INICIATIVA DE REFORMA AL ARTÍCULO 15 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2025-EXP19398.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Municipales"
  },
  {
    "id": "NL-2024-014",
    "fecha": "2024-12-02",
    "tipo_acto": "Iniciativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA AL ARTÍCULO DÉCIMO NOVENO TRANSITORIO DE LA LEY DE MOVILIDAD SOSTENIBLE, ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEÓN.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/iniciativas_lxxvii/pdf/LXXVII-2024-EXP19193.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Municipales"
  },
  {
    "id": "NL-2026-011",
    "fecha": "2026-03-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "DIVERSOS EXHORTOS AL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD DEL ESTADO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/20416%2020438%2020695%2020796%2020826%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2026-012",
    "fecha": "2026-02-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Recibidas en tiempo y forma. Atiende parcialmente las observaciones",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "OBSERVACIONES AL DECRETO NUM. 147 QUE CONTIENE LA REFORMA POR ADICION DE UN CAPITULO PRIMERO DENOMINADO 'TARIFAS SOCIALES AL USO DEL TRANSPORTE PUBLICO' EL CUAL CONTIENE LOS ARTICULOS 183 BIS, 183 BIS 1 Y 183 BIS 2 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON. SE TURNA CON CARACTER URGENTE.NOTA: MODIFICADO EN EL PLENO DEL CONGRESO, VER DECRETO P",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/Dictamen%2020514%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-072",
    "fecha": "2025-12-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "EXHORTO A LA SECRETARIA DE MOVILIDAD Y PLANEACION URBANA DE NUEVO LEON, PARA QUE EN EL AMBITO DE SUS COMPETENCIAS, DISEÑE, IMPLEMENTE Y ACTUALICE UN PADRON ESTATAL GRATUITO DE PERSONAS USUARIAS DE SCOOTERS MOTORIZADOS COMO DISPOSITIVOS DE MICROMOVILIDAD; ASI MISMO SE EXHORTE A LOS 51 MUNICIPIOS DEL ESTADO, PARA QUE EN EL AMBITO DE SUS COMPETENCIAS REGULEN EL USO EXCLUSIVAMENTE EN VIAS SECUNDARIAS",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/20033%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-073",
    "fecha": "2025-12-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Atendido/a",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL GOBERNADOR DEL ESTADO, PARA QUE EN SU CARACTER DE JEFE DE LA ADMINISTRACION PUBLICA ESTATAL Y PRESIDENTE DE LA JUNTA DE GOBIERNO DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD DE NUEVO LEON Y PRESIDENTE DEL CONSEJO DE ADMINISTRACION DEL SISTEMA DE TRANSPORTE COLECTIVO “METRORREY”, A FIN DE QUE, CON CARACTER DE URGENTE IMPLEMENTE LAS MEDIDAS NECESARIAS PARA GARANTIZAR EL RESTABLECIMIENTO DE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/20188%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-074",
    "fecha": "2025-10-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL TITULAR DE LA AGENCIA REGULADORA DEL TRANSPORTE FERROVIARIO, ORGANO DESCONCENTRADO DE LA SECRETARIA DE COMUNICACIONES Y TRANSPORTES, PARA QUE EN COORDINACION CON LOS TITULARES DE LA SECRETARIA DE MOVILIDAD Y PLANEACION URBANA DEL ESTADO Y DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD DE NUEVO LEON, SOLICITEN A LAS EMPRESAS ENCARGADAS DE LA CONCESION DE LAS VIAS FERROVIARIAS QUE REALICEN LA",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/DICTAMEN%2019808%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-075",
    "fecha": "2025-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE REFORMA A LA LEY DE MOVILIDAD SOSTENIBLE DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/DICTAMEN%2019538%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-076",
    "fecha": "2025-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "INICIATIVAS DE REFORMAS A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18742-LXXVII%20%2018959-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-077",
    "fecha": "2025-10-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL GERENTE DE DISTRIBUCION DE LA DIVISION DE GOLFO NORTE DE LA COMISION FEDERAL DE ELECTRICIDAD, PARA QUE ATIENDA TODOS LOS LLAMADOS Y REPORTES DE LAS COLONIAS MITRAS CENTRO, OBISPADO, ESPAÑA, BUROCRATAS MUNICIPALES Y SIERRA VENTANA EN EL MUNICIPIO DE MONTERREY, NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/20023-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-078",
    "fecha": "2025-10-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL GERENTE DE DISTRIBUCION DE LA DIVISION GOLFO NORTE DE LA COMISION FEDERAL DE ELECTRICIDAD PARA QUE EN EL AMBITO DE SUS ATRIBUCIONES Y EN LA MEDIDA DE LO POSIBLE SE CAMBIEN LOS TRANSFORMADORES DE LUZ QUE YA SE ENCUENTREN MUY DETERIORADOS O EN MAL ESTADO; CON EL OBJETO DE QUE EL MUNICIPIO DE JUAREZ, NUEVO LEON, NO SUFRAN ALTERACIONES EN EL VOLTAJE NI INTERRUPCIONES QUE PONGAN EN RIESGO SU",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/19943-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-079",
    "fecha": "2025-10-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL SOLICITA LA APROBACION DE UN PUNTO DE ACUERDO, A FIN DE EXHORTAR A LOS 51 AYUNTAMIENTOS DEL ESTADO DE NUEVO LEON, PARA QUE EN EL AMBITO DE SUS ATRIBUCIONES REALICEN LOS TRABAJOS NECESARIOS PARA CONTAR CON VIAS PEATONALES O BANQUETAS CON CONTINUIDAD Y ACCESIBILIDAD UNIVERSAL.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/P_19983%20LXXVII%20C.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-080",
    "fecha": "2025-10-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL TITULAR DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD DEL ESTADO, PARA QUE RINDE INFORME DETALLADO SOBRE LAS CAUSAS POR LAS CUALES LAS UNIDADES DE LA RUTA 217 ESCOBEDO- GUADALUPE NO ESTAN REALIZANDO SU RECORRIDOS DE MANERA COMPLETA, ENTRE OTROS. SE TURNA CON CARACTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/DICTAMEN%2019441%20LXXVII%20%281%29.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-081",
    "fecha": "2025-10-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE REFORMA POR ADICION AL ARTICULO 68 BIS 1 DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON; Y C. DIP. LORENA DE LA GARZA VENECIA, INTEGRANTE DEL GRUPO LEGISLATIVO DEL PARTIDO REVOLUCIONARIO INSTITUCIONAL DE LA LXXVII LEGISLATURA, MEDIANTE EL CUAL PRESENTA INICIATIVA DE REFORMA A LOS ARTICULOS 8 Y 68 BIS DE LA LEY DE MOVILIDAD SOSTENIBLE",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/PROYECTO%20DE%20DICTAMEN%2019683%20y%2020272.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-082",
    "fecha": "2025-10-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL C. HERNAN MANUEL VILLARREAL RODRIGUEZ, ENCARGADO DE LA SECRETARIA DE MOVILIDAD Y PLANEACION URBANA PARA QUE ADOPTE, EN EL AMBITO DE SU COMPETENCIA, TODAS LAS MEDIDAS NECESARIAS DE SUPERVISION, PREVENCION Y COORDINACION INTERINSTITUCIONAL A FIN DE GARANTIZAR LA SEGURIDAD EN LAS ZONAS DE CONSTRUCCION Y TRANSITO.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/DICTAMEN%2019944%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-083",
    "fecha": "2025-09-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "EXHORTO A LOS 51 AYUNTAMIENTOS DEL ESTADO, PARA QUE REALICEN MODIFICACIONES A SUS REGLAMENTOS DE TRANSITO Y VIALIDAD Y ESTABLEZCAN NORMATIVAS DE CERO TOLERANCIA A VEHICULOS CONTAMINANTES.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/DICTAMEN%2019615%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen | Auditado: reclasificado"
  },
  {
    "id": "NL-2025-084",
    "fecha": "2025-09-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL TITULAR DE LA SECRETARIA DE HACEIDNA Y CREDITO PUBLICO, AL TITULAR DE LA PROFECO, A LA COMISION REGULADORA DE ENERGIA PARA QUE DE CONFORMIDAD CON EL ARTICULO 31 FRACCION IX DE LA LEY ORGANICA DE LA ADINISTRACION PUBLICA FEDERAL, ANALICE LA VIABILIDAD DE FORTALECER LOS CRITERIOS Y MONTOS GLOBALES DEL ESTIMULO FISCAL EN MATERIA DEL IMPUESTO ESPECIAL SOBRE PRODUCCION Y SERVICIOS APLICABLES",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/19198-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-085",
    "fecha": "2025-04-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL SOLICITA LA APROBACION DE UN PUNTO DE ACUERDO, A FIN DE ENVIAR UN EXHORTO AL TITULAR DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD, C. JOSE MANUEL VALDEZ, A FIN DE QUE NO SE ELIMINE EL PAGO EN EFECTIVO EN LAS RUTAS URBANAS HASTA QUE SE GARANTICE EL ABASTECIMIENTO SUFICIENTE Y PERMANENTE DE LAS TARJETAS “ME MUEVO” EN LOS PUNTOS DE VENTA ESTABLECIDOS; YMEDIANTE EL CUAL SOLICITA LA APRO",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18640-%20LXXVI%20y%2018926-%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-086",
    "fecha": "2025-04-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL ENCARGADO DE LA DIRECCION GENERAL DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD PARA QUE DEJE SIN EFECTOS EL ACUERDO, POR EL QUE SE CREAN LAS 'RUTAS EXPRES INTEGRADAS', CON EL FIN DE QUE SE MANTENGA LA TARIFA ESTABLECIDA PARA ESAS UNIDADES DE TRANSPORTE PUBLICO, HASTA EN TANTO NO SE DISEÑE UN PLAN INTEGRAL CONFORME AL MARCO NORMATIVO APLICABLE; ASI COMO SE LLEVE A CABO LAS ACCIONES, CONFOR",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18936-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-087",
    "fecha": "2025-04-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL ING. ROBERTO ABRAHAM VARGAS MOLINA, ENCARGADO DEL DESPACHO DE LA DIRECCION GENERAL DEL INSTITUTO DE MOVILIDAD Y ACCESIBILIDAD PARA QUE IMPLEMENTE PROGRAMAS DE DESCUENTO Y CONDONACION DE MULTAS IMPAGABLES EN BENEFICIO DE LOS OPERADORES DEL TRANSPORTE; FACILIDADES ADMINISTRATIVAS A LOS OPERADOS DEL TRANSPORTE QUE BUSQUEN REGULARIZARSE Y REINCORPORARSE AL MERCADO LABORAL.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18831%20-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-088",
    "fecha": "2025-03-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "MEDIANTE EL CUAL REMITE EL DECRETO 88 QUE CONTIENE INICIATIVA DE REFORMA A DIVESOS ARTICULOS DE LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON, POR HABERSE OBSERVADO, DISCORDANCIAS ENTRE EL CONTENIDO DEL ARTICULADO VIGENTE. SE TURNA CON CARACTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/19643%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-089",
    "fecha": "2025-03-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL TITULAR DEL PODER EJECUTIVO DEL ESTADO, PARA QUE EN EL EJERCICIO DE SUS ATRIBUCIONES INSTRUYA A LA DEPENDENCIA COMPETENTE A AGILIZAR LA EXPEDICION DE LAS CARTAS DE ANTECEDENTES NO PENALES, PARA QUE SE EMITAN EN UN TIEMPO RAZONABLE, CON LA FINALIDAD DE QUE PERMITAN A LOS CHOFERES DE TRANSPORTE PUBLICO Y TAXISTAS CUMPLIR CON LOS REQUISITOS PARA LA RENOVACION O EXPEDICION DE SUS LICENCIAS.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18977-LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-090",
    "fecha": "2025-03-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "EXHORTO AL TITULAR DEL GOBIERNO DEL ESTADO, PARA QUE GIRE INSTRUCCIONES A LA SECRETARIA DE MOVILIDAD Y PLANEACION URBANA, PARA QUE DOTE DE MAS UNIDADES DE TRANSPORTE A LA RUTA EXPRESS PORTAL DE LAS SALINAS-CLINICA 6. SE TURNA CON CARACTER DE URGENTE.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/18695%20-%20LXXVII.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  },
  {
    "id": "NL-2025-091",
    "fecha": "2025-03-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "REFORMA INTEGRAL A LA LEY DE MOVILIDAD SOSTENIBLE, DE ACCESIBILIDAD Y SEGURIDAD VIAL PARA EL ESTADO DE NUEVO LEON.",
    "resumen": "",
    "link_documento": "https://www.hcnl.gob.mx/trabajo_legislativo/pdf/lxxvii/REFORMA%20INTEGRAL%20MOVILIDAD.pdf",
    "link_portal": "",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Término búsqueda: Dictamen"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
