const DATA = [
  {
    "id": "ZAC-2017-001",
    "fecha": "2017-10-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se exhorta al Titular del Poder Ejecutivo del Estado, para que desarrolle un Plan de Transporte Público con perspectiva de género, que atienda las necesidades de mujeres estudiantes, trabajadoras y ambulantes, así como de personas con discapacidad.",
    "resumen": "La LXII Legislatura exhortó al Ejecutivo estatal a desarrollar un Plan de Transporte Público con perspectiva de género, atendiendo a mujeres y personas con discapacidad. Es uno de los primeros registros de enfoque de género en movilidad para Zacatecas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20181128124007.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/1955",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXII | Votación del dictamen: A Favor 27"
  },
  {
    "id": "ZAC-2019-001",
    "fecha": "2019-07-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "La H. Sexagésima Tercera Legislatura del Estado respetuosamente exhorta al H. Ayuntamiento de Zacatecas, a través de su Presidente Municipal para que incluya Infraestructura Urbana Especial que permita la circulación de personas con discapacidad.",
    "resumen": "La LXIII Legislatura exhortó al Ayuntamiento de Zacatecas para que incluya infraestructura urbana especial que permita la movilidad de personas con discapacidad. Señala la necesidad de accesibilidad universal en el espacio público de la capital.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20190701150409.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/2348",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad | Legislatura: LXIII"
  },
  {
    "id": "ZAC-2019-002",
    "fecha": "2019-08-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se solicita a la Auditoria Superior del Estado, inicie una auditoría de las concesiones del transporte público, otorgadas en el Estado de Zacatecas, para la forestación del servicio de transporte público.",
    "resumen": "La LXIII Legislatura solicitó a la Auditoría Superior del Estado iniciar una auditoría a las concesiones del transporte público de Zacatecas. El objetivo era revisar la legalidad y condiciones de las concesiones otorgadas para el servicio de transporte.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20200526092653.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/2651",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXIII | Fecha lectura pleno: 27-AGO-2019 | Dictamen: 10-MAR-2020"
  },
  {
    "id": "ZAC-2019-003",
    "fecha": "2019-08-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "La H. LXIII Legislatura del Estado exhorta a la Comisión Federal de Electricidad a que en el ámbito de sus atribuciones vigile el correcto funcionamiento del servicio de energía eléctrica en los municipios.",
    "resumen": "La LXIII Legislatura exhortó a la CFE a vigilar el correcto funcionamiento del servicio eléctrico en los municipios de Zacatecas. Surge en un contexto de quejas por fallas en el suministro eléctrico en zonas municipales.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20190808131542.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/2377",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: electrica | Legislatura: LXIII"
  },
  {
    "id": "ZAC-2021-001",
    "fecha": "2021-11-10",
    "tipo_acto": "Minuta",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Se aprueba la minuta de decreto, por el que se reforman diversas disposiciones de la Constitución Política de los Estados Unidos Mexicanos, en materia de movilidad y seguridad vial.",
    "resumen": "Zacatecas ratificó la reforma constitucional federal que reconoce el derecho a la movilidad y la seguridad vial como derechos constitucionales. Esta reforma (Decreto 442 de la LXIII Legislatura) fue una de las más significativas en materia de movilidad en México.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20211110140615.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/2831",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad | Legislatura: LXIII | Decreto 442"
  },
  {
    "id": "ZAC-2022-001",
    "fecha": "2022-03-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "La LXIII Legislatura de Zacatecas exhorta respetuosamente al Director de la C.F.E., Dr. Manuel Bartlett Díaz, para que implemente programas de diferimiento del pago por el suministro de energía eléctrica.",
    "resumen": "La LXIII Legislatura exhortó al director de la CFE a implementar programas de diferimiento de pagos por suministro eléctrico para usuarios zacatecanos en contexto de dificultades económicas. Refleja la preocupación por el acceso al servicio eléctrico en el estado.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220301104222.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3215",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: electrica | Legislatura: LXIII"
  },
  {
    "id": "ZAC-2022-002",
    "fecha": "2022-03-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "La LXIII Legislatura del Estado de Zacatecas, exhorta respetuosamente, al titular del poder ejecutivo, para que en el ámbito de su competencia, instale de nueva cuenta en sus términos originales el programa de ciclovías en la ciudad de Zacatecas.",
    "resumen": "La LXIII Legislatura exhortó al Ejecutivo estatal a reinstalar el programa de ciclovías en la ciudad de Zacatecas. Indica que existía un programa previo de ciclovías que había sido retirado, solicitando su restauración.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220309142259.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3260",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: ciclista | Legislatura: LXIII"
  },
  {
    "id": "ZAC-2022-003",
    "fecha": "2022-03-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Se exhorta a la Secretaría de Energía del Gobierno Federal a que revise los contratos firmados entre ejidatarios del Estado de Zacatecas, y las empresas privadas que se dedican a producir energías alternativas (solar y eólica).",
    "resumen": "La LXIII Legislatura exhortó a la SENER a revisar contratos entre ejidatarios zacatecanos y empresas de energía solar y eólica. Señala posibles inequidades en las condiciones contractuales, dada la importancia de Zacatecas como estado con potencial solar y eólico.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220310135005.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3281",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: solar | Legislatura: LXIII"
  },
  {
    "id": "ZAC-2022-004",
    "fecha": "2022-03-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Se exhorta respetuosamente al titular del poder ejecutivo a realizar las gestiones necesarias correspondientes ante la Comisión Federal de Electricidad con la finalidad de que sean condonados los adeudos de los usuarios.",
    "resumen": "La LXIII Legislatura (CP) exhortó al Ejecutivo estatal a gestionar ante la CFE la condonación de adeudos de usuarios zacatecanos. Este exhorto, aprobado en periodo de receso, buscaba aliviar la carga económica por deudas eléctricas acumuladas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220323122755.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3375",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energia | Legislatura: LXIII | Comisión Permanente ACP38"
  },
  {
    "id": "ZAC-2022-005",
    "fecha": "2022-06-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "ENE_REG",
    "extracto": "Se exhorta de manera respetuosa a la Comisión reguladora de energía y a la secretaria de energía del gobierno federal a través de la Dirección General de Petróleos Mexicanos (PEMEX) para regular el precio.",
    "resumen": "La LXIV Legislatura exhortó a la CRE y la SENER, a través de PEMEX, para regular precios de combustibles. El exhorto buscaba un impacto en los precios locales de hidrocarburos en Zacatecas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220613150501.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3547",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energia | Legislatura: LXIV | Subtema corregido: ENE_TAR→ENE_HC (el foco es PEMEX/combustibles"
  },
  {
    "id": "ZAC-2022-006",
    "fecha": "2022-06-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Se exhorta respetuosamente al Titular del Ejecutivo Federal, para que gire instrucciones al Director General de la Comisión Federal de Electricidad (CFE), Manuel Bartlett Díaz, con el objeto de que, se restablezca el suministro de energía eléctrica.",
    "resumen": "La LXIV Legislatura exhortó al Ejecutivo Federal para que la CFE restablezca el suministro eléctrico interrumpido en comunidades zacatecanas. Responde a cortes de luz en el estado que afectaban a poblaciones vulnerables.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20220624135932.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3588",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: electrica | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2023-001",
    "fecha": "2023-06-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Se exhorta respetuosamente al Gobierno del Estado de Zacatecas a través de su Secretaría de Obras Públicas para realizar los proyectos y ejecutar las obras que permitan la circulación continúa y armónica de ciclistas.",
    "resumen": "La LXIV Legislatura exhortó a la Secretaría de Obras Públicas a construir infraestructura ciclista en Zacatecas para garantizar la circulación segura de ciclistas. Muestra la creciente atención legislativa a la movilidad activa.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20230628112214.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/3872",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: ciclista | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2024-001",
    "fecha": "2024-05-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Se autorice la comparecencia ante la Comisión Legislativa de Comunicaciones y Transportes, de los Titulares de la Secretaría de Desarrollo Urbano, Vivienda y Ordenamiento Territorial (SEDUVOT) y de la Secretaría de Seguridad Pública, en materia de movilidad urbana.",
    "resumen": "La LXIV Legislatura aprobó citar a comparecer a la SEDUVOT y a Seguridad Pública ante la comisión de Comunicaciones y Transportes sobre movilidad urbana. Mecanismo de control legislativo para rendir cuentas sobre la política de movilidad en Zacatecas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240513115448.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4078",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2024-002",
    "fecha": "2024-05-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Exhortar al Titular de la Secretaria de Seguridad Pública del Estado, para que, a través de la Dirección de Policía de Seguridad Vial, para que se instale la señalética correspondiente en las vías de comunicación para proteger a las personas peatonas.",
    "resumen": "La LXIV Legislatura exhortó a la SSP a instalar señalética de protección a peatones en vías de comunicación, a través de la Dirección de Policía de Seguridad Vial. Refleja la preocupación por la seguridad de los peatones en Zacatecas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240513115941.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4079",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: peaton | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2024-003",
    "fecha": "2024-05-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de punto de acuerdo, por el que se exhorta al titular de la Secretaría de Finanzas a transferir los recursos recabados por las multas generadas por obstruir o utilizar espacios destinados a personas con discapacidad.",
    "resumen": "La LXIV Legislatura exhortó a la Secretaría de Finanzas a redirigir los recursos de multas por obstrucción de espacios para discapacidad hacia mejoras de accesibilidad. Mecanismo para financiar infraestructura de movilidad inclusiva.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240523122129.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4134",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: peaton | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2024-004",
    "fecha": "2024-08-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Se exhorta respetuosamente al titular de la Dirección de Policía de Seguridad Vial, para que se implemente un operativo de revisión a las unidades de transporte público con adaptación de rampas de acceso para personas con discapacidad.",
    "resumen": "La LXIV Legislatura exhortó a la Policía de Seguridad Vial a realizar operativos de verificación de rampas de accesibilidad en unidades de transporte público para personas con discapacidad. Combina control de cumplimiento de concesiones con accesibilidad.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240822151013.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4282",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: vialidad | Legislatura: LXIV"
  },
  {
    "id": "ZAC-2024-005",
    "fecha": "2024-09-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforman, adicionan y derogan diversas disposiciones de las Leyes de Transporte, Tránsito y Vialidad, la de instituciones policiales de la Secretaría de Seguridad Pública y la del Sistema Estatal de Seguridad.",
    "resumen": "Reforma integral de la Ley de Transporte, Tránsito y Vialidad de Zacatecas, junto con las leyes de instituciones policiales de la SSP y del Sistema Estatal de Seguridad. Es la reforma más amplia al marco legal de movilidad en el estado en la LXIV Legislatura.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240905154302.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4291",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXIV | Decreto 456"
  },
  {
    "id": "ZAC-2024-006",
    "fecha": "2024-09-19",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Dictamen respecto de las iniciativas con proyecto de decreto, por las cuales se reforma la Ley de Transporte, Tránsito y Vialidad del Estado de Zacatecas.",
    "resumen": "La LXIV Legislatura aprobó el dictamen sobre diversas iniciativas de reforma a la Ley de Transporte, Tránsito y Vialidad. Consolida el proceso legislativo de reformas al marco regulatorio del transporte y la vialidad en Zacatecas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20240919150442.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4364",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXIV | Decreto 529"
  },
  {
    "id": "ZAC-2024-007",
    "fecha": "2024-09-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Se exhorta a las autoridades de la Comisión Federal de Electricidad en nuestro Estado para que tengan a bien revisar las condiciones en las que se encuentra la infraestructura de telecomunicaciones, así como el estado de la red eléctrica derivado de los múltiples apagones registrados en diversas zonas del semidesierto zacatecano.",
    "resumen": "La LXV Legislatura exhortó a la CFE a revisar el estado de la infraestructura eléctrica en el semidesierto zacatecano, tras múltiples apagones reportados. El exhorto incluyó también la revisión de la infraestructura de telecomunicaciones afectada.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250205143852.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4610",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: electrica | Legislatura: LXV | Fecha lectura pleno: 19-SEP-2024"
  },
  {
    "id": "ZAC-2024-008",
    "fecha": "2024-10-18",
    "tipo_acto": "Minuta",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Por el que se reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la Constitución Política de los Estados Unidos Mexicanos, en materia de vías de transporte ferroviario.",
    "resumen": "Zacatecas ratificó la Minuta del Congreso de la Unión para reformar el artículo 28 de la CPEUM en materia de vías de transporte ferroviario. Esta reforma establece el marco constitucional para que el Estado pueda participar en la operación de ferrocarriles.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250224123702.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4620",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXV | Decreto 007 | Fecha lectura pleno: 17-OCT-2024"
  },
  {
    "id": "ZAC-2024-009",
    "fecha": "2024-12-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Exhorta de manera respetuosa, al Titular del Poder Ejecutivo, para que gire instrucciones a quien corresponda con el objeto de que se preste el servicio de transporte público de manera regular y eficiente en todas las colonias de la Capital que cubre la Ruta 7.",
    "resumen": "La LXV Legislatura (Comisión Permanente) exhortó al Ejecutivo estatal a garantizar el servicio regular y eficiente de la Ruta 7 de transporte público en la capital. Muestra la atención legislativa a problemas concretos del servicio de transporte urbano.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250925141654.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4806",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXV | Comisión Permanente ACP02 | Fecha lectura pleno: 21-ENE-2025"
  },
  {
    "id": "ZAC-2025-001",
    "fecha": "2025-01-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorta respetuosamente al Titular del Poder Ejecutivo del Estado, a efecto de que, a través de la Secretaría de Obras Públicas del Gobierno del Estado, se inicien las labores de construcción de un puente peatonal.",
    "resumen": "La LXIV Legislatura (Comisión Permanente) exhortó al Ejecutivo estatal a iniciar la construcción de un puente peatonal a través de la Secretaría de Obras Públicas. El puente busca garantizar la movilidad activa segura para peatones en un punto específico del estado.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250115154844.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4581",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: peaton | Legislatura: LXIV | Comisión Permanente ACP39 | Fecha PDF: 15-ENE-2025"
  },
  {
    "id": "ZAC-2025-002",
    "fecha": "2025-02-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Respecto de la iniciativa con proyecto de Decreto, por el que se exhorta a la Secretaría de Energía del gobierno federal para que, en la generación de energía eólica y solar considere al Estado de Zacatecas como polo de desarrollo fundamental del centro norte del país.",
    "resumen": "La LXV Legislatura aprobó el dictamen sobre el exhorto a la SENER para que Zacatecas sea considerado polo de desarrollo de energía eólica y solar. Solicita además el desarrollo de infraestructura de generación de energías renovables y la creación de empleos en la entidad.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250908144619.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4791",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: solar | Legislatura: LXV | Dictamen: 12-JUN-2025 | Comisión: Innovación y competitividad"
  },
  {
    "id": "ZAC-2025-003",
    "fecha": "2025-03-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Se exhorta respetuosamente a la Secretaría General de Gobierno del Estado de Zacatecas, para que en ejercicio de sus facultades, revise que las y los concesionarios del transporte público de la Entidad, cumplan con las obligaciones establecidas en la Ley de Transporte, Tránsito y Vialidad del Estado de Zacatecas, respecto a las personas con discapacidad.",
    "resumen": "La LXV Legislatura exhortó a la Secretaría General de Gobierno a verificar que los concesionarios de transporte público cumplan con las obligaciones sobre accesibilidad para personas con discapacidad establecidas en la Ley de Transporte. Refuerza el acceso inclusivo al transporte.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250618155404.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4753",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXV | Fecha lectura pleno: 27-MAR-2025"
  },
  {
    "id": "ZAC-2025-004",
    "fecha": "2025-04-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Respecto de las iniciativas de punto de acuerdo mediante las que se exhorta, respetuosamente, a diversas autoridades para que refuercen e implementen la revisión y detección de conductores de motocicletas y otros vehículos y verificar que cumplan con lo establecido en la Ley de Transporte, Tránsito y Vialidad del Estado de Zacatecas y su Reglamento.",
    "resumen": "La LXV Legislatura aprobó exhortar a diversas autoridades a reforzar la revisión de conductores de motocicletas y vehículos para verificar cumplimiento de la Ley de Transporte, Tránsito y Vialidad. Responde a la problemática de seguridad vial vinculada a motociclistas.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250908142227.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4790",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Legislatura: LXV | Dictamen: 12-JUN-2025 | Comisiones: Seguridad Pública + Movilidad"
  },
  {
    "id": "ZAC-2025-005",
    "fecha": "2025-04-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En comisión",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Se exhorta al Titular del Poder Ejecutivo Federal, para que a través de la Secretaría de Agricultura y Desarrollo Rural (SADER), realice las gestiones necesarias para extender el registro al Programa Especial de Energía Para el Campo en el Ámbito de la Energía Eléctrica de Uso Agrícola (PEUA).",
    "resumen": "La LXV Legislatura exhortó al Ejecutivo Federal a través de la SADER para extender el registro al Programa PEUA (Energía Eléctrica para Uso Agrícola) para que productores zacatecanos puedan acceder a sus beneficios. El PEUA subsidia el costo eléctrico del sector agrícola.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250620145634.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4760",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En comisión | Término búsqueda: energia | Legislatura: LXV | Comisión: Agricultura y Desarrollo Rural | Recepción comisión: 23-24 ABR-2025 | Dictamen: 08-MAY-2025"
  },
  {
    "id": "ZAC-2025-006",
    "fecha": "2025-04-29",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "La Honorable Sexagésima Quinta Legislatura del Estado de Zacatecas, respetuosamente exhorta e invita a las diputadas y diputados, senadoras y senadores de origen zacatecano, que integran el Honorable Congreso de la Unión, a celebrar una reunión de trabajo con el sector campesino del estado de Zacatecas, a efecto de buscar alternativas de solución en el tema de concesiones y subsidios, relacionado con el Programa Especial de Energía para el Campo en materia de Energía Eléctrica para Uso Agrícola (PEUA).",
    "resumen": "La LXV Legislatura exhortó e invitó a los legisladores federales de origen zacatecano a reunirse con el sector campesino estatal para buscar alternativas sobre el PEUA (subsidio de energía eléctrica agrícola). Refleja la presión del sector rural por el costo energético.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250620103545.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energia | Legislatura: LXV | Fecha lectura pleno: 29-ABR-2025 | Todos los grupos parlamentarios"
  },
  {
    "id": "ZAC-2025-007",
    "fecha": "2025-05-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo, por el que se exhorta respetuosamente al Titular del Poder Ejecutivo del Estado de Zacatecas, para que, por su conducto solicite al Director General de la CONAGUA, al Secretario de SADER y a la Directora General de la CFE, a buscar alternativas y mecanismos de solución, en el ámbito de sus atribuciones y competencia, en el tema de concesiones y subsidios, relacionado con el Programa Especial de Energía para el Campo en materia de Energía Eléctrica para el Uso Agrícola (PEUA).",
    "resumen": "La LXV Legislatura (JUCOPO) exhortó al Ejecutivo estatal a gestionar ante CONAGUA, SADER y CFE alternativas de solución al problema de concesiones y subsidios del PEUA. Complementa el exhorto anterior (ZAC-2025-006) con una acción dirigida al Ejecutivo estatal.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20250620104740.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energia | Legislatura: LXV | Fecha lectura pleno: 08-MAY-2025 | Proponente: JUCOPO (todos los grupos)"
  },
  {
    "id": "ZAC-2025-008",
    "fecha": "2025-05-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Se exhorta a las autoridades estatales y municipales para que implementen medidas promoción de la eficiencia energética y aprovechamiento de las energías renovables, tanto en el sector público como privado, y entre la población, buscando ampliar la infraestructura energética eco-sustentable y mejorando los procesos de investigación e innovación.",
    "resumen": "La LXV Legislatura exhortó a autoridades estatales y municipales a implementar medidas de eficiencia energética y aprovechamiento de energías renovables en sectores público y privado. Propone ampliar la infraestructura eco-sustentable e impulsar investigación e innovación energética.",
    "link_documento": "https://www.congresozac.gob.mx/coz/images/uploads/20251104153758.pdf",
    "link_portal": "https://www.congresozac.gob.mx/sil/4827",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energia | Legislatura: LXV | Dictamen: 24-JUN-2025 | Comisión: Medio Ambiente y Cambio Climático"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
