const DATA = [
  {
    "id": "MOR-2024-001",
    "fecha": "2024-09-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada por unanimidad (20 votos)",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Aprueban nueva Ley Orgánica de la Administración Pública Estatal creando la Coordinación General de Movilidad y Transporte como organismo descentralizado adscrito a la Secretaría de Gobierno, con Junta de Gobierno integrada por ejecutivo y secretarios.",
    "resumen": "Se aprueba por unanimidad la nueva Ley Orgánica de la Administración Pública Estatal que crea la Coordinación General de Movilidad y Transporte como organismo descentralizado. Establece el marco institucional y de gobernanza para regular el transporte y la movilidad en Morelos. La reforma deroga la ley orgánica anterior de 2018.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2024/09/26/aprueban-nueva-ley-organica-de-la-administracion-publica-estatal-y-crean-la-coordinacion-general-de-movilidad-y-transporte/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada por unanimidad | Término búsqueda: transporte | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2024-002",
    "fecha": "2024-10-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Mesa de trabajo instalada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Consideran que ejercen competencia desleal porque plataformas no cumplen regulaciones que taxistas tradicionales deben satisfacer, incluyendo tarjetón de conductor y revista mecánica.",
    "resumen": "La diputada Jazmín Solano y el diputado Sergio Livera propusieron regular las plataformas de transporte digital (Uber, Didi) para equipararlas con los requisitos que ya cumplen los taxistas tradicionales. Se instaló una mesa de trabajo en la Comisión de Movilidad para analizar la propuesta y armonizarla con la Ley del Transporte estatal.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2024/10/24/a-revision-de-plataformas-de-transporte-digital-diputada-jazmin-solano-propone/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Mesa de trabajo instalada | Término búsqueda: transporte | Subtema corregido: MOV_ELEC→MOV_TP (el efecto jurídico es regulación de operadores de transporte no electromovilidad) | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2024-003",
    "fecha": "2024-11-07",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "ENE_EF",
    "extracto": "Se debe fomentar el aprovechamiento de las energías renovables, el uso de tecnologías limpias y la eficiencia energética, como instrumento de promoción de una sociedad sustentable.",
    "resumen": "La diputada Jazmín Solano propuso una Ley de Fomento de la Eficiencia Energética y Energías Renovables para Morelos que busca apoyar investigación, desarrollo e innovación tecnológica en energías limpias, promover paneles solares en instalaciones educativas y alinear la política estatal con las metas nacionales (35% energía limpia en 2024, 45% en 2030).",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2024/11/07/impulsa-diputada-jazmin-solano-ley-de-fomento-de-la-eficiencia-energetica-y-del-aprovechamiento-de-las-fuentes-de-energias-renovables/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: energía | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2025-001",
    "fecha": "2025-02-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "El campo morelense no puede esperar más. El exhorto atiende daños por suspensión del subsidio a la electricidad que afectan bombas de agua para riego, amenazando la viabilidad agrícola y la seguridad alimentaria del estado.",
    "resumen": "La diputada Luz Dary Quevedo exhortó al gobernador, a la Secretaría de Agricultura y a la CFE a instalar mesas de trabajo urgentes con agricultores afectados por la suspensión del subsidio a la electricidad en pozos de riego. El Congreso aprobó el punto de acuerdo con apoyo del grupo parlamentario de Morena.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2025/02/21/exhorta-diputada-luz-dary-quevedo-a-resolver-danos-a-campesinos-por-suspender-subsidio-a-electricidad-en-pozos-de-agua-de-uso-agricola/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2025-002",
    "fecha": "2025-03-10",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Se hace indispensable contar con espacios de descanso en las carreteras estatales, lo cual permitirá no sólo espacios a las personas en condiciones de discapacidad, sino que también servirán para la prevención de accidentes.",
    "resumen": "El diputado Luis Eduardo Pedrero propuso reformas a la Ley del Transporte de Morelos para obligar la construcción de espacios de descanso accesibles en carreteras estatales. Las modificaciones incluyen rampas, pasillos ensanchados, baños accesibles, pisos firmes, ayudas técnicas e iluminación adecuada para personas con discapacidad y prevención de accidentes.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2025/03/10/platea-diputado-luis-eduardo-pedrero-adecuar-carreteras-para-la-movilidad-de-personas-con-discapacidad-y-prevenir-accidentes/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisión | Término búsqueda: movilidad | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2025-003",
    "fecha": "2025-03-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada en sesión ordinaria",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Imponer los dos requisitos: de antigüedad y de revisión mecánica anual al servicio de transporte de carga en general constituye una sobrerregulación que impacta al sector que aporta el 3.8% del PIB nacional.",
    "resumen": "La diputada Jazmín Solano propuso reformar la Ley del Transporte de Morelos para eliminar el requisito de antigüedad vehicular en unidades de transporte de carga, manteniendo únicamente la revisión mecánica anual. Argumenta que la doble regulación afecta competitividad de un sector que emplea más de un millón de personas al año.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2025/03/25/propone-diputada-jazmin-solano-eliminar-la-doble-regulacion-a-las-unidades-de-transporte-de-carga/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada en sesión ordinaria | Término búsqueda: transporte | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  },
  {
    "id": "MOR-2025-004",
    "fecha": "2025-06-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentado en sesión ordinaria",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Exhorta a coordinación de vigilancia y prevención de delitos en tramos vulnerables de la autopista México-Cuernavaca, establecimiento de operativos conjuntos permanentes más allá de periodos vacacionales, y demarcación precisa de zonas federales y de tránsito urbano.",
    "resumen": "El diputado Daniel Martínez Terrazas presentó un exhorto a la Guardia Nacional, Caminos y Puentes Federales y secretarías de seguridad de Morelos y CDMX para reforzar permanentemente la seguridad en la autopista México-Cuernavaca. Solicita operativos conjuntos continuos en horarios de riesgo y delimitación clara de competencias en tramos Tlalpan-Topilejo y La Pera-Cuernavaca.",
    "link_documento": "",
    "link_portal": "https://congresomorelos.gob.mx/2025/06/13/diputado-daniel-martinez-terrazas-llama-a-reforzar-seguridad-en-la-autopista-mexico-cuernavaca-de-forma-permanente/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentado en sesión ordinaria | Término búsqueda: tránsito | Fuente no verificada: portal publica boletín de prensa sin PDF del documento legislativo"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
