const DATA = [
  {
    "id": "CAM-2025-009",
    "fecha": "2025-11-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Iniciativa para reformar diversas disposiciones de la Ley de Movilidad y Seguridad Vial y de la Ley de Vialidad, Tránsito y Control Vehicular del Estado de Campeche; busca actualizar normas, fortalecer la seguridad vial y ordenar el tránsito priorizando a peatones, ciclistas, adultos mayores, estudiantes y usuarios del transporte público diario.",
    "resumen": "Los diputados Jiménez Gutiérrez y Talango Cervantes (Morena) presentaron una reforma integral a las dos leyes de movilidad del estado. La propuesta busca reducir accidentes, actualizar el marco normativo y construir una movilidad más humana y equitativa, con énfasis en los grupos más vulnerables de la vialidad campechana. Fue leída en la Novena Sesión del primer período ordinario del segundo año legislativo.",
    "link_documento": "https://www.congresocam.gob.mx/novena-sesion-primer-periodo-ordinario/",
    "link_portal": "https://www.congresocam.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | Fuente: resumen sesión 25/11/2025 | Sin número de expediente identificado | Promoventes: Dip. José Antonio Jiménez Gutiérrez y Omar Alberto Talango Cervantes (Morena)"
  },
  {
    "id": "CAM-2025-008",
    "fecha": "2025-10-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Dictamen aprobado que reforma la Ley de Vialidad, Tránsito y Control Vehicular del Estado de Campeche para precisar la correcta portación y visibilidad de las placas vehiculares: cuando un vehículo no cuente con el espacio destinado por el fabricante, las placas deberán colocarse en lugar visible al exterior garantizando su identificación y contribuyendo a una movilidad más segura y ordenada.",
    "resumen": "La Comisión de Seguridad Pública y Protección a la Comunidad dictaminó favorablemente la iniciativa de los diputados Rabelo Cuevas, Pool Alpuche y Abraham Quijano (PRI). La reforma otorga certeza jurídica a conductores, evita interpretaciones erróneas en procedimientos de tránsito y fortalece la seguridad vial en Campeche. El dictamen fue aprobado por el pleno en la Tercera Sesión del 14 de octubre de 2025.",
    "link_documento": "https://www.congresocam.gob.mx/tercera-sesion-primer-periodo-ordinario/",
    "link_portal": "https://www.congresocam.gob.mx/dictamenes/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: tránsito | Fuente: resumen sesión 14/10/2025 | Sin número de decreto identificado | Promoventes: Dip. Rabelo Cuevas, Pool Alpuche, Abraham Quijano (PRI) | Comisión: Seguridad Pública y Protección a la Comunidad"
  },
  {
    "id": "CAM-2025-007",
    "fecha": "2025-10-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa para reformar la Ley de Vialidad, Tránsito y Control Vehicular del Estado de Campeche a fin de facultar a las autoridades para retirar vehículos abandonados o estacionados por largos períodos en lugares que afecten la movilidad o representen un riesgo para la seguridad de personas, especialmente cerca de escuelas, hospitales o espacios públicos.",
    "resumen": "El diputado José Antonio Jiménez Gutiérrez (Morena) presentó iniciativa para reformar la Ley de Vialidad y facultar a las autoridades a remover vehículos abandonados que obstruyen la vía pública o representan riesgos viales. La propuesta busca mantener calles más seguras y ordenadas, con pleno respeto a los derechos ciudadanos. Fue leída en la Tercera Sesión del primer período ordinario del segundo año legislativo.",
    "link_documento": "https://www.congresocam.gob.mx/tercera-sesion-primer-periodo-ordinario/",
    "link_portal": "https://www.congresocam.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: tránsito | Fuente: resumen sesión 14/10/2025 | Sin número de expediente identificado en fuente directa | Subtema corregido: MOV_INF considerado→MOV_SEG (por efecto: remover vehículo que representa riesgo de seguridad, no obra de infraestructura)"
  },
  {
    "id": "CAM-2025-006",
    "fecha": "2025-06-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo para solicitar a los trece honorables ayuntamientos del Estado de Campeche la implementación de campañas permanentes y el fomento de la participación ciudadana en políticas de movilidad segura para motociclistas.",
    "resumen": "La diputada Gladys Sofía Rivera López (Morena) promovió un Punto de Acuerdo para que todos los municipios de Campeche implementen campañas permanentes de educación vial y participación ciudadana orientadas a la seguridad de motociclistas. El grupo de motociclistas es señalado como especialmente vulnerable en los registros de siniestralidad vial.",
    "link_documento": "https://www.congresocam.gob.mx/wp-content/uploads/adjuntos_sitio/PL/LXV/PUNTOS_DE_ACUERDO/PA079LXV0625.pdf",
    "link_portal": "https://www.congresocam.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | Expediente: PA/079/LXV/06/25 | Promovente: Dip. Gladys Sofía Rivera López (Morena)"
  },
  {
    "id": "CAM-2025-005",
    "fecha": "2025-06-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo para exhortar a SEDATU, SCT, Secretaría de Desarrollo Urbano Movilidad y Obras Públicas del Estado, y ayuntamientos de Champotón y Seybaplaya, a adoptar acciones necesarias para eliminar riesgos de seguridad vial en las inmediaciones del Jardín de Niños 'Lic. José Vasconcelos', la Primaria 'La Ciudad del Sol' y la Secundaria Técnica No. 19 en Champotón.",
    "resumen": "La diputada Gladys Sofía Rivera López (Morena) presentó un Punto de Acuerdo para que autoridades federales y locales actúen sobre los riesgos viales frente a tres planteles educativos del municipio de Champotón. La propuesta involucra a la Secretaría de Infraestructura, Comunicaciones y Transportes y a las autoridades municipales de Champotón y Seybaplaya.",
    "link_documento": "https://www.congresocam.gob.mx/wp-content/uploads/adjuntos_sitio/PL/LXV/PUNTOS_DE_ACUERDO/PA065LXV0625.pdf",
    "link_portal": "https://www.congresocam.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: vialidad | Expediente: PA/065/LXV/06/25 | Promovente: Dip. Gladys Sofía Rivera López (Morena)"
  },
  {
    "id": "CAM-2025-004",
    "fecha": "2025-05-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado — Decreto 86",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma a la fracción XXXVII del artículo 2 de la Ley de Movilidad y Seguridad Vial del Estado de Campeche. Modifica la definición de 'Personas de movilidad limitada' para incluir a quienes temporal o permanentemente presentan dificultad de desplazamiento por enfermedad, edad, accidente u otra condición diversa a la discapacidad.",
    "resumen": "El Congreso de Campeche reformó mediante Decreto número 86 la definición de 'Personas de movilidad limitada' en la Ley de Movilidad y Seguridad Vial. La ampliación de la definición extiende la protección legal a un espectro más amplio de personas con dificultades de desplazamiento por causas distintas a la discapacidad formal. Fue publicado en el P.O.E. No. 2406 el 13 de mayo de 2025.",
    "link_documento": "https://periodicooficial.campeche.gob.mx/",
    "link_portal": "https://www.congresocam.gob.mx/dictamenes/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado — P.O.E. No. 2406 Tercera Sección 13/05/2025 | Término búsqueda: movilidad | Decreto número 86 | Texto de Fracción XXXVII verificado en versión consolidada (municipiocampeche.gob.mx)"
  },
  {
    "id": "CAM-2025-003",
    "fecha": "2025-05-06",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Turnada a comisiones",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Propuesta para la creación de la Comisión Especial para la Defensa de los Derechos de las Personas Usuarias del Servicio Eléctrico en el Estado de Campeche en el seno de la LXV Legislatura.",
    "resumen": "El diputado José Antonio Jiménez Gutiérrez (Morena) presentó propuesta para crear una Comisión Especial dentro del Congreso dedicada a defender los derechos de los usuarios del servicio eléctrico en Campeche. Fue leída en la Segunda Sesión del Tercer Período Ordinario el 6 de mayo de 2025.",
    "link_documento": "https://www.congresocam.gob.mx/wp-content/uploads/adjuntos_sitio/SG/LXV/Gacetas/01_PRIMER_ANO_EJERCICIO/005_TERCER_PERIODO_ORDINARIO/043_GACETA_06MAYO2025.pdf",
    "link_portal": "https://www.congresocam.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: energía | Fuente: Gaceta Parlamentaria No. 43 (06/05/2025) | Nota: propuesta de organización interna del Congreso; sin expediente identificado en portal de iniciativas"
  },
  {
    "id": "CAM-2024-002",
    "fecha": "2024-10-18",
    "tipo_acto": "Minuta",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Minuta remitida por la Cámara de Senadores para reformar el artículo 28 de la Constitución Política de los Estados Unidos Mexicanos a fin de que el Estado retome el control de las vías ferroviarias para la prestación del servicio de pasajeros.",
    "resumen": "La LXV Legislatura de Campeche aprobó la Minuta enviada por el Senado que reforma el artículo 28 constitucional para restablecer el control estatal sobre las vías ferroviarias en materia de servicio de pasajeros. Campeche fue el estado número 13 en ratificar esta reforma constitucional de alcance federal.",
    "link_documento": "https://www.congresocam.gob.mx/quinta-sesion-ordinaria-4/",
    "link_portal": "https://www.congresocam.gob.mx/quinta-sesion-ordinaria-4/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | Sin número de expediente identificado en fuente directa | Fuente: resumen sesión Quinta Sesión Ordinaria 18/10/2024"
  },
  {
    "id": "CAM-2024-001",
    "fecha": "2024-10-09",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Exhorto a la CFE y a la Secretaría de Energía del Gobierno Federal para garantizar el suministro de energía eléctrica en toda la entidad y atender de manera urgente las interrupciones y afectaciones en el servicio.",
    "resumen": "El Grupo Parlamentario de Movimiento Ciudadano presentó propuesta de acuerdo para exhortar a la CFE y a la Secretaría de Energía federal a garantizar el suministro eléctrico en Campeche y prevenir interrupciones. El dictamen de la Comisión de Desarrollo Energético Sustentable fue aprobado el 18 de octubre de 2024 en la Quinta Sesión del primer período ordinario de la LXV Legislatura.",
    "link_documento": "https://www.congresocam.gob.mx/wp-content/uploads/adjuntos_sitio/PL/LXV/DICTAMENES/D_PA002LXV1024.pdf",
    "link_portal": "https://www.congresocam.gob.mx/quinta-sesion-ordinaria-4/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | Expediente: PA/002/LXV/10/24 | Dictamen: D_PA002LXV1024.pdf | Promovente: GP Movimiento Ciudadano (Fernández Montúfar y otros)"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
