const DATA = [
  {
    "id": "PUE-2026-001",
    "fecha": "2026-03-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman el segundo párrafo del artículo 114, la fracción III del artículo 115; y se adiciona un tercer párrafo al artículo 114 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-002",
    "fecha": "2026-03-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-003",
    "fecha": "2026-03-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Infraestructura y a la Secretaría de Movilidad y transporte, ambas, del Estado, a \"Carreteras de Cuota Puebla\", para que fortalezcan la planeación y gestión de la red carretera estatal de cuota",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-004",
    "fecha": "2026-03-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los Ayuntamientos del Estado para que revisen, armonicen y actualicen sus reglamentos de tránsito, movilidad y seguridad vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: movilidad"
  },
  {
    "id": "PUE-2026-005",
    "fecha": "2026-03-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a las Secretarías de Seguridad Pública y a la de Movilidad y transporte del Estado, así como a los 212 Ayuntamientos y 5 Concejos Municipales para que implementen protocolos de atención a víctimas de accidentes viales",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-006",
    "fecha": "2026-03-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar al Titular del Gobierno del Estado, para que mediante Secretarías detengan de manera temporal la ejecución del proyecto denominado Servicio Público de transporte por Cable en la ciudad de Puebla",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-007",
    "fecha": "2026-03-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte, a transparentar la información relativa a los estudios técnicos de movilidad, así como a las Secretarías de Infraestructura y de Medio Ambiente sobre el impacto del proyecto de transporte urbano",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-008",
    "fecha": "2026-02-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-009",
    "fecha": "2026-02-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar al H. Ayuntamiento del Municipio de Puebla, para que haga pública la opinión en la que se determinan las condiciones de los árboles afectados por la implementación del Servicio Público de transporte",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-010",
    "fecha": "2026-02-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a diversas Secretarías del Estado, para que den a conocer el impacto ambiental del \"Sistema de transporte por Cable\"",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-011",
    "fecha": "2026-02-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-012",
    "fecha": "2026-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 212 Ayuntamientos y a los 5 Concejos Municipales del Estado, para que programen y realicen acciones de mantenimiento, reposición y mejora de la señalética vial horizontal y vertical",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-013",
    "fecha": "2026-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte, para que dentro de las acciones de la revista vehicular 2026, realice una minuciosa inspección de todos y cada uno de los vehículos del servicio público de transporte",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-014",
    "fecha": "2026-02-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma la fracción I del artículo 105 y el segundo párrafo del artículo 110; y se adiciona el tercer párrafo al artículo 106 recorriéndose los subsecuentes de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-015",
    "fecha": "2026-02-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que exhorta a las Secretarías de Movilidad y transporte y Seguridad Pública del Estado de Puebla para que, en coordinación con el Ayuntamiento de Puebla, refuercen un esquema metropolitano de prevención de conducción de alto riesgo",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-016",
    "fecha": "2026-01-29",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla; y de la Ley Orgánica Municipal",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-017",
    "fecha": "2026-01-29",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el artículo 106 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2026-018",
    "fecha": "2026-01-29",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la persona titular de la Secretaría de Movilidad y transporte, para que, en coordinación con el SEDIF Puebla, diseñe un Programa Piloto de transporte Especializado \"Puerta a Puerta\" para personas con discapacidad",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-019",
    "fecha": "2025-12-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial; de la Ley para la Protección del Ambiente Natural y el Desarrollo Sustentable y del Código Penal del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-020",
    "fecha": "2025-12-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-021",
    "fecha": "2025-12-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado para que fortalezca las jornadas de sanitización y limpieza de las unidades del servicio público de transporte",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-022",
    "fecha": "2025-12-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte, así como al Ayuntamiento de Puebla, para que implementen las medidas preventivas necesarias en materia de seguridad vial durante el período vacacional",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-023",
    "fecha": "2025-12-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte para que realice acciones de verificación y supervisión del servicio de transporte público en el Estado",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-024",
    "fecha": "2025-12-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar al Gobierno del Estado, por conducto de la Secretaría de Movilidad y transporte, ordene la realización de un estudio integral en materia de movilidad y seguridad vial en la Vía Atlixcáyotl",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-025",
    "fecha": "2025-11-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan diversas disposiciones a la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-026",
    "fecha": "2025-11-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 212 Ayuntamientos y 5 Concejos Municipales del Estado de Puebla para que implementen la figura de \"conductor designado\" en sus municipios",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-027",
    "fecha": "2025-11-06",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones a la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-028",
    "fecha": "2025-11-06",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan el Capítulo VI denominado \"Del Certificado de Control y Procedencia Vehicular\" y los artículos 74 al 79 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-029",
    "fecha": "2025-10-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 212 Ayuntamientos y a los 5 Concejos Municipales del Estado a que adopten medidas para combatir el cambio climático y sus efectos mediante la adopción de energías renovables",
    "resumen": "Exhorto legislativo dirigido a los 212 Ayuntamientos del Estado para que adopten medidas de combate al cambio climático mediante energías renovables. Busca impulsar la transición energética en el ámbito municipal. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía"
  },
  {
    "id": "PUE-2025-030",
    "fecha": "2025-10-16",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan diversas disposiciones a la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-031",
    "fecha": "2025-10-09",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan un último párrafo al artículo 54 y el artículo 54 Bis a la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-032",
    "fecha": "2025-10-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Gobernación, para que, de manera coordinada coadyuve el cumplimiento de las normas regulatorias en el transporte de gas LP y natural",
    "resumen": "Exhorto a la Secretaría de Gobernación para garantizar el cumplimiento de las normas regulatorias en el transporte de gas LP y natural. Busca fortalecer la seguridad en la distribución de hidrocarburos. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-033",
    "fecha": "2025-10-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 212 Ayuntamientos y a los 5 Concejos Municipales del Estado y a la Secretaría de Seguridad Pública para que implementen el programa denominado \"Manual Básico de Manejo\"",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-034",
    "fecha": "2025-10-02",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman las fracciones XXXIII, XXXIV y se adiciona la XXXV al artículo 26 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-035",
    "fecha": "2025-10-02",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el último párrafo del artículo 24 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-036",
    "fecha": "2025-09-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla; y de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-037",
    "fecha": "2025-09-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado y Carreteras de Cuota para que realicen acciones de mantenimiento y mejora de la infraestructura vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-038",
    "fecha": "2025-09-18",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adiciona un segundo párrafo a la fracción VI del artículo 4 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-039",
    "fecha": "2025-09-18",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman los artículos 106 y 111 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-040",
    "fecha": "2025-09-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado y a los 212 Ayuntamientos y 5 Concejos Municipales a promover programas en los que se respeten los lugares de estacionamiento para personas con discapacidad",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para promover la accesibilidad y movilidad de grupos vulnerables. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-041",
    "fecha": "2025-09-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado para que realice una campaña de difusión en su portal electrónico sobre las obligaciones de las personas usuarias del transporte público",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-042",
    "fecha": "2025-09-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a las Secretarías de Movilidad y transporte y la de Educación Pública para que diseñen e implementen campañas permanentes de educación y cultura vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-043",
    "fecha": "2025-08-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la persona titular de la Secretaría de Movilidad y transporte y los 212 Ayuntamientos y 5 Concejos Municipales para que promuevan la colocación y mantenimiento de semáforos auditivos peatonales",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para promover la accesibilidad y movilidad de grupos vulnerables. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-044",
    "fecha": "2025-08-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman los artículos 18, 36 y 55 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-045",
    "fecha": "2025-08-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Comisión Federal de Electricidad para que adopte medidas operativas que permitan simplificar y agilizar los trámites necesarios para contratar el servicio de energía eléctrica",
    "resumen": "Exhorto a la CFE para simplificar y agilizar los trámites de contratación del servicio de energía eléctrica. Busca reducir barreras administrativas que afectan a ciudadanos y empresas. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: energía"
  },
  {
    "id": "PUE-2025-046",
    "fecha": "2025-07-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la persona titular de la Secretaría de Movilidad y transporte del Estado para que fortalezca e implemente programas integrales y colaborativos, para promover la sana convivencia en materia vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-047",
    "fecha": "2025-07-03",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman las fracciones VII, VIII y se adiciona la IX al artículo 15 de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-048",
    "fecha": "2025-06-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-049",
    "fecha": "2025-06-26",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado para implementar las acciones necesarias para garantizar los asientos reservados para personas con discapacidad en el transporte público",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para promover la accesibilidad y movilidad de grupos vulnerables. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-050",
    "fecha": "2025-06-18",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adiciona un último párrafo al artículo 106 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-051",
    "fecha": "2025-06-18",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adiciona un segundo párrafo, recorriendo los subsecuentes del artículo 128 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es garantizar la accesibilidad y movilidad de personas con discapacidad. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-052",
    "fecha": "2025-06-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que reforman el último párrafo del artículo 24 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-053",
    "fecha": "2025-06-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 217 Ayuntamientos del Estado para que en la ejecución de operativos que involucren el arrastre de motocicletas se realice el cobro del servicio de grúa en proporción al vehículo arrastrado",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-054",
    "fecha": "2025-06-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 214 Ayuntamientos y a los 3 Concejos Municipales para que emitan, aprueben y apliquen en sus respectivas jurisdicciones el Programa Vial \"Uno por Uno\"",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-055",
    "fecha": "2025-06-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte para que impulse acciones a los conductores de las diferentes plataformas digitales como Didi, Uber se apeguen estrictamente a sus reglas de operación",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular las plataformas digitales de movilidad. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-056",
    "fecha": "2025-06-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los 19 Municipios que integran la zona metropolitana para implementar acciones y estrategias a fin de impulsar un plan de educación en materia de movilidad y seguridad vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: movilidad"
  },
  {
    "id": "PUE-2025-057",
    "fecha": "2025-05-29",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta de manera respetuosa a la Secretaría de Movilidad y transportes del Estado de Puebla, a instalar señalética informativa adecuada que indique de forma clara y visible los límites de velocidad establecidos en cada vialidad",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-058",
    "fecha": "2025-05-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-059",
    "fecha": "2025-05-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta respetuosamente a la Secretaría de Movilidad y transporte del Estado de Puebla, para que proceda a la cancelación de las concesiones de las unidades del transporte público que incumplan la normatividad vigente",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-060",
    "fecha": "2025-05-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta respetuosamente a la Secretaría de Movilidad y transporte del Gobierno del Estado de Puebla y a los 212 Ayuntamientos y 5 Concejos Municipales a realizar de manera coordinada un programa de verificación de unidades del transporte público",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-061",
    "fecha": "2025-05-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adiciona un segundo párrafo al artículo 169 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-062",
    "fecha": "2025-05-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta respetuosamente a la Secretaría de Infraestructura, Comunicaciones y transportes del Gobierno Federal y a la Secretaría de Infraestructura del Estado de Puebla, para que de manera coordinada realicen diversas obras de mejora en la infraestructura carretera",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-063",
    "fecha": "2025-05-08",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-064",
    "fecha": "2025-04-30",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-065",
    "fecha": "2025-04-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta a la Secretaría de Movilidad y transporte del Gobierno del Estado a inspeccionar que las unidades de transporte público cumplan con el cupo correspondiente al vehículo",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-066",
    "fecha": "2025-04-03",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el segundo párrafo del artículo 128 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es garantizar la accesibilidad y movilidad de personas con discapacidad. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-067",
    "fecha": "2025-03-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-068",
    "fecha": "2025-03-06",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta a la Secretaría de Movilidad y transporte del Gobierno del Estado, para que en coordinación con los Ayuntamientos de Puebla, implementen programas y campañas de educación vial para personas mayores y con discapacidad",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-069",
    "fecha": "2025-03-06",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta respetuosamente a la Secretaría de Infraestructura, Comunicaciones y transportes del Gobierno Federal y al Organismo Público Descentralizado denominado Caminos y Puentes Federales de Ingresos y Servicios Conexos (CAPUFE)",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para fortalecer la infraestructura vial y carretera del estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-070",
    "fecha": "2025-02-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman diversas disposiciones de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-071",
    "fecha": "2025-02-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se exhorta respetuosamente a la Secretaría de Movilidad y transporte del Gobierno del Estado de Puebla para que implementen campañas de sensibilización sobre la prevención, atención y sanción del acoso en el transporte público",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para mejorar la seguridad vial y la cultura del tránsito en el estado. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-072",
    "fecha": "2025-02-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa de Decreto por el que se reforman, adicionan y derogan diversas disposiciones de la Ley Orgánica de la Administración Pública del Estado de Puebla; de la Ley de Movilidad y Seguridad Vial y de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-073",
    "fecha": "2025-02-06",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma la fracción IV del artículo 123 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-074",
    "fecha": "2025-01-23",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma la fracción XII del artículo 120 de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-075",
    "fecha": "2025-01-23",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el artículo 106 de Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-076",
    "fecha": "2025-01-23",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan dos párrafos al artículo 166 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es garantizar la accesibilidad y movilidad de personas con discapacidad. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-077",
    "fecha": "2025-01-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman las fracciones I y II del artículo 13 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2025-078",
    "fecha": "2025-01-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que solicita exhortar al Gobierno del Estado a través de la Secretaría de Movilidad y transportes para que incorpore la figura de observadores ciudadanos en el programa de revisión de unidades del transporte público",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-079",
    "fecha": "2024-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman la fracción V, el inciso b) de la fracción VI y se adiciona la fracción VII al artículo 123 de la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es mejorar la seguridad vial y la regulación del tránsito en el estado. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-080",
    "fecha": "2024-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se adicionan los artículos 129 Bis y 132 Bis a la Ley de Movilidad y Seguridad Vial del Estado de Puebla",
    "resumen": "Iniciativa de decreto que adiciona la Ley de Movilidad y Seguridad Vial del Estado de Puebla. Su objetivo es garantizar la accesibilidad y movilidad de personas con discapacidad. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-081",
    "fecha": "2024-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman diversas disposiciones de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-082",
    "fecha": "2024-12-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforman y adicionan diversas disposiciones de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma y adiciona la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-083",
    "fecha": "2024-11-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Seguridad Pública para establecer una mesa de trabajo con los concesionarios del transporte público de pasajeros en el Estado de Puebla para garantizar la seguridad de los usuarios",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. En trámite.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-084",
    "fecha": "2024-11-21",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el artículo 110 de la Ley de transporte del Estado de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. Aprobada en pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-085",
    "fecha": "2024-11-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a los Concejos Municipales y Ayuntamientos del Estado a proveer lo conducente respecto a cumplir con el Transitorio Tercero de la Ley de Movilidad y Seguridad Vial",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-086",
    "fecha": "2024-11-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo por el que se solicita exhortar a la Secretaría de Movilidad y transporte del Estado para que realice la aplicación del examen práctico de manejo, para la emisión de las licencias de conducir",
    "resumen": "Punto de Acuerdo que exhorta a las autoridades competentes para regular y mejorar el servicio de transporte público. La iniciativa busca atender problemáticas específicas de movilidad en el estado de Puebla. Aprobada por el pleno.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11756",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte"
  },
  {
    "id": "PUE-2024-087",
    "fecha": "2024-09-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En Trámite",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Decreto por el que se reforma el primer párrafo del artículo 62 de la Ley de transporte para el Estado Libre y Soberano de Puebla",
    "resumen": "Iniciativa de decreto que reforma la Ley de transporte del Estado de Puebla. Su objetivo es regular y fortalecer el servicio de transporte público estatal. En trámite en la Comisión de Transportes y Movilidad.",
    "link_documento": "",
    "link_portal": "https://congresopuebla.gob.mx/index.php?option=com_content&view=article&id=11755",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En Trámite | Término búsqueda: transporte"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
