const DATA = [
  {
    "id": "CHP-2026-001",
    "fecha": "2026-02-04",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMAN, ADICIONAN Y DEROGAN DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS",
    "resumen": "Reforma, adición y derogación de diversas disposiciones de la Ley de Movilidad y Transporte del Estado de Chiapas. Actualización integral del marco normativo del transporte público. Aprobada con dictamen y decreto en la LXIX Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte|movilidad | No. portal: 6 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2025-003",
    "fecha": "2025-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMAN Y ADICIONAN DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS, PRESENTADA POR LA DIPUTADA MARÍA MANDIOLA TOTORICAGUENA, INTEGRANTE DE ESTA SEXAGÉSIMA NOVENA LEGISLATURA",
    "resumen": "Iniciativa de reforma a la Ley de Movilidad y Transporte presentada por la Dip. María Mandiola Totoricaguena. Propone modificaciones al marco normativo del transporte público en Chiapas. Sin dictamen a la fecha.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte|movilidad | No. portal: 35 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2025-002",
    "fecha": "2025-05-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMAN Y ADICIONAN DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS",
    "resumen": "Reforma y adición de diversas disposiciones de la Ley de Movilidad y Transporte del Estado de Chiapas. Actualiza el marco regulatorio del transporte público en la entidad. Aprobada con dictamen y decreto.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte|movilidad | No. portal: 77 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2025-001",
    "fecha": "2025-01-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMAN Y ADICIONAN DIVERSAS DISPOSICIONES DE LA LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS; SE REFORMAN DIVERSAS DISPOSICIONES DE LA LEY QUE ESTABLECE LAS BASES DE OPERACIÓN DE LA SECRETARÍA DE SEGURIDAD DEL PUEBLO DEL ESTADO DE CHIAPAS; SE REFORMA EL SEGUNDO PÁRRAFO DEL ARTÍCULO 185 DEL CÓDIGO DE LA H",
    "resumen": "Reforma integral que modifica la Ley de Movilidad y Transporte, la Ley de Seguridad del Pueblo, el Código de Hacienda Pública y la Ley de Derechos del Estado de Chiapas. Paquete legislativo amplio vinculado al transporte público y su financiamiento. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte|movilidad | No. portal: 130 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2024-002",
    "fecha": "2024-10-17",
    "tipo_acto": "Minuta",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PROYECTO DE DECRETO POR EL QUE SE REFORMA EL PÁRRAFO CUARTO Y SE ADICIONA UN PÁRRAFO QUINTO, AL ARTÍCULO 28 DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS, EN MATERIA DE VÍAS Y TRANSPORTE FERROVIARIO",
    "resumen": "Minuta de reforma constitucional federal para regular las vías y el transporte ferroviario en el artículo 28 de la CPEUM. Fortalece el marco constitucional del transporte ferroviario en México. Aprobada por la LXIX Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte | No. portal: 179 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2024-001",
    "fecha": "2024-05-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE ADICIONA LA FRACCIÓN XVI AL ARTÍCULO 9 DE LA CONSTITUCIÓN POLÍTICA DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, PARA RECONOCER A LA MOVILIDAD DE LAS PERSONAS COMO UN DERECHO INDIVIDUAL QUE DEBE DARSE EN CONDICIONES DE SEGURIDAD, ACCESIBILIDAD, SOSTENIBILIDAD, CALIDAD E INCLUSIÓN",
    "resumen": "Reforma a la Constitución Política del Estado de Chiapas para reconocer la movilidad de las personas como un derecho individual en condiciones de seguridad, accesibilidad, sostenibilidad y calidad. Eleva el derecho a la movilidad a rango constitucional estatal. Aprobada.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 M:1 Dec:1) | Término búsqueda: movilidad | No. portal: 20 | Legislatura: LXIX"
  },
  {
    "id": "CHP-2023-002",
    "fecha": "2023-01-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE SE EXHORTA A LA ENCARGADA DE LA SECRETARÍA DE COMUNICACIONES Y TRANSPORTES DEL MUNICIPIO DE TAPACHULA Y A LA SECRETARÍA DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS, PARA QUE INFORMEN DETALLADAMENTE A ESTA SOBERANÍA LA EXPEDICIÓN DE PERMISOS DE SERVICIO DE TRANSPORTE PÚBLICO FEDERAL Y DE TRANSPORTE DE PENETRACIÓN OTOR",
    "resumen": "Exhorto a la Secretaría de Movilidad y Transporte del Estado para informar sobre permisos de transporte público federal y de penetración otorgados en Tapachula durante 2022. Busca transparencia en la concesión de rutas de transporte. Sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte|movilidad | No. portal: 185 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2023-001",
    "fecha": "2023-01-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE RESPETUOSAMENTE EL HONORABLE CONGRESO DEL ESTADO DE CHIAPAS EXHORTA A LA SECRETARÍA DE SEGURIDAD PÚBLICA Y PROTECCIÓN CIUDADANA Y AL INSTITUTO DE COMUNICACIÓN SOCIAL Y RELACIONES PÚBLICAS DEL ESTADO A REALIZAR CAMPAÑAS DE DIFUSIÓN PARA EVITAR ACCIDENTES DE TRÁNSITO, CONVOCANDO A LA POBLACIÓN A RESPETAR LOS LÍMITES DE VEL",
    "resumen": "Exhorto a la Secretaría de Seguridad Pública y al ICSRP del Estado para realizar campañas de difusión sobre seguridad vial: respeto de límites de velocidad, no uso de celular al conducir y uso de cinturón. Sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: tránsito | No. portal: 187 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-006",
    "fecha": "2022-12-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL CUAL LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, EXHORTA A LA FISCALÍA GENERAL DEL ESTADO, A LA SECRETARÍA DE SALUD, A LA SECRETARÍA DE PROTECCIÓN CIVIL, A LA SECRETARÍA DE SEGURIDAD Y PROTECCIÓN CIUDADANA Y A LOS AYUNTAMIENTOS A IMPLEMENTAR EN EL ÁMBITO DE SUS COMPETENCIAS",
    "resumen": "Exhorto a la Fiscalía General, Secretaría de Salud, Protección Civil, Seguridad Ciudadana y ayuntamientos para implementar operativos de alcoholímetro y prevenir accidentes de tránsito por conductores en estado de ebriedad. Aprobado con decreto.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: tránsito | No. portal: 188 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-005",
    "fecha": "2022-12-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, SOLICITA RESPETUOSAMENTE AL PODER EJECUTIVO FEDERAL, AL INSTITUTO NACIONAL DE LOS PUEBLOS INDÍGENAS Y A LA SECRETARÍA DE COMUNICACIONES Y TRANSPORTES, SE IMPLEMENTE EL PROGRAMA DE PAVIMENTACIÓN DE CAMINOS RURALES CON CONCRETO",
    "resumen": "Solicitud al Ejecutivo Federal, INPI y SCT para implementar el Programa de Pavimentación de Caminos Rurales para Pueblos Indígenas de Chiapas. Busca mejorar la conectividad vial en comunidades indígenas del estado. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte | No. portal: 200 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-004",
    "fecha": "2022-07-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, EXHORTA RESPETUOSAMENTE AL TITULAR DE LA SECRETARÍA DE INFRAESTRUCTURA, COMUNICACIONES Y TRANSPORTES, PARA QUE VERIFIQUE Y SUPERVISE QUE LOS TRABAJOS DE REPARACIÓN Y MANTENIMIENTO EN EL TRAMO CARRETERO ARRIAGA-TAPACHULA SEAN R",
    "resumen": "Exhorto a la SICT para supervisar la calidad de los trabajos de reparación y mantenimiento en el tramo carretero Arriaga-Tapachula. Señala irregularidades en obras de infraestructura vial federal en Chiapas. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte | No. portal: 245 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-003",
    "fecha": "2022-06-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO DE CHIAPAS, EXHORTA RESPETUOSAMENTE AL TITULAR DEL PODER EJECUTIVO FEDERAL, AL TITULAR DE LA COMISIÓN REGULADORA DE ENERGÍA Y AL TITULAR DE LA SECRETARÍA DE HACIENDA Y CRÉDITO PÚBLICO, PARA QUE ESTABLEZCAN LA TARIFA 1F A LOS MUNICIPIOS DE LA COSTA DE CHIA",
    "resumen": "Exhorto a la Comisión Reguladora de Energía y a la SHCP para establecer la Tarifa 1F a diez municipios de la Costa de Chiapas durante el verano. Busca aliviar el impacto de altas temperaturas en las tarifas eléctricas domésticas. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: energía | No. portal: 251 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-002",
    "fecha": "2022-03-30",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, EXHORTA AL PODER EJECUTIVO DEL ESTADO DE CHIAPAS Y A LOS AYUNTAMIENTOS DE CHIAPAS A REFORMAR LOS REGLAMENTOS DE TRÁNSITO PARA INCLUIR MEDIDAS DE IDENTIFICACIÓN A LOS CONDUCTORES DE MOTOCICLETAS",
    "resumen": "Exhorto al Ejecutivo estatal y a los ayuntamientos para reformar reglamentos de tránsito e incluir medidas de identificación para conductores de motocicletas. Busca mejorar la seguridad vial y el control de motos. Sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: tránsito | No. portal: 284 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2022-001",
    "fecha": "2022-03-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO DE CHIAPAS, EXHORTA RESPETUOSAMENTE AL TITULAR DE LA SECRETARÍA DE INFRAESTRUCTURA, COMUNICACIONES Y TRANSPORTES, PARA QUE SOLICITE A LA EMPRESA CONCESIONARIA DE AUTOPISTAS DEL SURESTE, S.A. DE C.V., REVISAR Y RECONSIDERAR LOS AUMENTOS DE TARIFAS DE PEAJE",
    "resumen": "Exhorto a la SICT para que solicite a la concesionaria Autopistas del Sureste reconsiderar los aumentos de tarifas de peaje en tramos carreteros de Chiapas. Protege a usuarios de carreteras de incrementos en costos de peaje. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte | No. portal: 293 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2021-003",
    "fecha": "2021-11-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DE ESTE HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, EXHORTA RESPETUOSAMENTE A LA SECRETARÍA DE COMUNICACIONES Y TRANSPORTES, PARA QUE EN EL ÁMBITO DE SU RESPECTIVA COMPETENCIA, DE SEGUIMIENTO A LOS PROBLEMAS RELACIONADOS A LOS HUNDIMIENTOS Y SOCAVONES QUE PRESENTA LA CARRET",
    "resumen": "Exhorto a la SCT para dar seguimiento a hundimientos y socavones en la carretera MEX-200, con 236.5 km en mal estado en Chiapas. Exige atención a infraestructura vial federal deteriorada en el estado. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte | No. portal: 325 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2021-002",
    "fecha": "2021-10-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR MEDIO DEL CUAL EXHORTA RESPETUOSAMENTE A LA COMISIÓN FEDERAL DE ELECTRICIDAD A REALIZAR LAS ACCIONES NECESARIAS DE MANTENIMIENTO, Y EN SU CASO, LA CREACIÓN DE INFRAESTRUCTURA ELÉCTRICA NECESARIA PARA GARANTIZAR LA EFICACIA Y LA EFICIENCIA EN EL SERVICIO DEL SUMINISTRO DE ENERGÍA ELÉCTRICA DE LOS HABITANTES DEL FRACCIONAMIENTO V",
    "resumen": "Exhorto a la CFE para realizar mantenimiento e instalar infraestructura eléctrica en el fraccionamiento Villas del Sol, municipio de Solidaridad, Quintana Roo. Atiende déficit de servicio eléctrico en una zona urbana. Sin dictamen; nota: el destino del exhorto es Quintana Roo.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: energía | No. portal: 327 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2021-001",
    "fecha": "2021-10-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA OCTAVA LEGISLATURA DE ESTE HONORABLE CONGRESO DEL ESTADO DE CHIAPAS, EXHORTA RESPETUOSAMENTE A LA CÁMARA DE DIPUTADOS DEL HONORABLE CONGRESO DE LA UNIÓN, A INCORPORAR EN LA REFORMA CONSTITUCIONAL EN MATERIA DE ENERGÍA ELÉCTRICA UNA PERSPECTIVA REGIONAL QUE CONTRIBUYA AL FORTALECIMIENTO DE LAS CONDICIONES EC",
    "resumen": "Exhorto a la Cámara de Diputados para incorporar una perspectiva regional del sureste mexicano en la reforma constitucional de energía eléctrica. Busca que la reforma energética nacional beneficie equitativamente a Chiapas y el sureste. Sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: energía | No. portal: 332 | Legislatura: LXVIII"
  },
  {
    "id": "CHP-2020-006",
    "fecha": "2020-11-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA SÉPTIMA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS EXHORTA RESPETUOSAMENTE AL EJECUTIVO FEDERAL PARA QUE INSTRUYA A LA SECRETARÍA DE HACIENDA Y CRÉDITO PÚBLICO Y A LA SECRETARÍA DE COMUNICACIONES Y TRANSPORTES PARA QUE LIBEREN Y DESTINEN RECURSOS ECONÓMICOS Y MATERIALES PARA R",
    "resumen": "Exhorto al Ejecutivo Federal para liberar recursos de la SHCP y SCT destinados a restablecer vías carreteras afectadas por fenómenos hidrometeorológicos en Chiapas. Respuesta legislativa a daños de infraestructura vial por desastres naturales. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:0 Dec:1) | Término búsqueda: transporte | No. portal: 51 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2020-005",
    "fecha": "2020-11-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR MEDIO DEL CUAL LA SEXAGÉSIMA SÉPTIMA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO, EXHORTA RESPETUOSAMENTE AL TITULAR DE LA SECRETARÍA DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS, PARA QUE EN EL ÁMBITO DE SU RESPECTIVA COMPETENCIA INSTRUYA A LOS CONCESIONARIOS DEL SERVICIO PÚBLICO DE TRANSPORTE DEL ESTADO, EL USO DE CUBREB",
    "resumen": "Exhorto a la Secretaría de Movilidad y Transporte de Chiapas para que los concesionarios del transporte público implementen el uso obligatorio de cubrebocas durante la pandemia. Medida sanitaria en el transporte público. Sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte|movilidad | No. portal: 53 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2020-003",
    "fecha": "2020-10-27",
    "tipo_acto": "Minuta",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "MINUTA PROYECTO DE DECRETO POR EL QUE SE REFORMAN DIVERSAS DISPOSICIONES DE LA CONSTITUCIÓN POLÍTICA DE LOS ESTADOS UNIDOS MEXICANOS, EN MATERIA DE MOVILIDAD Y SEGURIDAD VIAL",
    "resumen": "Minuta de reforma constitucional federal en materia de movilidad y seguridad vial, ratificada por el Congreso de Chiapas. Eleva a rango constitucional el derecho a la movilidad y establece principios de seguridad vial. Aprobada.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: movilidad | No. portal: 59 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2020-004",
    "fecha": "2020-10-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE EXPIDE LA LEY DE FOMENTO PARA EL USO DE LA BICICLETA Y PROTECCIÓN AL CICLISTA DEL ESTADO DE CHIAPAS",
    "resumen": "Expide la Ley de Fomento para el Uso de la Bicicleta y Protección al Ciclista del Estado de Chiapas. Crea un marco de protección y promoción de la movilidad activa en bicicleta. Aprobada con decreto.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: ciclista | No. portal: 62 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2020-002",
    "fecha": "2020-10-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS",
    "resumen": "Expedición de la Ley de Movilidad y Transporte del Estado de Chiapas, que crea el nuevo marco normativo integral del transporte público en la entidad. Aprobada con dictamen y decreto en la LXVII Legislatura, sustituyendo la antigua Ley de Transportes.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: transporte|movilidad | No. portal: 63 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2020-001",
    "fecha": "2020-05-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA SÉPTIMA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO DE CHIAPAS EXHORTA AL TITULAR DEL PODER EJECUTIVO FEDERAL PARA QUE INSTRUYA AL TITULAR DE LA COMISIÓN FEDERAL DE ELECTRICIDAD (CFE) PARA QUE, EN SOLIDARIDAD CON LA CRISIS GENERADA POR LA PANDEMIA DE COVID-19, OTORGUE UNA CONDONACIÓN TOTAL O PARCIAL DEL C",
    "resumen": "Punto de acuerdo para que la CFE condone total o parcialmente el cobro de energía eléctrica doméstica durante la pandemia de COVID-19. Medida de solidaridad ante la crisis económica de los hogares chiapanecos. Aprobado.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: cfe | No. portal: 123 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2019-001",
    "fecha": "2019-10-17",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "ENE_REG",
    "extracto": "PUNTO DE ACUERDO POR EL QUE SE EXHORTA RESPETUOSAMENTE AL TITULAR DEL PODER EJECUTIVO FEDERAL PARA QUE GENERE UN DECRETO DE ESTIMULOS FISCALES PARA LA REGIÓN FRONTERIZA SUR; ASI MISMO SE EXHORTA AL TITULAR DE LA SECRETARÍA DE ENERGÍA, AL TITULAR DE LA COMISIÓN REGULADORA DE ENERGÍA Y AL TITULAR DE LA COMISIÓN FEDERAL DE ELECTRICIDAD A IMPLEMENTAR E",
    "resumen": "Exhorto al Ejecutivo Federal y a la SENER, CRE y CFE para establecer estímulos fiscales y esquemas de subsidio de energía en la región fronteriza sur de Chiapas. Vincula política energética con desarrollo económico de la zona. Aprobado con decreto.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado (docs: I:1 D:1 Dec:1) | Término búsqueda: energía | No. portal: 194 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2018-003",
    "fecha": "2018-12-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE SE EXHORTA A LA SECRETARÍA DE HACIENDA Y CRÉDITO PÚBLICO, COMISIÓN REGULADORA DE ENERGÍA Y LA COMISIÓN FEDERAL DE ELECTRICIDAD A PROPONER ACCIONES QUE GARANTICEN LA CONDONACIÓN TOTAL DE LOS ADEUDOS A LOS USUARIOS FINALES DEL SERVICIO DOMÉSTICO DE ENERGÍA ELÉCTRICA DE DIVERSOS MUNICIPIOS DE CHIAPAS",
    "resumen": "Exhorto a la SHCP, la Comisión Reguladora de Energía y la CFE para condonar los adeudos de energía eléctrica doméstica en municipios de Chiapas. Busca aliviar la carga financiera de usuarios con deudas acumuladas con la CFE. Presentada sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: energía | No. portal: 275 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2018-002",
    "fecha": "2018-06-21",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE LEY DE MOVILIDAD Y TRANSPORTE DEL ESTADO DE CHIAPAS",
    "resumen": "Iniciativa para expedir una nueva Ley de Movilidad y Transporte del Estado de Chiapas, que modernizara el marco regulatorio del transporte público estatal. Primera versión de la ley, presentada ante la LXVII Legislatura sin dictamen.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte|movilidad | No. portal: 19 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2018-001",
    "fecha": "2018-05-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMA LA FRACCIÓN X DEL ARTÍCULO 6 DE LA LEY DE TRANSPORTES DEL ESTADO DE CHIAPAS, EN MATERIA DE REGISTRO DE MOTOCICLETAS",
    "resumen": "Reforma la fracción X del artículo 6 de la Ley de Transportes para regular el registro de motocicletas. Amplía el marco de registro vehicular en el transporte. Presentada ante la LXVII Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte | No. portal: 21 | Legislatura: LXVII"
  },
  {
    "id": "CHP-2017-003",
    "fecha": "2017-11-16",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "PUNTO DE ACUERDO POR EL QUE LA SEXAGÉSIMA SEXTA LEGISLATURA DEL HONORABLE CONGRESO DEL ESTADO LIBRE Y SOBERANO DE CHIAPAS, EXHORTA RESPETUOSAMENTE A LA SECRETARÍA DE TRANSPORTES DEL ESTADO DE CHIAPAS, A IMPLEMENTAR UN CENSO DE EMPADRONAMIENTO A FIN DE QUE GARANTICE LA SEGURIDAD DE LAS Y LOS USUARIOS DE TRASPORTES PÚBLICO EN EL ESTADO, EN LA MODALID",
    "resumen": "Exhorto a la Secretaría de Transportes para implementar un censo de empadronamiento de operadores de taxi, a fin de garantizar la seguridad de los usuarios. Presentada ante la LXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte | No. portal: 68 | Legislatura: LXVI"
  },
  {
    "id": "CHP-2017-002",
    "fecha": "2017-10-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE ADICIONA EL ARTÍCULO 59 DE LA LEY DE TRANSPORTES DEL ESTADO DE CHIAPAS",
    "resumen": "Adiciona el artículo 59 a la Ley de Transportes de Chiapas para fortalecer la regulación del servicio de transporte público. Presentada ante la LXVI Legislatura sin dictamen visible.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte | No. portal: 84 | Legislatura: LXVI"
  },
  {
    "id": "CHP-2017-001",
    "fecha": "2017-06-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE INSTITUYE EL 21 DE OCTUBRE, COMO EL \"DÍA ESTATAL DEL AHORRO DE ENERGÍA\"",
    "resumen": "Iniciativa para instituir el 21 de octubre como Día Estatal del Ahorro de Energía en Chiapas. Busca crear conciencia sobre eficiencia energética mediante una fecha conmemorativa oficial. Presentada ante la LXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: energía | No. portal: 116 | Legislatura: LXVI"
  },
  {
    "id": "CHP-2016-002",
    "fecha": "2016-05-31",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE DE REFORMAN LA FRACCIÓN I Y EL INCISO F) DE LA FRACCIÓN II DEL ARTICULO 50 TER DE LA LEY DE TRANSPORTES DEL ESTADO DE CHIAPAS",
    "resumen": "Reforma específica a los artículos 50 Ter de la Ley de Transportes, en materia de concesiones de transporte público. Presentada ante la LXVI Legislatura sin dictamen visible.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte | No. portal: 208 | Legislatura: LXVI"
  },
  {
    "id": "CHP-2016-001",
    "fecha": "2016-02-03",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "INICIATIVA DE DECRETO POR EL QUE SE REFORMAN DIVERSAS DISPOSICIONES DE LA LEY DE TRANSPORTES DEL ESTADO DE CHIAPAS",
    "resumen": "Reforma a diversas disposiciones de la Ley de Transportes del Estado de Chiapas. Modifica el marco regulatorio del transporte en la entidad. Presentada ante la LXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://web.congresochiapas.gob.mx/trabajo-legislativo/trabajo-legislativo",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada (docs: I:1 D:0 Dec:0) | Término búsqueda: transporte | No. portal: 242 | Legislatura: LXVI"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
