const DATA = [
  {
    "id": "COL-2026-003",
    "fecha": "2026-03-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Pendiente",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Adiciona el inciso m) a la fracción V del artículo 27 de la Ley de Movilidad Sustentable para el Estado de Colima. Suscrita por la Dip. María Cristina Lupién Ventura y el Dip. José Israel González Mendoza de Movimiento Ciudadano.",
    "resumen": "Reforma puntual de Movimiento Ciudadano que agrega un nuevo inciso m) al artículo 27, fracción V de la Ley de Movilidad Sustentable de Colima. El artículo 27 de dicha ley regula obligaciones y derechos de los sujetos del sistema de movilidad; la adición de un nuevo inciso incorpora una categoría o supuesto normativo no previsto actualmente. Pendiente de dictaminación en las comisiones de Desarrollo Urbano y Estudios Legislativos.",
    "link_documento": "https://congresocol.gob.mx/web/Sistema/uploads/Iniciativas/INICIATIVA%20REFORMA%20LEY%20DE%20MOVILIDAD%20DIPUTADOS%20MC.pdf",
    "link_portal": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Pendiente | Término búsqueda: movilidad | Subtema asignado por art. 27 Ley Movilidad Sustentable; requiere verificación de PDF"
  },
  {
    "id": "COL-2026-002",
    "fecha": "2026-02-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Pendiente",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma y adiciona diversos artículos de la Ley de Movilidad Sustentable para el Estado de Colima. Suscrita por las Diputadas Hilda Lizette Moreno Ceballos y Betzaida Luz Alondra Pinzón Carreto y el Diputado Arnoldo Ochoa González del Grupo Parlamentario del PRI.",
    "resumen": "Reforma amplia a la Ley de Movilidad Sustentable de Colima que modifica y adiciona múltiples artículos, impulsada por el bloque PRI en febrero de 2026. La reforma de 'diversos artículos' sugiere cambios estructurales al régimen de movilidad estatal, posiblemente actualizando concesiones, tarifas o infraestructura de transporte público. Pendiente de dictaminación en la Comisión de Desarrollo Urbano, Medio Ambiente y Movilidad.",
    "link_documento": "https://congresocol.gob.mx/web/Sistema/uploads/Iniciativas/INIC%20DE%20REFORMA%20A%20LA%20LEY%20DE%20MOVILIDAD%20SUSTENTABLE%20.pdf",
    "link_portal": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Pendiente | Término búsqueda: movilidad | Fecha aproximada: mes de presentación | Subtema asignado por contexto de ley reformada; requiere verificación de PDF"
  },
  {
    "id": "COL-2026-001",
    "fecha": "2026-01-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Pendiente",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Expide la Ley de Cambio Climático para el Estado de Colima. Iniciativa suscrita por el Dip. Jaime Enrique Sotelo García y la coalición gobernante (PVEM, Morena, PT y PNAL). Turnada a las comisiones de Desarrollo Urbano Medio Ambiente y Movilidad y Estudios Legislativos y Puntos Constitucionales.",
    "resumen": "Iniciativa para expedir la primera Ley de Cambio Climático estatal de Colima, creando el marco normativo para enfrentar el calentamiento global. Las leyes de cambio climático estatales típicamente incorporan mandatos de transición energética, metas de energía renovable y mecanismos de reducción de emisiones, lo que la clasifica principalmente como ENE_REG. La coalición gobernante (PVEM-Morena-PT-PNAL) la impulsa con mayoría, lo que aumenta sus posibilidades de aprobación.",
    "link_documento": "https://congresocol.gob.mx/web/Sistema/uploads/Iniciativas/INICIATIVA%20%20LEY%20DE%20CAMBIO%20%20CLIMATICO%20PARA%20EL%20ESTADO.pdf",
    "link_portal": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Pendiente | Término búsqueda: movilidad (comisión receptora) | Fecha aproximada: mes de presentación | PDF accesible pero no legible en visor del navegador"
  },
  {
    "id": "COL-2025-001",
    "fecha": "2025-09-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Pendiente",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma el artículo 63 de la Ley de Movilidad Sustentable del Estado de Colima. Presentada por el Grupo Parlamentario del PRI (Diputado y Diputadas integrantes). Turnada a las comisiones de Desarrollo Urbano Medio Ambiente y Movilidad y Estudios Legislativos.",
    "resumen": "Iniciativa del PRI que reforma el artículo 63 de la Ley de Movilidad Sustentable de Colima, norma que regula el sistema de transporte y movilidad en el estado. Sin acceso al PDF, el artículo 63 de dicha ley podría versar sobre operadores de transporte público, infraestructura o disposiciones de cumplimiento. Pendiente de dictaminación en las comisiones correspondientes.",
    "link_documento": "https://congresocol.gob.mx/web/Sistema/uploads/Iniciativas/INICIATIVA%20DIP%20BETZAIDA.pdf",
    "link_portal": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Pendiente | Término búsqueda: movilidad | Fecha aproximada: mes de presentación (día exacto no disponible en portal) | Subtema asignado por comisión receptora; requiere verificación de PDF"
  },
  {
    "id": "COL-2024-002",
    "fecha": "2024-11-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Decreto",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "ENE_REG",
    "extracto": "Adiciona el Capítulo IX 'DE LOS IMPUESTOS ECOLÓGICOS' al Título Primero de la Ley de Hacienda del Estado de Colima, creando doce nuevos artículos (41 Z BIS 16 al 41 Z BIS 27). Presentada por la Comisión de Desarrollo Urbano, Medio Ambiente y Movilidad; aprobada como DECRETO 34.",
    "resumen": "Reforma a la Ley de Hacienda que introduce un capítulo específico de impuestos ecológicos con doce nuevos artículos que gravan actividades con impacto ambiental, potencialmente incluyendo combustibles fósiles y emisiones contaminantes. La iniciativa fue presentada por la propia Comisión de Desarrollo Urbano, Medio Ambiente y Movilidad, señal de prioridad legislativa, y fue aprobada como DECRETO 34. Crea un marco fiscal para internalizar costos ambientales, clave para la transición energética estatal.",
    "link_documento": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "link_portal": "",
    "fuente_verificada": "No",
    "notas": "Estatus portal: DECRETO 34 | Término búsqueda: ecológico | Subtema principal ENE_TAR por efecto fiscal; ENE_REG como secundario por el marco regulatorio que establece | PDF de decreto no disponible en enlace directo"
  },
  {
    "id": "COL-2024-001",
    "fecha": "2024-10-16",
    "tipo_acto": "Minuta",
    "estatus": "Decreto",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_TP",
    "extracto": "Minuta con Proyecto por el que se reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la CPEUM en materia de Vías y Transporte Ferroviario. Turnada el 16 de octubre de 2024; aprobada como DECRETO 3.",
    "resumen": "Ratificación estatal de reforma constitucional federal que modifica el artículo 28 de la CPEUM para regular las vías y el transporte ferroviario. La LXI Legislatura de Colima aprobó la minuta —DECRETO 3— incorporando el marco federal de infraestructura ferroviaria al ordenamiento constitucional. Aunque es ratificación de iniciativa federal, tiene relevancia para la planeación de conectividad intermodal en el estado.",
    "link_documento": "https://congresocol.gob.mx/web/www/gaceta/index.php?idt=iniciativas",
    "link_portal": "",
    "fuente_verificada": "No",
    "notas": "Estatus portal: DECRETO 3 | Término búsqueda: transporte | PDF de decreto no disponible en enlace directo"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
