const DATA = [
  {
    "id": "JAL-2026-016",
    "fecha": "2026-03-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, uno de los más recientes de la LXIV Legislatura.",
    "resumen": "El Congreso emite exhorto sobre transporte público colectivo estatal. La iniciativa es de las más recientes registradas en el portal INFOLEJ al momento de la búsqueda. El contenido específico requiere verificación en el portal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-015",
    "fecha": "2026-03-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, presentado en marzo de 2026.",
    "resumen": "El Congreso emite exhorto sobre transporte público en el inicio del período de sesiones de marzo 2026. La iniciativa mantiene la supervisión parlamentaria sobre el sistema de transporte colectivo estatal. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-014",
    "fecha": "2026-02-26",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre un Plan Integral relacionado con el sistema de transporte o movilidad en Jalisco; descripción completa no disponible.",
    "resumen": "El Congreso aprueba o discute un punto de acuerdo relacionado con un Plan Integral de movilidad o transporte. La descripción parcial disponible en el portal sugiere un instrumento de planeación más amplio que un exhorto puntual. Requiere verificación en el portal para determinar el alcance y autoridades destinatarias.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Descripción cortada en portal; clasificación provisional"
  },
  {
    "id": "JAL-2026-012",
    "fecha": "2026-02-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa al marco normativo del transporte público del Estado de Jalisco, febrero 2026.",
    "resumen": "La legislatura propone una reforma al sistema normativo del transporte público estatal. La iniciativa modifica disposiciones sobre operación, concesión o regulación del transporte colectivo. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2026-013",
    "fecha": "2026-02-17",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, presentado a mediados de febrero de 2026.",
    "resumen": "El Congreso emite exhorto en materia de transporte público durante la segunda semana de sesiones de febrero 2026. La iniciativa atiende problemas del sistema de transporte colectivo del estado. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-010",
    "fecha": "2026-02-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Transporte de Jalisco, febrero 2026.",
    "resumen": "La legislatura propone una reforma al marco normativo del transporte público estatal. La iniciativa actualiza disposiciones sobre la operación del transporte colectivo en el estado. Fue presentada junto con otras reformas de movilidad en el período de sesiones de febrero 2026.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2026-011",
    "fecha": "2026-02-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Reforma legislativa sobre transporte público y movilidad activa en Jalisco, segunda reforma del 13 de febrero de 2026.",
    "resumen": "La legislatura propone una segunda reforma de la misma sesión que integra transporte público y movilidad activa. La iniciativa puede establecer obligaciones de integración intermodal en el sistema de transporte colectivo. Es parte del paquete legislativo de movilidad de febrero 2026.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2026-009",
    "fecha": "2026-02-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, presentado en febrero de 2026.",
    "resumen": "El Congreso emite exhorto sobre transporte público en el período de sesiones de febrero 2026. La iniciativa continúa el patrón de supervisión legislativa del sistema de transporte colectivo estatal. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-007",
    "fecha": "2026-01-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de infracciones de tránsito, con propuesta de incentivo o beneficio para conductores con buen historial de cumplimiento vial.",
    "resumen": "El Congreso propone un exhorto para establecer un mecanismo de incentivos a conductores que mantengan un historial limpio de infracciones de tránsito. La iniciativa busca complementar el esquema sancionatorio con un enfoque positivo de cumplimiento vial. Tiene potencial impacto en la cultura vial y en la recaudación por infracciones.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito"
  },
  {
    "id": "JAL-2026-008",
    "fecha": "2026-01-28",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo relacionado con obras o trabajos de la CFE (Comisión Federal de Electricidad) con impacto en el suministro eléctrico en Jalisco.",
    "resumen": "El Congreso emite un exhorto vinculado a acciones de la CFE en el estado, posiblemente referente a interrupciones del servicio, obras de infraestructura eléctrica o tarifas. El registro apareció en la búsqueda de movilidad pero el contenido corresponde al sector energético. Requiere verificación adicional para determinar el tipo exacto de exhorto a la CFE.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Subtema corregido: movilidad→ENE_TAR (contenido sobre CFE electricidad, no transporte)"
  },
  {
    "id": "JAL-2026-006",
    "fecha": "2026-01-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la SCT sobre infraestructura vial o carretera en Jalisco, enero 2026.",
    "resumen": "El Congreso exhorta a la SCT federal a atender necesidades de infraestructura vial en el estado al inicio de 2026. La iniciativa mantiene el patrón de supervisión parlamentaria sobre la red federal de carreteras. El tramo o problema específico requiere verificación en el portal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-005",
    "fecha": "2026-01-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa que modifica el artículo 391 de la Ley de Movilidad y Transporte del Estado de Jalisco sobre el sistema de transporte público.",
    "resumen": "La reforma modifica disposiciones específicas de la Ley de Movilidad y Transporte de Jalisco relativas al transporte público. Los cambios en el artículo 391 pueden involucrar la regulación de concesiones, tarifas o requisitos operativos de los prestadores de servicio. Representa una de las reformas legislativas más recientes en materia de transporte público del estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2026-004",
    "fecha": "2026-01-16",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público de Jalisco, presentado el 16 de enero de 2026.",
    "resumen": "El Congreso emite exhorto sobre transporte público dos días después del bloque del 14 de enero. La iniciativa continúa la agenda legislativa de inicio de año en materia de transporte colectivo. El contenido requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-001",
    "fecha": "2026-01-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, presentado en la primera semana de actividades de enero 2026.",
    "resumen": "El Congreso inicia el año legislativo 2026 con exhortos en materia de transporte público. La iniciativa forma parte de un bloque de tres puntos de acuerdo sobre transporte presentados el 14 de enero de 2026. El contenido específico requiere verificación en el portal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-002",
    "fecha": "2026-01-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, segundo del bloque del 14 de enero de 2026.",
    "resumen": "El Congreso emite un segundo exhorto en materia de transporte público en la primera sesión de 2026. La iniciativa forma parte de un conjunto de puntos de acuerdo que abordan distintas aristas del transporte colectivo en el estado. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2026-003",
    "fecha": "2026-01-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, tercero del bloque del 14 de enero de 2026.",
    "resumen": "Tercer exhorto del bloque de enero 2026 sobre transporte público estatal. La densidad de iniciativas sobre transporte público en esta fecha sugiere una discusión amplia sobre el sistema de transporte colectivo. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-059",
    "fecha": "2025-11-21",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma legislativa que modifica la Ley de Movilidad y Transporte con énfasis en transporte público y seguridad vial en Jalisco.",
    "resumen": "La legislatura propone una reforma que articula el régimen del transporte público con normas de seguridad vial. La iniciativa puede abordar responsabilidades de operadores ante accidentes, sistemas de monitoreo de flota o protocolos de emergencia. Cierra el ciclo legislativo de reformas de movilidad de noviembre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-056",
    "fecha": "2025-11-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ELEC",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público con componentes de electromovilidad o vehículos eléctricos en Jalisco.",
    "resumen": "El Congreso emite exhorto que vincula la modernización del transporte público con la introducción de vehículos eléctricos o electromovilidad. La iniciativa impulsa la transición energética en la flota de transporte colectivo del estado. Es relevante en el contexto de la descarbonización del transporte como política de movilidad sostenible.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-057",
    "fecha": "2025-11-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma legislativa que modifica disposiciones sobre movilidad activa integrada con el transporte público en el Estado de Jalisco.",
    "resumen": "La legislatura propone una reforma que fortalece la movilidad activa en articulación con el sistema de transporte público. La iniciativa puede incluir la regulación de cicloestaciones, corredores peatonales seguros o criterios de diseño incluyente en terminales de transporte. Fue presentada en el intenso período legislativo de noviembre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-058",
    "fecha": "2025-11-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Transporte del Estado de Jalisco, segunda reforma del 13 de noviembre de 2025.",
    "resumen": "La legislatura aprueba una segunda reforma al marco legal del transporte público en la misma sesión del 13 de noviembre. La alta densidad de reformas en este período sugiere un proceso amplio de actualización del marco normativo de movilidad. El contenido específico requiere verificación en el portal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-055",
    "fecha": "2025-11-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Transporte del Estado de Jalisco, noviembre 2025.",
    "resumen": "La legislatura propone una reforma al marco legal del transporte público del estado. La iniciativa modifica disposiciones sobre la operación o regulación del sistema de transporte colectivo. Fue presentada justo antes del período intenso de reformas de movilidad de noviembre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-053",
    "fecha": "2025-11-03",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa en materia de seguridad vial que modifica disposiciones sobre infracciones, sanciones o prevención de accidentes en Jalisco.",
    "resumen": "La legislatura propone una reforma al marco normativo de seguridad vial del estado. La iniciativa puede incluir nuevas infracciones, ajuste de sanciones o programas de prevención de accidentes de tránsito. Es parte del esfuerzo continuo de actualización normativa en materia de seguridad en las vialidades.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-054",
    "fecha": "2025-11-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público de Jalisco, presentado en noviembre de 2025.",
    "resumen": "El Congreso emite exhorto sobre transporte público durante el período ordinario de sesiones de noviembre 2025. La iniciativa atiende problemas específicos del sistema de transporte colectivo del estado. El detalle del contenido requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-052",
    "fecha": "2025-10-21",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre infraestructura vial o carretera, dirigido a la SCT federal respecto a vías en Jalisco.",
    "resumen": "El Congreso exhorta a la SCT federal a dar atención a la infraestructura carretera del estado. La iniciativa refleja la gestión continua del Congreso ante el gobierno federal en materia de caminos y carreteras. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-051",
    "fecha": "2025-10-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Registro encontrado bajo búsqueda de movilidad; descripción completa no disponible en resultados de búsqueda del portal INFOLEJ.",
    "resumen": "Iniciativa registrada en el portal INFOLEJ bajo el término movilidad. El contenido específico requiere verificación directa en el portal para determinar el alcance exacto y la clasificación definitiva. Se clasificó provisionalmente como MOV_TP por contexto de búsqueda.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Descripción requiere verificación en portal"
  },
  {
    "id": "JAL-2025-050",
    "fecha": "2025-10-15",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa que modifica el artículo 391 u otras disposiciones de la Ley de Movilidad y Transporte del Estado de Jalisco.",
    "resumen": "La reforma modifica artículos de la legislación de movilidad y transporte del estado para actualizar el marco regulatorio del transporte público. Los cambios pueden afectar concesiones, obligaciones de operadores o derechos de usuarios del transporte. Es parte del proceso continuo de actualización normativa en materia de movilidad.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-048",
    "fecha": "2025-10-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa que modifica el marco normativo de infraestructura vial en el Estado de Jalisco.",
    "resumen": "La legislatura presenta una reforma al marco normativo de infraestructura vial del estado. La iniciativa puede modificar criterios de diseño, responsabilidades de mantenimiento o procesos de planeación vial. Complementa los exhortos parlamentarios hacia la SCT en materia de infraestructura carretera.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-049",
    "fecha": "2025-10-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la SCT federal sobre infraestructura vial o carretera en Jalisco.",
    "resumen": "El Congreso exhorta a la SCT a atender necesidades de infraestructura vial en el estado. La iniciativa puede referirse a tramos específicos con daños, en obras o con proyectos pendientes. Es parte del ejercicio sistemático de supervisión legislativa sobre la red federal de carreteras.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-047",
    "fecha": "2025-10-06",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_INF",
    "extracto": "Punto de Acuerdo sobre transporte público e infraestructura vial relacionada en municipios de Jalisco.",
    "resumen": "El Congreso emite exhorto que vincula la mejora del transporte público con la adecuación de infraestructura vial asociada, como paradas, terminales o vialidades de acceso. La iniciativa reconoce la interdependencia entre la operación del transporte y la infraestructura que lo soporta. Fue presentado en el período de sesiones de octubre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-044",
    "fecha": "2025-09-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre un programa de la SCT federal relacionado con el transporte en Jalisco.",
    "resumen": "El Congreso exhorta a la SCT federal a implementar o dar seguimiento a un programa específico de transporte en el estado. La iniciativa vincula la agenda legislativa estatal con programas federales de transporte. El detalle del programa específico requiere verificación en el portal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-045",
    "fecha": "2025-09-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa sobre movilidad activa que modifica disposiciones de la ley estatal para fortalecer derechos de ciclistas y peatones.",
    "resumen": "La legislatura propone una reforma centrada en el fortalecimiento de la movilidad activa como sistema de transporte. La iniciativa puede modificar obligaciones municipales de infraestructura ciclista, peatonal o reglas de preferencia de paso. Es parte del impulso normativo a la movilidad no motorizada de septiembre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-046",
    "fecha": "2025-09-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el horario de operación del SITEUR (Sistema de Tren Eléctrico Urbano) de la Zona Metropolitana de Guadalajara.",
    "resumen": "El Congreso exhorta al SITEUR a modificar o ampliar el horario de operación del sistema de tren eléctrico urbano de la ZMG. La iniciativa busca mejorar la accesibilidad temporal del transporte masivo para trabajadores en horarios nocturnos o de madrugada. Es una demanda recurrente de usuarios del sistema metropolitano.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-043",
    "fecha": "2025-09-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta a las autoridades del Área Metropolitana de Guadalajara (AMG) a realizar trabajos de bacheo en las vialidades deterioradas.",
    "resumen": "El Congreso exhorta al AMG o a los municipios metropolitanos a ejecutar trabajos de bacheo y mantenimiento en vialidades en mal estado. El deterioro de la infraestructura vial urbana es un problema recurrente que afecta la seguridad y los vehículos de los ciudadanos. La iniciativa busca coordinar la respuesta metropolitana ante el deterioro de las calles.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad"
  },
  {
    "id": "JAL-2025-038",
    "fecha": "2025-09-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte público de Jalisco, presentado en septiembre de 2025.",
    "resumen": "El Congreso emite exhorto sobre el sistema de transporte público durante la intensa semana legislativa de septiembre 2025. La iniciativa atiende problemas del transporte colectivo estatal. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-039",
    "fecha": "2025-09-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma legislativa que modifica disposiciones de transporte público y seguridad vial en la legislación de Jalisco.",
    "resumen": "La legislatura propone una reforma que vincula el transporte público con normas de seguridad vial. La iniciativa puede abordar condiciones de operación de unidades de transporte, capacitación de operadores o protocolos de seguridad. Fue presentada en el período intenso de reformas de movilidad de septiembre 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-040",
    "fecha": "2025-09-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público de Jalisco, septiembre 2025.",
    "resumen": "El Congreso emite exhorto sobre el transporte público estatal en el contexto de la semana legislativa de mayor actividad en movilidad del año. La iniciativa atiende aspectos del servicio de transporte colectivo. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-041",
    "fecha": "2025-09-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el servicio de transporte público en Jalisco, presentado en el período de sesiones de septiembre 2025.",
    "resumen": "El Congreso emite exhorto en materia de transporte público durante la intensa agenda legislativa de septiembre de 2025. La iniciativa forma parte de un bloque de acuerdos sobre transporte y movilidad concentrado en esa semana. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-042",
    "fecha": "2025-09-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la Secretaría de Transporte del Estado para actualizar o mejorar aspectos del sistema de transporte público de Jalisco.",
    "resumen": "El Congreso exhorta a la Secretaría de Transporte a implementar actualizaciones en la operación o regulación del sistema de transporte público estatal. La iniciativa puede referirse a actualizaciones tarifarias, de rutas, tecnológicas o de normativa de concesiones. Refleja la supervisión legislativa permanente sobre el órgano rector del transporte en la entidad.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-037",
    "fecha": "2025-09-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la Secretaría de Movilidad del Estado sobre accesibilidad para personas con discapacidad en el sistema de transporte y espacios públicos de Jalisco.",
    "resumen": "El Congreso exhorta a la Secretaría de Movilidad a garantizar condiciones de accesibilidad plena para personas con discapacidad en el transporte público y la infraestructura urbana. La iniciativa atiende una demanda histórica de organizaciones de la sociedad civil sobre barreras físicas en el sistema de movilidad. Complementa la normativa de accesibilidad universal vigente en el estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-036",
    "fecha": "2025-09-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta a las autoridades de Puerto Vallarta a construir o mejorar ciclovías en el municipio costero.",
    "resumen": "El Congreso exhorta al gobierno de Puerto Vallarta a desarrollar infraestructura ciclista en el municipio. La iniciativa responde al crecimiento del turismo activo y la demanda local de alternativas de movilidad sustentable en la zona costera. Forma parte de un patrón legislativo de impulso a la movilidad no motorizada en municipios con vocación turística.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-033",
    "fecha": "2025-09-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Punto de Acuerdo sobre transporte público con énfasis en movilidad activa e integración intermodal en Jalisco.",
    "resumen": "El Congreso exhorta a las autoridades de transporte a mejorar la integración entre el transporte público y los modos de movilidad activa. La iniciativa promueve la intermodalidad como estrategia de movilidad sustentable en la ZMG y municipios del estado. Fue presentada en una sesión muy activa en materia de movilidad el 5 de septiembre de 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-034",
    "fecha": "2025-09-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_INF",
    "extracto": "Punto de Acuerdo sobre movilidad activa e infraestructura peatonal o ciclista en municipios de Jalisco.",
    "resumen": "El Congreso exhorta a autoridades municipales a mejorar la infraestructura para movilidad activa, incluyendo banquetas, ciclovías y cruces peatonales. La iniciativa busca garantizar condiciones seguras para peatones y ciclistas en el entorno urbano. Complementa los esfuerzos legislativos de promoción de la movilidad sustentable.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-035",
    "fecha": "2025-09-05",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Punto de Acuerdo sobre infraestructura vial con componentes de accesibilidad para movilidad activa en municipios jaliscienses.",
    "resumen": "El Congreso exhorta a los ejecutivos municipales a incorporar criterios de accesibilidad y movilidad activa en los proyectos de infraestructura vial. La propuesta busca que las obras de vialidad incluyan banquetas accesibles, rampas y carriles para ciclistas. Es complementaria a otros acuerdos en materia de movilidad activa presentados en la misma sesión.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-030",
    "fecha": "2025-08-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Transporte del Estado de Jalisco, agosto 2025.",
    "resumen": "La legislatura presenta una reforma al marco normativo del transporte público estatal. La iniciativa modifica disposiciones sobre la operación, concesión o regulación del servicio de transporte colectivo. Fue presentada en la sesión intensa de finales de agosto 2025 con múltiples iniciativas de transporte.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-031",
    "fecha": "2025-08-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo relativo al transporte público con alcance para los 125 ayuntamientos del estado de Jalisco.",
    "resumen": "El Congreso emite un exhorto de alcance estatal sobre el transporte público, dirigido a los 125 municipios de Jalisco. La iniciativa puede referirse a la homologación de normativas de transporte, seguridad o accesibilidad en los sistemas locales. Es notable por su cobertura universal sobre todos los ayuntamientos del estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-032",
    "fecha": "2025-08-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre transporte universitario de la Universidad de Guadalajara (UdeG) en el estado de Jalisco.",
    "resumen": "El Congreso exhorta a la UdeG o a las autoridades de transporte sobre el servicio de transporte universitario. La iniciativa puede abordar tarifas especiales, rutas, o condiciones del servicio para la comunidad universitaria. Fue presentada el mismo día que el exhorto sobre los 125 ayuntamientos, como parte de un paquete de agosto 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-029",
    "fecha": "2025-08-26",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa centrada en la movilidad activa, modificando disposiciones sobre derechos de ciclistas, peatones y usuarios de medios no motorizados en Jalisco.",
    "resumen": "La legislatura propone una reforma que fortalece los derechos y la infraestructura para usuarios de modos de transporte activo. La iniciativa puede incluir nuevas obligaciones para los municipios en materia de infraestructura ciclista y peatonal. Es parte del proceso de actualización normativa que reconoce la movilidad activa como derecho.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-028",
    "fecha": "2025-08-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público de Jalisco, dirigido a operadores o autoridades de transporte.",
    "resumen": "El Congreso emite exhorto sobre el transporte público estatal, posiblemente sobre rutas, tarifas o condiciones del servicio. La iniciativa forma parte del conjunto de exhortos en materia de transporte público de agosto de 2025. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-027",
    "fecha": "2025-08-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la SCT para que realice reparaciones o mantenimiento en carreteras federales de Jalisco.",
    "resumen": "El Congreso exhorta a la Secretaría de Comunicaciones y Transportes federal a ejecutar trabajos de mantenimiento en carreteras de jurisdicción federal en el estado. La iniciativa atiende el deterioro de la red carretera federal como factor de riesgo vial y económico. Es un mecanismo recurrente de gestión parlamentaria ante la SCT.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-026",
    "fecha": "2025-08-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "ENE_EF",
    "extracto": "Punto de Acuerdo No. 404-LXIV-25 que exhorta al Ejecutivo del Estado a instalar paneles solares en edificios y dependencias del gobierno estatal de Jalisco como medida de eficiencia y transición energética.",
    "resumen": "El Congreso aprueba exhortar al gobierno estatal para que instale paneles solares fotovoltaicos en sus edificios públicos. La medida tiene como objetivo reducir el gasto energético gubernamental y demostrar liderazgo institucional en la transición a energías limpias. Complementa las políticas de generación distribuida en el marco de la reforma energética federal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía"
  },
  {
    "id": "JAL-2025-025",
    "fecha": "2025-07-10",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta a autoridades municipales a vigilar y garantizar la libre circulación en vialidades de la entidad.",
    "resumen": "El Congreso exhorta a las autoridades competentes a mantener la libre circulación en las vialidades del estado, previniendo bloqueos u obstrucciones. La iniciativa puede responder a protestas, manifestaciones o invasiones de vía pública que afecten la movilidad ciudadana. Es un exhorto de control parlamentario sobre el orden en las vialidades.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad"
  },
  {
    "id": "JAL-2025-024",
    "fecha": "2025-07-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo relativo a la carretera Lagos de Moreno-Guadalajara, referente al cobro de cuotas o peaje y condiciones de la vía.",
    "resumen": "El Congreso emite exhorto sobre la situación de la carretera Lagos de Moreno-Guadalajara, con énfasis en las condiciones del cobro de peaje o cuota. La iniciativa atiende demandas de usuarios sobre el estado de la infraestructura y la justificación del cobro de peaje. Es relevante para la conectividad del corredor norte del estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito"
  },
  {
    "id": "JAL-2025-022",
    "fecha": "2025-07-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "ENE_GEN",
    "extracto": "Punto de Acuerdo No. 355-LXIV-25 en relación con la reforma energética publicada en el DOF el 18 de marzo de 2025, que modifica el marco regulatorio del sector eléctrico nacional.",
    "resumen": "El Congreso de Jalisco emite posicionamiento respecto a la reforma constitucional energética federal publicada en el DOF el 18 de marzo de 2025. El acuerdo analiza las implicaciones de la reforma en la generación, distribución y gobernanza del sector eléctrico. Es un acto de posicionamiento legislativo ante la transformación del marco regulatorio federal.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | Subtema corregido: ENE_GEN→ENE_REG (el contenido es gobernanza/marco regulatorio derivado de reforma federal, no generación directa)"
  },
  {
    "id": "JAL-2025-023",
    "fecha": "2025-07-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "ENE_EF",
    "extracto": "Punto de Acuerdo No. 356-LXIV-25 que exhorta a los 125 municipios de Jalisco a adoptar medidas de eficiencia energética y promover el uso de energías limpias y renovables en instalaciones públicas municipales.",
    "resumen": "El Congreso exhorta a los municipios jaliscienses a implementar políticas de eficiencia energética y transición a energías limpias en edificios e infraestructura pública. La iniciativa impulsa la descarbonización desde el ámbito municipal como complemento a la política energética estatal. Refleja la tendencia de empujar responsabilidades de transición hacia los gobiernos locales.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía"
  },
  {
    "id": "JAL-2025-021",
    "fecha": "2025-06-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta al municipio de Zapopan a realizar obras de pavimentación en vialidades con deterioro.",
    "resumen": "El Congreso exhorta a las autoridades de Zapopan a ejecutar obras de pavimentación en vías con daños o en tierra. La iniciativa atiende demandas ciudadanas de mejora en la infraestructura vial en uno de los municipios más grandes del estado. La pavimentación es una condición básica para la seguridad y fluidez del tránsito.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad"
  },
  {
    "id": "JAL-2025-020",
    "fecha": "2025-06-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre la coordinación entre la Secretaría de Transporte estatal y el Área Metropolitana de Guadalajara (AMG) en materia de transporte público.",
    "resumen": "El Congreso exhorta a la Secretaría de Transporte y al organismo metropolitano AMG a mejorar la coordinación en la operación del transporte público de la zona conurbada. La iniciativa aborda la fragmentación institucional en la gestión del transporte metropolitano. Es relevante para la articulación del sistema de movilidad de la segunda ciudad más grande del país.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-019",
    "fecha": "2025-06-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público en Jalisco, presentado en junio de 2025.",
    "resumen": "El Congreso emite exhorto sobre transporte público colectivo del estado. La iniciativa forma parte de la agenda legislativa de junio 2025 en materia de movilidad. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-016",
    "fecha": "2025-05-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre las rutas de transporte público 45, 207, 249 y 258A en la Zona Metropolitana de Guadalajara, relativo a frecuencias, cobertura o condiciones del servicio.",
    "resumen": "El Congreso exhorta a las autoridades de transporte respecto al servicio en cuatro rutas específicas de la ZMG. La iniciativa atiende quejas ciudadanas sobre deficiencias en frecuencias o cobertura de estas líneas. Es un mecanismo de control parlamentario sobre la concesionaria de transporte público.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "JAL-2025-017",
    "fecha": "2025-05-20",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "ENE_TAR",
    "extracto": "Exhorto a la CFE para implementar tarifas diferenciadas o subsidios en el suministro eléctrico a bancos de alimentos y organizaciones de asistencia social en Jalisco, en el marco de la transición energética.",
    "resumen": "El Congreso exhorta a la CFE a aplicar tarifas preferenciales o subsidios a bancos de alimentos y organizaciones sociales del estado. La medida busca reducir el impacto de los costos energéticos en instituciones que atienden a poblaciones vulnerables. Tiene relevancia dentro del debate sobre acceso equitativo a la energía en el contexto de la reforma eléctrica.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía"
  },
  {
    "id": "JAL-2025-018",
    "fecha": "2025-05-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Reforma legislativa que modifica la Ley de Movilidad para incluir disposiciones sobre transporte público y movilidad activa en Jalisco.",
    "resumen": "La legislatura propone una reforma que fortalece el marco normativo del transporte público incorporando elementos de movilidad activa. La iniciativa puede incluir la regulación de cicloestaciones en terminales de transporte o criterios de diseño incluyente. Fue presentada el mismo día que puntos de acuerdo sobre energía y transporte, evidenciando una sesión intensiva.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-015",
    "fecha": "2025-05-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_INF",
    "extracto": "Punto de Acuerdo que solicita incrementar el patrullaje o rondines de seguridad en carreteras del estado de Jalisco.",
    "resumen": "El Congreso exhorta a las autoridades de seguridad a intensificar la vigilancia en carreteras estatales y federales de Jalisco. La iniciativa busca reducir la incidencia delictiva y accidentes en tramos de alto riesgo. Complementa esfuerzos previos de solicitud de presencia de Guardia Nacional en carreteras.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-014",
    "fecha": "2025-05-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Punto de Acuerdo sobre el SITEUR (Sistema de Tren Eléctrico Urbano) relativo a escaleras eléctricas o mecánicas en estaciones del sistema de transporte masivo de la ZMG.",
    "resumen": "El Congreso exhorta al SITEUR a reparar o instalar escaleras eléctricas o mecánicas en las estaciones del sistema de tren eléctrico. La falta de escaleras operativas afecta la accesibilidad y experiencia de usuarios, especialmente personas con movilidad reducida. La iniciativa vincula la operación del transporte masivo con estándares de movilidad activa y accesibilidad.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-012",
    "fecha": "2025-05-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el servicio de transporte público en Jalisco, mayo 2025.",
    "resumen": "El Congreso emite exhorto en materia de transporte público durante el período de sesiones de mayo 2025. La iniciativa atiende problemas del sistema de transporte colectivo estatal. El contenido específico requiere verificación en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-013",
    "fecha": "2025-05-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo dirigido a la Secretaría de Comunicaciones y Transportes (SCT) federal sobre infraestructura vial en Jalisco.",
    "resumen": "El Congreso exhorta a la SCT federal a atender necesidades de infraestructura en carreteras federales del estado. La iniciativa puede referirse a mantenimiento, ampliación o construcción de vías federales en Jalisco. Es parte del ejercicio habitual de gestión legislativa ante dependencias federales.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-011",
    "fecha": "2025-05-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo sobre el sistema de transporte público en Jalisco, dirigido a la Secretaría de Transporte o concesionarios.",
    "resumen": "El Congreso emite un exhorto en materia de transporte público de Jalisco. La iniciativa busca atender deficiencias específicas en el servicio de transporte colectivo del estado. El contenido detallado requiere verificación directa en el portal INFOLEJ.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-010",
    "fecha": "2025-03-31",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Punto de Acuerdo sobre transporte público con incorporación de elementos de movilidad activa en Jalisco.",
    "resumen": "El Congreso emite exhorto sobre transporte público con énfasis en la articulación con modos de movilidad activa. La iniciativa promueve la integración intermodal entre transporte colectivo y desplazamientos a pie o en bicicleta. Es el cierre del bloque de iniciativas de movilidad integrada de marzo 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-009",
    "fecha": "2025-03-26",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Punto de Acuerdo sobre movilidad activa y su integración con el sistema de transporte público en municipios de Jalisco.",
    "resumen": "El Congreso exhorta a las autoridades a promover la movilidad activa como complemento del transporte público colectivo. La iniciativa busca articular la caminata y el ciclismo urbano con el sistema de transporte masivo. Refleja el enfoque de movilidad integrada que caracteriza a varias iniciativas de la LXIV Legislatura.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-008",
    "fecha": "2025-03-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la normativa de seguridad vial del Estado de Jalisco, modificando disposiciones sobre tránsito y sanciones.",
    "resumen": "La legislatura propone una reforma centrada en la seguridad vial, modificando disposiciones sobre infracciones, sanciones o procedimientos de tránsito. La iniciativa busca fortalecer el marco normativo de prevención de accidentes en el estado. Puede incluir actualizaciones al Reglamento de Tránsito o leyes relacionadas.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-007",
    "fecha": "2025-03-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_INF",
    "extracto": "Punto de Acuerdo que solicita la instalación de módulos de seguridad de la Guardia Nacional en carreteras federales que atraviesan el estado de Jalisco.",
    "resumen": "El Congreso exhorta al gobierno federal a instalar módulos o retenes de la Guardia Nacional en tramos carreteros clave del estado. La iniciativa responde a la inseguridad en las carreteras de Jalisco y busca disuadir el crimen en vías de comunicación. Involucra tanto la seguridad vial como la infraestructura de supervisión en carreteras.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-006",
    "fecha": "2025-02-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma legislativa que modifica la Ley de Movilidad y Transporte y/o la Ley de Seguridad Vial del Estado de Jalisco.",
    "resumen": "La legislatura presenta una reforma que aborda conjuntamente el transporte público y la seguridad vial en Jalisco. La iniciativa modifica disposiciones normativas que vinculan la operación del transporte con estándares de seguridad. Es parte del proceso de actualización del marco legal de movilidad en el estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-005",
    "fecha": "2025-02-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "Punto de Acuerdo sobre seguridad en el transporte público de Jalisco, exhortando a mejorar protocolos de seguridad para usuarios y operadores.",
    "resumen": "El Congreso exhorta a las autoridades competentes a reforzar la seguridad en el servicio de transporte público del estado. La iniciativa aborda riesgos para usuarios y operadores en el sistema de transporte colectivo. Complementa las reformas legislativas sobre movilidad y seguridad vial del período.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2025-001",
    "fecha": "2025-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Punto de Acuerdo que exhorta a autoridades del transporte público a garantizar la instalación y mantenimiento de rampas de acceso para personas con discapacidad en las unidades de transporte público de Jalisco.",
    "resumen": "El Congreso exhorta al sector de transporte público a asegurar la accesibilidad universal mediante la instalación de rampas para personas con discapacidad. La iniciativa atiende una obligación legal de accesibilidad que frecuentemente no se cumple en la flota vehicular del estado. Es parte de un conjunto de iniciativas de febrero de 2025 sobre transporte y movilidad.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-002",
    "fecha": "2025-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de Acuerdo que exhorta a las autoridades de Tlaquepaque a garantizar la libre circulación en las vialidades del municipio.",
    "resumen": "El Congreso exhorta al municipio de San Pedro Tlaquepaque a remover obstáculos o garantizar la fluidez del tránsito en sus vialidades principales. La iniciativa responde a quejas ciudadanas sobre bloqueos, invasión de vialidades o deficiencias en la señalización. Aborda la seguridad y fluidez vial en uno de los municipios metropolitanos del estado.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad"
  },
  {
    "id": "JAL-2025-003",
    "fecha": "2025-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Punto de Acuerdo sobre condiciones de seguridad en el transporte público de Jalisco, exhortando a operadores o autoridades a mejorar protocolos.",
    "resumen": "El Congreso exhorta a las autoridades de transporte a fortalecer las condiciones de seguridad en el servicio público de transporte. La iniciativa aborda aspectos de protección a usuarios y operadores del sistema de transporte colectivo. Fue presentada el mismo día que otros puntos de acuerdo de transporte del bloque de febrero 2025.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "JAL-2025-004",
    "fecha": "2025-02-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Transporte del Estado de Jalisco, presentada en febrero 2025.",
    "resumen": "La legislatura debate una reforma a la Ley de Movilidad y Transporte del estado. La iniciativa modifica artículos relacionados con la regulación del transporte público en Jalisco. Fue presentada en el mismo bloque de febrero 2025 con otras reformas en la materia.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2024-002",
    "fecha": "2024-11-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Reforma legislativa a la Ley de Movilidad y Seguridad Vial del Estado de Jalisco, modificando disposiciones sobre transporte público y seguridad en el servicio.",
    "resumen": "La LXIV Legislatura aprueba una reforma que modifica la Ley de Movilidad y Seguridad Vial en lo relativo al transporte público y la seguridad en el servicio. Es una de las primeras reformas de calado de la nueva legislatura en materia de transporte y seguridad vial. Establece el marco normativo inicial sobre el que se construirán reformas posteriores.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | También encontrado en: movilidad"
  },
  {
    "id": "JAL-2024-001",
    "fecha": "2024-11-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Decreto de reforma legislativa relacionado con el SITEUR (Sistema de Tren Eléctrico Urbano) de la Zona Metropolitana de Guadalajara.",
    "resumen": "La legislatura aprueba una reforma al marco legal del SITEUR, el sistema de transporte masivo de la ZMG. La reforma regula aspectos operativos, de gobernanza o tarifarios del sistema de tren eléctrico urbano metropolitano. Es una de las primeras reformas de la LXIV Legislatura en materia de transporte público.",
    "link_documento": "",
    "link_portal": "https://infolej.congresojal.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};