const DATA = [
  {
    "id": "QRO-2026-001",
    "fecha": "2026-02-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Acuerdo por el cual se exhorta respetuosamente a la Secretaría de Infraestructura, Comunicaciones y Transportes, así como a la Agencia de Movilidad de Querétaro para que en el ámbito de sus atribuciones supervisen los servicios auxiliares de autotransporte; presentada por la Diputada Sully Yanira Mauricio Sixtos (MORENA).",
    "resumen": "Exhorto a la SICT federal y a la Agencia de Movilidad de Querétaro para que supervisen el cumplimiento normativo de los servicios auxiliares de autotransporte (grúas, pensiones vehiculares y similares). Busca corregir irregularidades operativas en este sector de transporte que afectan a usuarios del estado.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/449_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "QRO-2025-008",
    "fecha": "2025-11-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Ley que modifica el título de la Ley de Servicios Auxiliares del Transporte Público del Estado de Querétaro a Ley de Servicios Auxiliares de las Vías de Comunicación del Estado de Querétaro, y reforma artículos 4 BIS, 6, 8, 40, 45 y adiciona Capítulo Noveno sobre permisos especiales para emergencias (Art. 58); presentada por el Diputado Enrique Antonio Correa Sada (Independiente).",
    "resumen": "Reforma sustancial a la ley que regula los servicios auxiliares al transporte: cambia su nombre y alcance para abarcar todas las vías de comunicación (no solo transporte público), modifica el catálogo de servicios regulados, actualiza fracciones sobre operación y permisos, y añade un capítulo de permisos especiales para emergencias.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/384_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "QRO-2025-007",
    "fecha": "2025-10-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Ley que reforma y adiciona diversas disposiciones del Código Penal del Estado de Querétaro y de la Ley de Tránsito del Estado de Querétaro; presentada por el Diputado Homero Barrera McDonald (MORENA).",
    "resumen": "Reforma en paralelo el Código Penal y la Ley de Tránsito de Querétaro para fortalecer las consecuencias penales y administrativas de conductas de riesgo en la vía pública. Endurece el marco sancionatorio para conductores infractores, vinculando el derecho penal con la normatividad de tránsito estatal.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/344_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito"
  },
  {
    "id": "QRO-2025-006",
    "fecha": "2025-08-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Iniciativa de Ley por la que se expide la Ley de Movilidad Sustentable y Seguridad Vial del Estado de Querétaro; Iniciativa de Ley que adiciona al Código Penal en materia de delitos contra personas usuarias de la vía pública, ciclistas y peatones; e Iniciativa que adiciona el artículo 39 BIS de la Ley de Educación del Estado de Querétaro en materia de educación vial; presentadas por el Diputado Enrique Antonio Correa Sada (Independiente), 54 páginas.",
    "resumen": "Paquete legislativo que propone crear una nueva Ley de Movilidad Sustentable y Seguridad Vial para Querétaro, tipificar delitos contra ciclistas y peatones en el Código Penal, e incorporar educación vial en la ley educativa estatal. Es la propuesta más integral del período por combinar nueva ley, reforma penal y enfoque educativo.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/293_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "QRO-2025-005",
    "fecha": "2025-06-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Acuerdo por el cual la LXI Legislatura exhorta a la Secretaría de Infraestructura, Comunicaciones y Transportes a restringir temporalmente la circulación de tractocamiones y vehículos de carga pesada en el tramo México-Querétaro de la Carretera Federal 57 durante obras de remodelación, obligando al uso de vías alternas; presentada por la Diputada Sully Yanira Mauricio Sixtos (MORENA).",
    "resumen": "Exhorto a la SICT federal para restringir temporalmente el tránsito de carga pesada en la Carretera Federal 57 tramo México-Querétaro mientras se realizan obras de remodelación, obligando a usar vías alternas. Responde a afectaciones a la infraestructura vial y la seguridad de los usuarios.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/258_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "QRO-2025-004",
    "fecha": "2025-03-03",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa de Acuerdo por el que se exhorta al Poder Ejecutivo del Estado a implementar 'Senderos Seguros' a favor de la movilidad y seguridad de las mujeres y niñas del Estado de Querétaro; presentada por el Diputado Homero Barrera McDonald (MORENA).",
    "resumen": "Exhorto al Ejecutivo estatal para que implemente un programa de senderos seguros con infraestructura peatonal protegida para mujeres y niñas en espacios públicos. Prioriza la movilidad activa con enfoque de género como elemento de seguridad urbana y accesibilidad.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/187_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "QRO-2025-003",
    "fecha": "2025-02-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa que reforma la Ley de la Agencia de Movilidad y Modalidades de Transporte Público para el Estado de Querétaro en materia del servicio público de transporte denominado mixto; presentada por el Diputado Sinuhé Arturo Piedragil Ortiz (MORENA).",
    "resumen": "Reforma la ley de la Agencia de Movilidad estatal para regular específicamente el transporte mixto, una modalidad de servicio público de transporte. Modifica el régimen de concesiones, requisitos y operación de esta modalidad de transporte público en Querétaro.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/176_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  },
  {
    "id": "QRO-2025-002",
    "fecha": "2025-01-30",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Iniciativa que reforma y adiciona diversas disposiciones de la Ley Orgánica de la Agencia de Energía del Estado de Querétaro; presentada por las Diputadas Claudia Díaz Gayou, Laura Andrea Tovar Saavedra, María Eugenia Margarito Vázquez y Rosalba Vázquez Munguía.",
    "resumen": "Reforma la Ley Orgánica de la Agencia de Energía del Estado de Querétaro, modificando el marco de gobernanza, atribuciones y estructura de dicha agencia estatal. Afecta directamente la institucionalidad del sector energético en Querétaro y la regulación de quién genera y distribuye energía en el estado.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/169_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: energía | Fecha estimada: PDF no accesible (404); fecha inferida por posición secuencial entre ini. 142 (14/01/25) y 176 (13/02/25)"
  },
  {
    "id": "QRO-2025-001",
    "fecha": "2025-01-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa que crea la Ley de Movilidad y Seguridad Vial para el Estado de Querétaro (94 páginas); presentada por el Diputado Arturo Maximiliano García Pérez (MORENA). Establece jerarquía de usuarios de la vía, derechos a la movilidad, normas de seguridad vial, infraestructura y régimen sancionatorio.",
    "resumen": "Iniciativa de 94 páginas que propone crear una Ley de Movilidad y Seguridad Vial completa para Querétaro, la primera del estado en su tipo. Establece derechos a la movilidad, jerarquía de usuarios de la vía pública que privilegia a peatones y ciclistas, normas de seguridad vial y un régimen de sanciones. Es la propuesta legislativa de mayor alcance en materia de movilidad del período.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/142_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad"
  },
  {
    "id": "QRO-2024-001",
    "fecha": "2024-10-16",
    "tipo_acto": "Minuta",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Minuta con proyecto de decreto que reforma el párrafo cuarto y se adiciona un párrafo quinto al artículo 28 de la Constitución Política de los Estados Unidos Mexicanos en materia de vías y transporte ferroviario; presentada por la Sen. Verónica Noemí Camino Farjat, Secretaria de la Mesa Directiva del Senado de la República.",
    "resumen": "Minuta federal enviada a la Legislatura de Querétaro para ratificación, que reforma el artículo 28 constitucional para modificar disposiciones sobre vías generales de comunicación y el sistema ferroviario nacional. Implica un cambio de fondo al régimen constitucional del transporte ferroviario en México, con implicaciones para la infraestructura estatal.",
    "link_documento": "https://site.legislaturaqueretaro.gob.mx/CloudPLQ/SerPar/Iniciativas/LXI/038_61.pdf",
    "link_portal": "http://legislaturaqueretaro.gob.mx/iniciativas/",
    "fuente_verificada": "Sí",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
