const DATA = [
  {
    "id": "GRO-2026-006",
    "fecha": "2026-03-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #187 de la LXIV Legislatura que solicita la rehabilitación del libramiento de Tlapa de Comonfort para garantizar el derecho humano a la movilidad y mejorar la conectividad de la región Montaña de Guerrero.",
    "resumen": "El Congreso aprobó un segundo exhorto sobre el libramiento de Tlapa de Comonfort, esta vez enfocado en su rehabilitación, lo que indica que la problemática persiste sin resolverse. La reiteración del tema en dos acuerdos distintos (ver también #164 de feb-2026) evidencia una deficiencia vial crónica en el acceso a la región Montaña.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #187 de la LXIV Legislatura; segundo exhorto sobre el libramiento de Tlapa (primer exhorto: Acuerdo #164 de feb-2026); exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2026-005",
    "fecha": "2026-03-17",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "ENE_REG",
    "extracto": "Acuerdo #182 de la LXIV Legislatura que exhorta a la Comisión Federal de Electricidad (CFE) al retiro del cableado en desuso ('marañas') acumulado en postes del estado de Guerrero, que representa riesgos de seguridad pública y deterioro del entorno urbano.",
    "resumen": "El Congreso aprobó un exhorto para que CFE retire el cableado obsoleto acumulado en postes de ciudades guerrerenses, una problemática de seguridad pública (riesgo de caída, cortocircuitos) y estética urbana. El acuerdo formaliza la presión legislativa hacia la empresa paraestatal en materia de mantenimiento de infraestructura eléctrica.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Acuerdo #182 de la LXIV Legislatura; exhorto no vinculante | Subtema corregido: ENE_TAR→ENE_EF (trata de infraestructura y mantenimiento, no de tarifas)",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2026-004",
    "fecha": "2026-02-18",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Acuerdo #171 de la LXIV Legislatura que solicita a la Comisión Federal de Electricidad (CFE) otorgue una categoría tarifaria eléctrica especial para los organismos operadores de agua del Estado de Guerrero, considerando el alto impacto de la energía eléctrica en sus costos operativos.",
    "resumen": "El Congreso aprobó un exhorto para que CFE aplique una tarifa eléctrica diferenciada a los organismos operadores de agua de Guerrero, que enfrentan facturas elevadas que encarecen el servicio de agua potable. La medida busca reducir costos operativos y hacer más accesible el servicio de agua para la población. Complementa el Acuerdo #94 sobre diagnósticos energéticos en sistemas de bombeo.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Acuerdo #171 de la LXIV Legislatura; exhorto no vinculante; relacionado con Acuerdo #94",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2026-003",
    "fecha": "2026-02-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 84 ayuntamientos de Guerrero y al Concejo Municipal de Ayutla de los Libres para que expidan y/o actualicen sus Reglamentos de Tránsito y Vialidad, con el objetivo de generar condiciones de orden, seguridad y sana convivencia entre usuarios de la vía pública. Presentado por la Dip. Violeta Martínez Pacheco (Morena).",
    "resumen": "La Dip. Violeta Martínez Pacheco presentó un exhorto a todos los municipios de Guerrero para actualizar sus reglamentos de tránsito, señalando que son herramientas esenciales de seguridad vial para prevenir accidentes y fomentar el respeto a los derechos humanos. La propuesta reconoce que muchos municipios operan con reglamentos desactualizados o inexistentes, generando vacíos normativos en la gestión vial local.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/inicio/pide-diputada-a-ayuntamientos-modernizar-reglamentos-de-transito-y-vialidad/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: En comisión | Término búsqueda: tránsito | Propuesta de Dip. Violeta Martínez Pacheco (Morena); en análisis en Comisión de Transporte al 12-feb-2026; estatus en pleno no confirmado",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2026-001",
    "fecha": "2026-02-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #162 de la LXIV Legislatura que solicita al gobierno federal supervisión y reparación de la carretera federal Iguala-Ciudad Altamirano, que presenta deterioro severo afectando el tránsito regional en la zona norte y Tierra Caliente del estado.",
    "resumen": "El Congreso aprobó un exhorto para atender el deterioro de la carretera Iguala-Ciudad Altamirano, que conecta la zona norte del estado con la región de Tierra Caliente y es vital para la movilidad de personas y mercancías en el interior de Guerrero.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #162 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2026-002",
    "fecha": "2026-02-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #164 de la LXIV Legislatura que demanda la ampliación a cuatro carriles y mantenimiento del libramiento de Tlapa de Comonfort para garantizar el derecho humano a la movilidad y mejorar la conectividad de la región Montaña de Guerrero.",
    "resumen": "El Congreso aprobó un exhorto para la ampliación del libramiento de Tlapa de Comonfort a cuatro carriles, atendiendo la demanda de mayor capacidad vial en una de las ciudades más importantes de la región Montaña. La vía actual resulta insuficiente para el volumen de tránsito, generando cuellos de botella y riesgos viales.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #164 de la LXIV Legislatura; ver también Acuerdo #187 (mar-2026) sobre el mismo libramiento; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2025-005",
    "fecha": "2025-11-12",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #136 de la LXIV Legislatura que solicita al gobierno federal la reparación urgente de la carretera Acapulco-Zihuatanejo en el tramo de Pie de la Cuesta, que presenta deterioro severo comprometiendo la seguridad vial de usuarios.",
    "resumen": "El Congreso aprobó un exhorto urgente para que el gobierno federal atienda el deterioro grave de la carretera costera Acapulco-Zihuatanejo, arteria vital para la conectividad turística y económica del estado. El tramo de Pie de la Cuesta presenta condiciones que comprometen la seguridad de conductores y peatones.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #136 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2025-004",
    "fecha": "2025-10-29",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #123 de la LXIV Legislatura que instruye al ejecutivo estatal establecer una partida presupuestal para la rehabilitación de vías en los municipios de Teloloapan e Ixcateopan de Cuauhtémoc, en la región norte de Guerrero.",
    "resumen": "El Congreso aprobó un exhorto para destinar recursos presupuestales a la rehabilitación de vías en dos municipios de la zona norte de Guerrero. Si bien no crea obligaciones vinculantes, la medida presiona al ejecutivo a priorizar inversión en infraestructura vial en zonas con déficit histórico de mantenimiento carretero.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #123 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2025-003",
    "fecha": "2025-10-15",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Acuerdo #115 de la LXIV Legislatura que requiere al gobierno federal y estatal establecer protocolos de actuación ante bloqueos en la autopista del Sol (México-Acapulco), garantizando el libre tránsito de personas y mercancías.",
    "resumen": "El Congreso aprobó un exhorto para atender los bloqueos recurrentes en la autopista del Sol, que afectan el derecho al libre tránsito y la conectividad de Guerrero con el centro del país. La medida formaliza la posición legislativa ante una problemática de impacto en la movilidad regional, el sector turístico y el comercio.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | Acuerdo #115 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2025-002",
    "fecha": "2025-10-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Acuerdo #102 de la LXIV Legislatura que demanda a la Comisión Federal de Electricidad (CFE) brindar atención eficiente en los municipios del Estado de Guerrero, en materia de fallas, interrupciones del servicio eléctrico y atención a usuarios.",
    "resumen": "El Congreso aprobó un exhorto exigiendo a CFE mejorar la calidad y continuidad del servicio eléctrico en los municipios guerrerenses, donde son recurrentes las fallas y la atención deficiente al usuario. Aunque sin fuerza vinculante, el acuerdo refleja presión legislativa ante quejas ciudadanas por interrupciones prolongadas del servicio.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Acuerdo #102 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2025-001",
    "fecha": "2025-09-09",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_EF",
    "subtema_secundario": "ENE_TAR",
    "extracto": "Acuerdo #94 de la LXIV Legislatura que requiere que la Comisión Federal de Electricidad (CFE) celebre convenios con los organismos operadores de agua del Estado de Guerrero para la realización de diagnósticos energéticos en sistemas de bombeo y adopción de medidas de eficiencia energética.",
    "resumen": "El Congreso aprobó un exhorto para que CFE celebre convenios con los organismos de agua de Guerrero orientados a reducir el consumo energético en sistemas de bombeo. La iniciativa busca disminuir costos operativos de los organismos de agua, cuya factura eléctrica representa uno de sus principales egresos, mediante diagnósticos técnicos y mejoras en eficiencia. Su impacto normativo es limitado por ser un exhorto no vinculante.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/64/sesiones/acuerdos.php",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Acuerdo #94 de la LXIV Legislatura; exhorto no vinculante",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2024-004",
    "fecha": "2024-10-01",
    "tipo_acto": "Minuta",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Minuta del Senado de la República que reforma los artículos 25, 27 y 28 de la Constitución Política de los Estados Unidos Mexicanos en materia de áreas y empresas estratégicas del Estado, convirtiendo a CFE y Pemex en empresas públicas del Estado y derogando los efectos de la reforma energética de 2013 que abrió la generación y distribución de energía al capital privado.",
    "resumen": "El Congreso de Guerrero (LXIV Legislatura) fue uno de los 22 congresos estatales que aprobaron la reforma constitucional energética que revirtió la apertura al capital privado de 2013. La reforma otorga nuevamente al Estado el control rector sobre la generación y distribución de electricidad e hidrocarburos, fortaleciendo el carácter público de CFE y Pemex. Por ser minuta constitucional, su aprobación fue requisito para consumar la reforma a nivel federal.",
    "link_documento": "",
    "link_portal": "https://congresogro.gob.mx/63/inicio/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: energía | Guerrero identificado entre los 22 estados que aprobaron la reforma; reforma constitucional se consuma el 24-oct-2024 a nivel federal; fecha exacta de sesión en LXIV Legislatura no verificada; se estima octubre 2024",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2024-003",
    "fecha": "2024-08-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Transporte y Vialidad que armoniza la ley con la Ley Orgánica de la Administración Pública del Estado, transfiere facultades de la Comisión Técnica de Transporte a la Secretaría General de Gobierno, incorpora lenguaje incluyente sustituyendo expresiones sexistas (ej. 'los concesionarios' por 'las personas concesionarias'), y regula servicios auxiliares de arrastre, salvamento y depósito vehicular con control tarifario vía Secretaría General de Gobierno.",
    "resumen": "El Congreso aprobó una reforma que armoniza la Ley de Transporte y Vialidad con la Ley Orgánica de la Administración Pública estatal, moderniza el lenguaje del texto conforme a estándares de derechos humanos e incorpora regulación formal de servicios auxiliares como arrastre y salvamento vehicular. Las tarifas de estos servicios quedan sujetas a autorización gubernamental, con revocación de permisos como sanción por incumplimiento.",
    "link_documento": "http://legismex.mty.itesm.mx/estados/ley-gro/GRO-L-TranspVial2024_09.pdf",
    "link_portal": "https://guerrero.quadratin.com.mx/aprueban-reformas-a-la-ley-de-transporte-de-guerrero/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | Fecha es del voto en pleno según Quadratín; versión actualizada de la ley publicada en septiembre 2024",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2024-002",
    "fecha": "2024-07-04",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Transporte y Vialidad del Estado de Guerrero que establece procedimiento adecuado en casos de revocación de concesión, garantizando derecho de audiencia al concesionario. Establece como causa de revocación la operación de unidad en estado de intoxicación por alcohol o drogas, o cuando por condición mecánica del vehículo se produzca accidente con pérdida de vidas humanas.",
    "resumen": "El Congreso aprobó reformas a la Ley de Transporte y Vialidad para fortalecer el procedimiento de revocación de concesiones, garantizando el debido proceso para operadores mientras establece sanciones claras ante accidentes fatales causados por intoxicación o fallas mecánicas. La medida responde a incidentes reiterados de vehículos de transporte público involucrados en accidentes graves bajo estas causas.",
    "link_documento": "https://congresogro.gob.mx/legislacion/ordinarias/ARCHI/LEY-DE-TRANSPORTE-Y-VIALIDAD-DEL-ESTADO-DE-GUERRERO-0-2021-08-19.pdf",
    "link_portal": "https://congresogro.gob.mx/63/inicio/2024/07/04/aprobo-el-congreso-reformas-para-garantizar-la-prestacion-de-un-mejor-servicio-publico-de-transporte/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | Link documento es versión anterior de la ley; reforma específica aprobada el 4-jul-2024 no tiene PDF directo verificado",
    "estado": "Guerrero"
  },
  {
    "id": "GRO-2024-001",
    "fecha": "2024-06-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Ley Número 849 que establece las bases y principios que garanticen el derecho a la movilidad en condiciones de seguridad vial, accesibilidad, eficiencia, sostenibilidad, calidad, inclusión e igualdad, primordialmente a favor de grupos en situación de vulnerabilidad. Prioriza a peatones y ciclistas como usuarios más vulnerables de la vía.",
    "resumen": "El Congreso de Guerrero aprobó la Ley Número 849 de Movilidad y Seguridad Vial, que reemplaza el marco de transporte y vialidad con un enfoque centrado en el derecho humano a la movilidad. La ley prioriza peatones y ciclistas, integra accesibilidad universal, sostenibilidad y coordinación metropolitana. Responde a la crisis de siniestralidad vial del estado, con aproximadamente 1,200 muertes anuales. Iniciativas presentadas por Dip. Héctor Apreza Patrón y por Dip. Nora Yanek Velázquez Martínez junto con Marco Tulio Sánchez Alarcón; consolidadas por la Comisión de Transporte.",
    "link_documento": "https://www.guerrero.gob.mx/wp-content/uploads/2024/09/L849MOVILIDADSEGVIAL.pdf",
    "link_portal": "https://congresogro.gob.mx/63/inicio/2024/06/12/aprueba-el-congreso-la-ley-de-movilidad-y-seguridad-vial-del-estado-de-guerrero/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | Ley 849 publicada en Periódico Oficial del Estado de Guerrero en septiembre 2024; nueva ley que reemplaza el marco anterior de transporte",
    "estado": "Guerrero"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
