const DATA = [
  {
    "id": "MICH-2026-001",
    "fecha": "2026-02-12",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma a la Ley de Movilidad y Seguridad Vial aprobada el 12 de febrero de 2026 que sanciona la violencia ejercida por operadores de transporte público. Establece suspensión de licencia de conducir a operadores involucrados en riñas, confrontaciones o agresiones contra pasajeros, peatones o terceros. La reincidencia en un año conlleva cancelación definitiva de la licencia e inhabilitación mínima de un año, condicionada a curso de 30 horas de manejo de la ira y educación vial.",
    "resumen": "El Pleno aprueba sanciones severas a choferes violentos del transporte público, incluyendo suspensión y cancelación definitiva de licencia ante reincidencia. El proceso probatorio es garantista: requiere dictámenes periciales, grabaciones o declaraciones oficiales. Promovida por la Comisión de Movilidad (Hugo Rangel), que al momento de la aprobación acumula 34 dictámenes sin rezago.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2026/02/12/congreso-del-estado-avala-reformas-para-suspender-licencia-a-operadores-de-transporte-publico-involucrados-en-rinas-por-incidente-vial/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: transporte | REGISTRO AGREGADO EN AUDITORÍA: faltaba en la primera pasada"
  },
  {
    "id": "MICH-2025-007",
    "fecha": "2025-07-02",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa del diputado Hugo Rangel para reformar la Ley de Movilidad y Seguridad Vial incorporando los Vehículos Motorizados Eléctricos Personales (VEMEPE): patinetes eléctricos, monopatines y bicicletas con asistencia eléctrica. Propone registro obligatorio en el Padrón Estatal de Vehículos y obtención de licencia de conducir y tarjeta de circulación para sus operadores.",
    "resumen": "La iniciativa busca llenar el vacío legal para la micromovilidad eléctrica que prolifera en vías urbanas sin regulación. Establece reglas de coexistencia entre VEMEPE, peatones, ciclistas y automovilistas. Presentada por el presidente de la Comisión de Movilidad, quien encabeza la agenda de electromovilidad de la LXXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/07/02/hugo-rangel-plantea-reforma-para-regular-vehiculos-motorizados-electricos-personales/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: movilidad | Promotor: Dip. Hugo Rangel (PT, Comisión de Movilidad)"
  },
  {
    "id": "MICH-2025-002",
    "fecha": "2025-06-20",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Reforma a la Ley de Movilidad y Seguridad Vial aprobada por unanimidad que regula la operación de grúas y corralones para eliminar discrecionalidad y corrupción en el servicio de arrastre vehicular. Incorpora: obligación de registro informático de entradas/salidas de vehículos en corralones, tarifa autorizada de acceso público, información inmediata al usuario sobre costos y procedimientos, causales taxativas para remisión de vehículos, y monitoreo activo por la Secretaría de Seguridad Pública.",
    "resumen": "El Congreso aprueba por unanimidad una reforma que combate décadas de abuso en el servicio de arrastre vehicular y depósitos. La SSP queda obligada a vigilar cumplimiento de tarifas e impedir arbitrariedad en las causales de infracción. Responde a denuncias ciudadanas en Morelia, Uruapan y Lázaro Cárdenas. Promotor: Dip. Hugo Rangel (PT). Iniciativa presentada el 2025-05-07; aprobada el 20-jun.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/06/20/congreso-aprueba-propuesta-de-hugo-rangel-para-frenar-corrupcion-en-gruas-y-corralones/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: tránsito | Iniciativa presentada: 2025-05-07"
  },
  {
    "id": "MICH-2025-001",
    "fecha": "2025-06-19",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_ELEC",
    "extracto": "Reforma a la Ley de Movilidad y Seguridad Vial del Estado aprobada el 19 de junio de 2025 que incorpora: renovación vehicular obligatoria (unidades de transporte masivo no mayores a 12 años para incorporarse al servicio), seguros de responsabilidad civil por daños a terceros de contratación obligatoria, revisión y actualización anual de tarifas conforme a la Estrategia Nacional de Movilidad, y estímulo del 100% en derechos de concesiones para vehículos eléctricos de producción nacional.",
    "resumen": "La LXXVI Legislatura aprueba un paquete integral de reformas a la Ley de Movilidad que moderniza el transporte público. El estímulo del 100% en concesiones para VE nacionales incentiva la transición hacia flotas limpias. El proceso incluyó Parlamento Abierto con operadores, reguladores y usuarios. Promotor: Dip. Hugo Rangel (PT, Comisión de Movilidad). Nota: la aprobación en comisión fue el 18-jun; el decreto se publicó como de fecha 19-jun.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/06/18/congreso-aprueba-dictamen-de-movilidad-propuesto-por-hugo-rangel-incentivos-para-transporte-electrico-y-revision-de-tarifas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad | También encontrado en: transporte"
  },
  {
    "id": "MICH-2025-006",
    "fecha": "2025-06-17",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa del diputado Juan Carlos Barragán para reformar la Ley de Movilidad y Seguridad Vial estableciendo como requisito obligatorio contar con licencia de conducir vigente para adquirir cualquier vehículo automotor o motocicleta. La propuesta surge a petición de Motociclistas Organizados de Michoacán (MOM) ante muertes de jóvenes que conducían sin preparación ni licencia en Morelia, Uruapan y Lázaro Cárdenas.",
    "resumen": "El diputado propone vincular la compra de vehículos al acreditamiento previo de la competencia para conducirlos. Establece un principio básico de responsabilidad social y seguridad vial ante la proliferación de conductores no habilitados. Atiende casos documentados de mortalidad vial ligados a conducción sin licencia.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/06/17/juan-carlos-barragan-presenta-reforma-para-establecer-como-requisito-la-licencia-de-conducir-para-la-compra-de-vehiculos/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: tránsito | Promotor: Dip. Juan Carlos Barragán"
  },
  {
    "id": "MICH-2025-005",
    "fecha": "2025-06-05",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa del diputado Iván Alejandro Arévalo Vera para reformar la Ley de Movilidad y Seguridad Vial en materia de derecho de vía y uso adecuado de las vías públicas estatales. Busca regular la presencia de vehículos abandonados y chatarrizados en vía pública, que generan desorden, riesgo sanitario y obstáculos a la movilidad urbana y rural.",
    "resumen": "El diputado propone una regulación efectiva del espacio vial para garantizar fluidez y salubridad en la movilidad estatal. La iniciativa atiende la problemática de vehículos abandonados como focos de infección y riesgo público en vías estatales. Se presentó días antes del paquete aprobado el 19-jun-2025, aunque no se confirmó su inclusión en ese decreto.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/06/05/diputado-ivan-arevalo-vera-presenta-iniciativa-para-regular-el-derecho-de-via-mejora-del-entorno-y-la-seguridad-vial-en-michoacan/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad | Subtema corregido: MOV_SEG→MOV_INF principal (derecho de vía = infraestructura) | Promotor: Dip. Iván A. Arévalo Vera"
  },
  {
    "id": "MICH-2025-004",
    "fecha": "2025-05-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "MOV_TP",
    "extracto": "Iniciativa de Víctor Manríquez González para reformar la Ley de Movilidad y Seguridad Vial estableciendo un sistema de transporte público accesible e incluyente. Propone que al menos el 10% de las unidades por ruta cuenten con rampa o mecanismos de accesibilidad, y nunca menos de dos unidades adaptadas por ruta, independientemente del tamaño de la flotilla. El estado reporta 130,691 residentes con discapacidad física.",
    "resumen": "El diputado presenta una reforma orientada a garantizar movilidad autónoma y segura a personas con discapacidad en Michoacán. Obliga a concesionarios a implementar accesibilidad física sin comprometer la seguridad de otros pasajeros. Parte de la agenda de inclusión de Movimiento Ciudadano en la LXXVI Legislatura.",
    "link_documento": "",
    "link_portal": "https://www.contramuro.com/transporte-accesible-michoacan-reforma-inclusiva/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: transporte | FECHA APROXIMADA: mayo 2025 sin día exacto confirmado | Promotor: Dip. Víctor Manríquez González (MC)"
  },
  {
    "id": "MICH-2025-003",
    "fecha": "2025-03-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_SEG",
    "extracto": "Iniciativa de Víctor Manríquez González (MC) para regular el cobro de tarifas en carreteras de cuota de jurisdicción estatal y mejorar la seguridad en dichas vías. Propone establecer criterios técnicos y de transparencia para la determinación de tarifas y medidas de seguridad vial en autopistas concesionadas. Responde a quejas ciudadanas sobre cobros excesivos y condiciones inseguras en tramos estatales.",
    "resumen": "El diputado de Movimiento Ciudadano propone un marco regulatorio claro para tarifas y condiciones de seguridad en carreteras de cuota estatales. La iniciativa complementa la agenda de movilidad de la bancada naranja y atiende una demanda ciudadana documentada sobre transparencia en los cobros viales.",
    "link_documento": "",
    "link_portal": "https://esferanoticias.mx/2025/03/27/regular-cobro-de-tarifas-en-carreteras-de-cuota-y-mejorar-seguridad-propone-victor-manriquez/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Presentada | Término búsqueda: vialidad | Promotor: Dip. Víctor Manríquez González (MC)"
  },
  {
    "id": "MICH-2024-001",
    "fecha": "2024-10-17",
    "tipo_acto": "Minuta",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_TP",
    "extracto": "Reforma constitucional al artículo 28 párrafo 4 y adición de párrafo 5 en materia de vías y transporte ferroviario. El Estado recupera el derecho de uso de líneas ferroviarias para servicio de pasajeros; el Ejecutivo Federal puede otorgar asignaciones a empresas públicas o concesiones a particulares. Michoacán fue uno de los 24 congresos estatales que ratificaron la reforma en sesión extraordinaria.",
    "resumen": "La LXXVI Legislatura de Michoacán ratifica en sesión extraordinaria la primera reforma constitucional del sexenio de Sheinbaum, en materia ferroviaria. Permite que el Estado retome la operación del ferrocarril de pasajeros concesionado a privados desde los 90. Tiene implicaciones directas sobre la infraestructura y la posibilidad de nuevos servicios de transporte colectivo en la entidad.",
    "link_documento": "https://comunicacionsocial.diputados.gob.mx/index.php/notilegis/publica-dof-decreto-de-reforma-constitucional-en-materia-de-vias-y-transporte-ferroviario",
    "link_portal": "https://www.redmichoacan.com/2024/10/18/congreso-de-michoacan-aprueba-reforma-constitucional-en-vias-de-transporte-ferroviario/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | Subtema corregido: MOV_INF→MOV_INF+MOV_TP (la infraestructura ferroviaria también habilita transporte de pasajeros)"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
