const DATA = [
  {
    "id": "TLX-2026-004",
    "fecha": "2026-03-31",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 60 ayuntamientos para garantizar mínimo 5 cajones exclusivos para personas con discapacidad motriz o movilidad limitada en espacios públicos y 3 en estacionamientos autorizados, con dimensiones conforme a la NOM (3.8 m × 5 m) y señalética de accesibilidad; incluye sanciones a estacionamientos que incumplan y a particulares que ocupen cajones exclusivos.",
    "resumen": "La Diputada Gabriela Hernández Islas, primera diputada con discapacidad en la historia del Congreso de Tlaxcala, presentó punto de acuerdo para exhortar a los 60 ayuntamientos a garantizar espacios de estacionamiento accesibles para personas con discapacidad motriz, conforme a la Ley de Movilidad y la Ley para Personas con Discapacidad. Propone sanciones a quienes incumplan. Fue turnada a comisiones para análisis.",
    "link_documento": "",
    "link_portal": "https://www.xn--expedientepolticomx-x1b.com/2026/03/gabriela-hernandez-pide-garantizar.html",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | LXV Legislatura | Proponente: Dip. Gabriela Hernández Islas | Presentada 31 mar 2026 | MOV_ACT por accesibilidad de personas con discapacidad en espacio público",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2026-003",
    "fecha": "2026-03-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa para adicionar Capítulo V al Título Segundo de la Ley de Movilidad y Seguridad Vial con disposiciones específicas para conductores y pasajeros de motocicletas, trimotos, cuatrimotos y motocarros: uso obligatorio de casco certificado, prohibición de menores de 12 años sin apoyo adecuado, límite de pasajeros conforme al diseño original del vehículo, y restricción de servicios de transporte por plataformas digitales en moto.",
    "resumen": "La Diputada Madai Pérez Carrillo presentó iniciativa para adicionar un capítulo específico a la Ley de Movilidad que regule la circulación de motocicletas, trimotos, cuatrimotos y motocarros, con énfasis en reducir accidentes. Propone casco certificado obligatorio, restricción de menores de 12 años, límite de pasajeros y prohibición de servicios tipo mototaxi por apps. Fue turnada a Comisiones Unidas de Movilidad y de Puntos Constitucionales.",
    "link_documento": "",
    "link_portal": "https://abctlax.com/propone-madai-perez-fortalecer-ley-de-movilidad-y-seguridad-vial-para-reducir-accidentes-de-motociclistas/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: tránsito | LXV Legislatura | Proponente: Dip. Madai Pérez Carrillo (Morena) | Fecha aproximada (La Polilla: 22 mar 2026)",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2026-002",
    "fecha": "2026-03-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Exhorto a los 60 municipios para construir conjuntamente un Acuerdo por la Movilidad Segura y Humana en Tlaxcala: armonizar reglamentos de tránsito, promover infraestructura segura para peatones y ciclistas, y desarrollar programas permanentes de educación y cultura vial para prevenir accidentes y fortalecer la seguridad en vías públicas.",
    "resumen": "La Diputada Madai Pérez Carrillo presentó punto de acuerdo para exhortar a los 60 municipios a construir conjuntamente un Acuerdo por la Movilidad Segura y Humana, que incluye armonización de reglamentos de tránsito, infraestructura para peatones y ciclistas, y programas de educación vial permanente. La iniciativa fue turnada a las Comisiones Unidas de Movilidad y de Puntos Constitucionales.",
    "link_documento": "",
    "link_portal": "https://lapolilla.com.mx/2026/03/11/madai-perez-propone-acuerdo-estatal-por-una-movilidad-segura-en-tlaxcala/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | LXV Legislatura | Proponente: Dip. Madai Pérez Carrillo (Morena) | MOV_ACT secundario por mención explícita a peatones y ciclistas",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2026-001",
    "fecha": "2026-02-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa para reformar fracciones II, IV y XII del artículo 5, adicionar fracción I-A al artículo 6, e incorporar Capítulo I Bis al Título Décimo de la Ley de Movilidad con artículos 113 Bis a 113 Sexies, estableciendo procedimiento para retiro de vehículos en colisiones menores sin heridos, sin pérdida de cobertura de seguro ni sanción administrativa.",
    "resumen": "La Diputada María Aurora Villeda Temoltzin presentó iniciativa para reformar la Ley de Movilidad y Seguridad Vial para establecer un procedimiento claro que permita a conductores mover sus vehículos en colisiones menores sin heridos, sin pérdida de seguro ni sanciones. Busca reducir la congestión vial, los accidentes secundarios y la incertidumbre jurídica actual. Fue turnada a Comisiones Unidas de Movilidad y de Puntos Constitucionales.",
    "link_documento": "",
    "link_portal": "https://gentetlx.com.mx/2026/02/10/propone-aurora-villeda-agilizar-la-movilidad-vial-mediante-regulacion-de-choques-menores-en-tlaxcala/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | LXV Legislatura | Proponente: Dip. María Aurora Villeda Temoltzin | Fuente: prensa local (gentetlx.com.mx)",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2025-003",
    "fecha": "2025-05-27",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "MOV_TP",
    "extracto": "Decreto que autoriza prórroga de 10 años a la concesión de la autopista Tlaxcala-Xoxtla e inversiones adicionales para su modernización: ampliación a 4 carriles en 16 km, aumento de 15% en cuotas de peaje para equilibrio financiero, e incremento de la contraprestación al Estado de 0.5% a 1.0% semestral.",
    "resumen": "La LXV Legislatura aprobó extender 10 años la concesión de la autopista Tlaxcala-Xoxtla, presentada por la Gobernadora Lorena Cuéllar Cisneros, e inversiones para ampliarla a 4 carriles en un tramo de 16 km, que beneficiará a más de 13,000 vehículos diarios. El decreto incluye un aumento del 15% en tarifas de peaje y el incremento de la contraprestación estatal al doble. Obras en fases 2025-2027.",
    "link_documento": "",
    "link_portal": "https://agendatlaxcala.com/2025/politica/aprueba-lxv-legislatura-ampliacion-de-concesion-para-modernizar-la-autopista-tlaxcala-xoxtla",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: vialidad | LXV Legislatura | Proponente: Poder Ejecutivo (Gobernadora Cuéllar) | MOV_TP secundario por aumento de tarifas de peaje y extensión de concesión | Fuente: agendatlaxcala.com / 385grados.com",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2025-002",
    "fecha": "2025-05-22",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Exhorto a los 60 ayuntamientos de Tlaxcala para que publiquen o adapten sus reglamentos municipales en materia de movilidad y seguridad vial conforme al Tercer Artículo Transitorio de la Ley de Movilidad y Seguridad Vial del Estado; el plazo legal para municipios venció en octubre 2024 sin cumplimiento pleno; incluye priorización de motocicletas.",
    "resumen": "La Diputada Miriam Esmeralda Martínez Sánchez presentó punto de acuerdo para exhortar a los 60 ayuntamientos a publicar o adaptar sus reglamentos de movilidad conforme a la Ley de Movilidad y Seguridad Vial del Estado, cuyo plazo legal venció en octubre 2024 sin cumplimiento. La Legislatura lo aprobó unánimemente en la 35a sesión ordinaria.",
    "link_documento": "",
    "link_portal": "https://congresodetlaxcala.gob.mx/propone-miriam-martinez-exhortar-a-ayuntamientos-de-tlaxcala-para-armonizar-reglamentos-municipales-en-materia-de-movilidad/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: movilidad | LXV Legislatura | Proponente: Dip. Miriam Esmeralda Martínez Sánchez | 35a sesión ordinaria | Fecha aproximada tomada de notas de prensa",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2025-001",
    "fecha": "2025-04-16",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobado",
    "macrotema": "Energía",
    "subtema": "ENE_GEN",
    "subtema_secundario": "ENE_EF",
    "extracto": "Exhorto a la Comisión Estatal de Agua y Saneamiento de Tlaxcala (CEAT) y a los 60 municipios para implementar tecnología fotovoltaica en sistemas de extracción y bombeo de agua potable, con el objetivo de reducir el consumo de energía eléctrica en pozos de agua y disminuir los gastos municipales en recibos de luz de la CFE.",
    "resumen": "La LXV Legislatura aprobó unánimemente exhortar a la CEAT y a los 60 municipios de Tlaxcala a implementar tecnología fotovoltaica en sus sistemas de extracción y bombeo de agua potable. La medida, impulsada por la Diputada Maribel Cervantes Hernández, busca reducir los gastos municipales en electricidad y posicionar a Tlaxcala como referente nacional en uso de energía solar para el suministro de agua, en línea con la Agenda 2030.",
    "link_documento": "",
    "link_portal": "https://congresodetlaxcala.gob.mx/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobado | Término búsqueda: energía | LXV Legislatura | Proponente: Dip. Maribel Cervantes Hernández (Presidenta Comisión Recursos Hidráulicos) | Aprobado en 26a sesión ordinaria | Publicado en POE | ENE_EF secundario por reducción de consumo eléctrico en infraestructura pública",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2024-002",
    "fecha": "2024-11-28",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Turnada a comisiones",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa para adicionar fracción XII al artículo 26 de la Constitución Política de Tlaxcala para reconocer el derecho a la movilidad como derecho humano, obligando a los tres órdenes de gobierno a establecer esquemas de urbanización, reglamentos y políticas públicas que garanticen su ejercicio efectivo.",
    "resumen": "La Diputada Madai Pérez Carrillo propuso adicionar la fracción XII al artículo 26 de la Constitución de Tlaxcala para elevar el derecho a la movilidad a rango constitucional. La propuesta obligaría a los gobiernos estatal, municipal y comunitario a establecer esquemas urbanísticos, reglamentos y políticas públicas que garanticen el ejercicio efectivo de este derecho. Fue presentada en la 25a sesión ordinaria de la LXV Legislatura y turnada a comisiones.",
    "link_documento": "",
    "link_portal": "https://congresodetlaxcala.gob.mx/propone-diputada-madai-perez-carrillo-reconocer-el-derecho-a-la-movilidad-como-derecho-humano-en-la-constitucion-de-tlaxcala/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Turnada a comisiones | Término búsqueda: movilidad | LXV Legislatura | Proponente: Dip. Madai Pérez Carrillo (Morena) | Sesión 25a ordinaria | Reforma constitucional (Art. 26)",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2024-001",
    "fecha": "2024-02-29",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Expedición integral de la Ley de Movilidad y Seguridad Vial del Estado de Tlaxcala (Decreto 336) que establece el marco normativo para garantizar el derecho a la movilidad en condiciones de seguridad vial, accesibilidad, eficiencia, sustentabilidad, calidad, inclusión e igualdad; incluye regulación de tránsito, sanciones y jerarquía de movilidad.",
    "resumen": "La LXIV Legislatura expidió la nueva Ley de Movilidad y Seguridad Vial del Estado de Tlaxcala (Decreto 336), propuesta por el Diputado Jorge Caballero Román. La ley establece el marco normativo integral para garantizar el derecho a la movilidad en condiciones de seguridad, accesibilidad y sustentabilidad en todo el estado, con base en la jerarquía de movilidad.",
    "link_documento": "https://congresodetlaxcala.gob.mx/wp-content/uploads/2024/04/D.336.-SE-EXPIDE-LA-LEY-DE-MOVILIDAD-Y-SEGURIDAD-VIAL-DEL-ESTADO-DE-TLAXCALA.29022024.pdf",
    "link_portal": "https://congresodetlaxcala.gob.mx/aprueba-la-lxiv-legislatura-ley-de-movilidad-y-seguridad-vial-del-estado-de-tlaxcala/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: movilidad | LXIV Legislatura | Proponente: Dip. Jorge Caballero Román | Decreto 336 | PDF del decreto disponible",
    "estado": "Tlaxcala"
  },
  {
    "id": "TLX-2023-001",
    "fecha": "2023-12-14",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "MOV_INF",
    "extracto": "Adiciona Capítulo Quinto Ter a la Ley de Comunicaciones y Transportes para crear Sistema Público de Pasajeros mediante movilidad sostenible en carriles exclusivos con concesiones hasta 30 años; establece que concesiones carreteras deberán priorizar materiales reciclados y energías renovables.",
    "resumen": "La LXIV Legislatura aprobó reformar la Ley de Comunicaciones y Transportes para crear un Sistema Público de Pasajeros con tecnología de movilidad sostenible, operando en carriles exclusivos con concesiones hasta 30 años previa autorización del Congreso. La reforma también estableció que las concesiones carreteras deberán priorizar materiales reciclados y energías renovables, en línea con los objetivos de protección ambiental y seguridad vial.",
    "link_documento": "http://legismex.mty.itesm.mx/estados/ley-tlax/TLA-L-ComuTrans2023_12.pdf",
    "link_portal": "https://congresodetlaxcala.gob.mx/aprueba-lxiv-legislatura-reformar-ley-comunicaciones-transportes/",
    "fuente_verificada": "No",
    "notas": "Estatus portal: Aprobada | Término búsqueda: transporte | LXIV Legislatura | Aprobada en 30a sesión ordinaria del Pleno | MOV_TP principal por concesiones de transporte público; MOV_INF secundario por regulación de concesiones carreteras",
    "estado": "Tlaxcala"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
