const DATA = [
  {
    "id": "SON-2024-001",
    "fecha": "2024-09-25",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Iniciativa con punto de Acuerdo que presenta el diputado René Edmundo García Rojo, integrante del Grupo Parlamentario del Partido del Trabajo, mediante el cual el Congreso del Estado de Sonora, resuelve exhortar a la Secretaría de Infraestructura, Comunicaciones y Transportes para que, en el ámbito de sus atribuciones realicen las acciones necesarias para mejorar la infraestructura vial.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=64",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=64; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2024-002",
    "fecha": "2024-10-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con Punto de Acuerdo que presenta la diputada María Eduwiges Espinoza Tapia, integrante del Grupo Parlamentario de MORENA mediante el cual, el Congreso del Estado de Sonora, resuelve emitir un exhorto al Licenciado Francisco Antonio Astiazarán Gutiérrez, Presidente Municipal de Hermosillo y Presidente de la Junta de Gobierno del Organismo municipal.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=99",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "REVISAR: Organismo municipal Hermosillo; posible agua o transporte | id_portal=99; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2024-003",
    "fecha": "2024-10-24",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con punto de Acuerdo que presentan el diputado Jesús Manuel Scott Sánchez y diputada Gabriela Danitza Félix Bojórquez, integrantes del grupo parlamentario del partido Movimiento Ciudadano, mediante el cual este Poder Legislativo resuelve exhortar al Presidente Municipal de Hermosillo, Sonora, el C. Antonio Astiazarán Gutiérrez, con el objeto de mejorar el transporte urbano.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=157",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "REVISAR: Exhorto Presidente Municipal Hermosillo; posible transporte urbano | id_portal=157; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2025-001",
    "fecha": "2025-02-11",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Iniciativa con punto de Acuerdo que presentan la diputada Gabriela Danitza Félix Bojórquez y el Diputado Jesús Manuel Scott Sánchez, integrantes del Grupo Parlamentario de Movimiento Ciudadano, mediante el cual este Poder Legislativo resuelve exhortar al C. André Georges Foullon Van Lissum, director de la Agencia Nacional de Aduanas de México (ANAM) sobre operación fronteriza.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=159",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Punto de Acuerdo sobre ANAM (Aduanas); frontera → MOV_TP (operación) | id_portal=159; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2025-002",
    "fecha": "2025-02-27",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Folio 1409.- Iniciativa con punto de Acuerdo que presentan el diputado Jesús Manuel Scott Sánchez y la diputada Gabriela Danitza Félix Bojórquez, integrantes del Grupo Parlamentario de Movimiento Ciudadano, mediante el cual este Poder Legislativo resuelve exhortar al Titular del Instituto de Movilidad y Transporte para el Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=164",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=164; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  },
  {
    "id": "SON-2025-003",
    "fecha": "2025-03-11",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Folio 1528.- Iniciativa que presenta el diputado Próspero Valenzuela Múñer, integrante del Grupo Parlamentario de MORENA, con proyecto de Decreto que reforma y adiciona diversas disposiciones de la Ley de Tránsito del Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=113",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=113; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  },
  {
    "id": "SON-2025-004",
    "fecha": "2025-03-13",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_ELEC",
    "subtema_secundario": "",
    "extracto": "Folio 1547.- Iniciativa que presenta el diputado David Figueroa Ortega, integrante del Grupo Parlamentario del Partido Verde Ecologista, con proyecto de Decreto que adiciona diversas disposiciones a la Ley de Hacienda del Estado, en materia de vehículos eléctricos.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=210",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=210; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Hacienda"
  },
  {
    "id": "SON-2025-005",
    "fecha": "2025-03-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Energía",
    "subtema": "ENE_REG",
    "subtema_secundario": "",
    "extracto": "Folio 1592.- Iniciativa que presenta el diputado Héctor Raúl Castelo Montaño, integrante del Grupo Parlamentario de MORENA, con proyecto de Decreto que reforma y adiciona diversas disposiciones a la Ley del Equilibrio Ecológico y Protección al Ambiente del Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=78",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "Ley ambiental turnada a Comisión de Energía; clasificada ENE_REG por enfoque regulatorio | id_portal=78; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Energía, Medio Ambiente y Cambio Climático"
  },
  {
    "id": "SON-2025-006",
    "fecha": "2025-04-01",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Folio 1629.- Iniciativa que presentan los diputados Raúl González De la Vega de esta Sexagésima Cuarta Legislatura y Héctor Raúl Castelo Montaño, integrante del Grupo Parlamentario de MORENA con proyecto de Decreto que reforma y adiciona diversas disposiciones de la Ley de Tránsito del Estado de Sonora, así como de la Ley de Control Vehicular para el Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=80",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=80; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  },
  {
    "id": "SON-2025-007",
    "fecha": "2025-04-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa con punto de Acuerdo que presentan la diputada y diputados del Grupo Parlamentario de Nueva Alianza Sonora, y la diputada Ernestina Castro Valenzuela, para exhortar a diversos ayuntamientos de los municipios del estado de Sonora para que implementen programas y campañas para la sensibilización y educación en materia de movilidad y seguridad vial.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=94",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=94; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2025-008",
    "fecha": "2025-04-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Folio 1827.- Iniciativa que presenta el diputado Emeterio Ochoa Bazúa, integrante del Grupo Parlamentario del Partido Revolucionario Institucional, con proyecto de Decreto que adiciona un segundo párrafo al artículo 214 a la Ley de Tránsito del Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=268",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=268; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  },
  {
    "id": "SON-2025-009",
    "fecha": "2025-04-24",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_TP",
    "subtema_secundario": "",
    "extracto": "Folio 1826.- Iniciativa que presenta el diputado Raúl González de la Vega, con proyecto de Decreto que reforma y adiciona diversas disposiciones de la Ley de Seguridad Pública del Estado de Sonora y con punto de Acuerdo mediante el cual el Congreso del Estado de Sonora, resuelve emitir un respetuoso exhorto al doctor Carlos Hernández Cordero, Titular del Instituto de Movilidad y Transporte del Estado de Sonora.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=274",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=274; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  },
  {
    "id": "SON-2025-010",
    "fecha": "2025-04-30",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa con punto de Acuerdo que presenta la diputada María Eduwiges Espinoza Tapia, integrante del Grupo Parlamentario de MORENA, mediante el cual el Congreso del Estado de Sonora, resuelve exhortar al Ayuntamiento de Hermosillo para que informe sobre si los Reglamentos, en especial el Reglamento de Tránsito Municipal de Hermosillo, se encuentran actualizados.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=85",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=85; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible"
  },
  {
    "id": "SON-2025-011",
    "fecha": "2025-04-30",
    "tipo_acto": "Reforma legislativa",
    "estatus": "En comisión",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Folio 1853.- Iniciativa que presenta el diputado David Figueroa Ortega, integrante del Grupo Parlamentario del Partido Verde Ecologista, con proyecto de Decreto que reforma, deroga y adiciona diversas disposiciones a la Ley de Tránsito del Estado de Sonora y a la Ley de Control Vehicular para el Estado de Sonora, en materia de ordenamiento del tránsito.",
    "resumen": "",
    "link_documento": "",
    "link_portal": "https://congresoson.gob.mx/iniciativa-comentario?id=215",
    "fuente_verificada": "No (solo epígrafe del portal)",
    "notas": "id_portal=215; API: votacion-electronica.api.congresoson.gob.mx; Sin PDF individual disponible | Comisión: Comisión de Movilidad y Seguridad Vial"
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
