const DATA = [
  {
    "id": "VER-2024-001",
    "fecha": "2024-11-21",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa que reforma el artículo 56 de la Ley de Tránsito y Seguridad Vial del Estado de Veracruz",
    "resumen": "Reforma al artículo 56 de la Ley de Tránsito y Seguridad Vial. Presentada por la Dip. Yunes Márquez (PAN). Turnada a comisión.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA5.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 5"
  },
  {
    "id": "VER-2024-002",
    "fecha": "2024-12-04",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo sobre el derecho a la movilidad segura y exhorto a autoridades estatales",
    "resumen": "Punto de acuerdo que reconoce el derecho a la movilidad segura y exhorta a dependencias estatales a fortalecer políticas públicas. Dip. Rosales San Román (PAN). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA10.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 10"
  },
  {
    "id": "VER-2025-001",
    "fecha": "2025-01-08",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_INF",
    "extracto": "Punto de acuerdo sobre movilidad segura y condición de carreteras en el estado",
    "resumen": "Punto de acuerdo que exhorta a autoridades sobre movilidad segura y estado de carreteras estatales. Dip. Córdova Molina (MC). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA14.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 14"
  },
  {
    "id": "VER-2025-002",
    "fecha": "2025-01-13",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo sobre carreteras y autopistas en mal estado en el territorio veracruzano",
    "resumen": "Punto de acuerdo que exhorta a la SICT y al gobierno estatal a atender el deterioro de carreteras y autopistas en Veracruz. Dip. Córdova Molina (MC). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA17.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 17"
  },
  {
    "id": "VER-2025-003",
    "fecha": "2025-06-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo sobre seguridad vial para conductores y motociclistas",
    "resumen": "Punto de acuerdo que exhorta a autoridades a reforzar la seguridad vial para conductores y motociclistas en el estado. Dip. Flores Barnils (MORENA). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA41.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "Sí",
    "notas": "Gaceta 41. Auditoría Gemini 2026-04-02: MOV_SEG confirmado (4/6). Evidencia: seguridad de motociclistas, conductores y transeúntes. No hay indicios de MOV_TP."
  },
  {
    "id": "VER-2025-011",
    "fecha": "2025-07-22",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_ACT",
    "subtema_secundario": "",
    "extracto": "Iniciativa con proyecto de Ley para el Fomento y Promoción del Uso de la Bicicleta y Protección al Ciclista del Estado de Veracruz de Ignacio de la Llave",
    "resumen": "Iniciativa que crea la Ley para el Fomento y Promoción del Uso de la Bicicleta y Protección al Ciclista del Estado de Veracruz. Establece derechos, medidas de seguridad vial y obligaciones para garantizar la movilidad activa de ciclistas. Dip. Pintos Guillén (MORENA). Turnada a comisión. Registro recuperado en verificación de cobertura (PDF escaneado no legible por PDF.js).",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA47.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "Sí",
    "notas": "Gaceta 47 (22/07/2025). PDF escaneado — no detectado en scan automático. Índice verificado visualmente. MOV_ACT: nueva ley de bicicleta."
  },
  {
    "id": "VER-2025-004",
    "fecha": "2025-08-05",
    "tipo_acto": "Dictamen",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Dictamen sobre adeudos de municipios con la Comisión Federal de Electricidad (CFE)",
    "resumen": "Dictamen de la Comisión de Hacienda sobre adeudos municipales con la CFE. Propone mecanismo de saneamiento financiero para regularizar el suministro eléctrico. Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA48.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 48"
  },
  {
    "id": "VER-2025-005",
    "fecha": "2025-08-14",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "MOV_ACT",
    "extracto": "Punto de acuerdo con motivo del Día Mundial del Peatón",
    "resumen": "Punto de acuerdo en conmemoración del Día Mundial del Peatón que exhorta a reforzar políticas de seguridad peatonal. Dip. Pintos Guillén (MORENA). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA49.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 49"
  },
  {
    "id": "VER-2025-006",
    "fecha": "2025-09-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Presentada",
    "macrotema": "Energía",
    "subtema": "ENE_TAR",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo sobre apagones en zona conurbada Veracruz-Boca del Río-Alvarado-Medellín y condonación del pago de servicio de energía eléctrica",
    "resumen": "Punto de acuerdo que exhorta a la CFE a atender los apagones recurrentes en la zona conurbada Veracruz-Boca del Río-Alvarado-Medellín, y a condonar el pago del servicio eléctrico a los usuarios afectados. Dip. Rosales San Román (PAN). Clasificación ENE_TAR confirmada: centralidad en afectaciones de suministro y condonación de cobros.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA54.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "Sí",
    "notas": "Gaceta 54. Auditoría Gemini 2026-04-02: ENE_TAR confirmado (4/6). Evidencia: apagones + condonación pago CFE."
  },
  {
    "id": "VER-2025-007",
    "fecha": "2025-09-25",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa que reforma la Ley de Tránsito y Seguridad Vial del Estado de Veracruz",
    "resumen": "Iniciativa de reforma a la Ley de Tránsito y Seguridad Vial. Presentada por el Grupo Mixto (Dip. Ortega Ruiz). Turnada a comisión.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA56.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 56"
  },
  {
    "id": "VER-2025-008",
    "fecha": "2025-10-23",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Movilidad",
    "subtema": "MOV_INF",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo que exhorta a la SICT a eximir del pago de peaje a habitantes afectados por inundaciones",
    "resumen": "Punto de acuerdo que exhorta a la SICT a eximir del pago de peaje en autopistas a habitantes de zonas afectadas por inundaciones en Veracruz. Dip. Pintos Guillén (MORENA). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA60.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 60"
  },
  {
    "id": "VER-2025-009",
    "fecha": "2025-11-06",
    "tipo_acto": "Reforma legislativa",
    "estatus": "Presentada",
    "macrotema": "Movilidad",
    "subtema": "MOV_SEG",
    "subtema_secundario": "",
    "extracto": "Iniciativa que adiciona el artículo 77 Bis a la Ley de Tránsito: prohíbe a conductores obstruir o impedir el libre tránsito de vehículos de emergencia",
    "resumen": "Iniciativa que adiciona el artículo 77 Bis a la Ley de Tránsito y Seguridad Vial: crea prohibición expresa para conductores de obstruir o dificultar el paso a vehículos de emergencia en vía pública. Regula conducta vial de terceros, no la operación de las unidades de emergencia. Dip. Pintos Guillén (MORENA). Turnada a comisión.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA62.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "Sí",
    "notas": "Gaceta 62. Auditoría Gemini 2026-04-02: MOV_SEG confirmado (6/6, criterios c1–c6). Articulado crea obligación de conducta vial en vía pública."
  },
  {
    "id": "VER-2026-001",
    "fecha": "2026-03-19",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo sobre el derrame de hidrocarburos en el Golfo de México",
    "resumen": "Punto de acuerdo que exhorta a PEMEX y autoridades federales a atender el derrame de hidrocarburos ocurrido en el Golfo de México en marzo de 2026 y sus efectos en las costas de Veracruz. Dip. Córdova Molina (MC). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA86.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 86. Derrame Golfo de México mar-abr 2026."
  },
  {
    "id": "VER-2026-002",
    "fecha": "2026-04-01",
    "tipo_acto": "Punto de Acuerdo",
    "estatus": "Aprobada",
    "macrotema": "Energía",
    "subtema": "ENE_HC",
    "subtema_secundario": "",
    "extracto": "Punto de acuerdo para solicitar la comparecencia de la Procuraduría Federal de Protección al Ambiente sobre el derrame de hidrocarburos",
    "resumen": "Punto de acuerdo que solicita la comparecencia de la PROFEPA ante el Congreso de Veracruz para informar sobre las acciones tomadas ante el derrame de hidrocarburos en el Golfo de México. Dip. Córdova Molina (MC). Aprobado.",
    "link_documento": "https://www.legisver.gob.mx/gaceta/gacetaLXVII/GACETA89.pdf",
    "link_portal": "https://www.legisver.gob.mx/Inicio.php?p=sesiones",
    "fuente_verificada": "No",
    "notas": "Gaceta 89. Segunda iniciativa sobre el derrame HC."
  }
];

const SUBTEMAS = {
  "ENE_GEN": "Generación y transición energética",
  "ENE_REG": "Marco regulatorio energético",
  "ENE_TAR": "Tarifas, subsidios y cortes de suministro",
  "ENE_HC": "Hidrocarburos, gas y combustibles",
  "ENE_EF": "Eficiencia energética y alumbrado",
  "MOV_SEG": "Seguridad vial",
  "MOV_INF": "Infraestructura vial",
  "MOV_ACT": "Movilidad activa",
  "MOV_TP": "Transporte público y concesiones",
  "MOV_ELEC": "Electromovilidad y vehículos eléctricos"
};
